import test from 'node:test';
import assert from 'node:assert/strict';
import {espnMatch,espnRoster,espnSchedule,statsBombMatch,collectPriorMatches} from '../lib/espn-squad.mjs';
const captured='2026-09-27T12:00:00Z';
const players=Array.from({length:11},(_,n)=>({starter:true,athlete:{id:String(n),displayName:'Player '+n}}));
function summary(date='2026-09-20T12:00:00Z'){return {header:{id:'1',competitions:[{date,status:{type:{completed:true,state:'post',shortDetail:'FT'}},competitors:[{homeAway:'home',score:'2',team:{id:'h',displayName:'Home'}},{homeAway:'away',score:'1',team:{id:'a',displayName:'Away'}}]}]},rosters:[{homeAway:'home',roster:players},{homeAway:'away',roster:players.map(p=>({...p,athlete:{...p.athlete,id:'a'+p.athlete.id}}))}],leaders:[{statistics:[{name:'expectedGoals',value:1.2}]}]};}
test('ESPN historical XI/results are confirmed without inventing team xG from a selected player leader',()=>{const m=espnMatch(summary(),'1','mls',captured);assert.equal(m.lineup.status,'historical-confirmed');assert.equal(m.xg,null);assert.equal(m.score.home,2);assert.equal(m.lineup.home[0].id,'espn:0');});
test('ESPN match timing rejects future final results and non-FT settlement',()=>{assert.throws(()=>espnMatch(summary('2026-09-27T14:00:00Z'),'1','mls',captured),/timing/);const d=summary();d.header.competitions[0].status.type.shortDetail='AET';assert.equal(espnMatch(d,'1','mls',captured).status,'unconfirmed');});
test('ESPN starting XI is current only inside its announcement window',()=>{const d=summary('2026-09-27T13:00:00Z');Object.assign(d.header.competitions[0].status.type,{state:'pre',completed:false});assert.equal(espnMatch(d,'1','mls',captured).lineup.status,'provider-confirmed');d.header.competitions[0].date='2026-10-10T13:00:00Z';assert.equal(espnMatch(d,'1','mls',captured).lineup.status,'unknown');});
test('published roster identity is checked and is never fitness verification',()=>{assert.throws(()=>espnRoster({team:{id:2},athletes:[]},'1',captured),/identity/);const roster=espnRoster({team:{id:'1'},athletes:[{id:'3',displayName:'Player'}]},'1',captured);assert.equal(roster.status,'published-roster');assert.match(roster.note,/not proof/);});
test('schedule normalizes both object and string scores',()=>{const e=summary().header.competitions[0];e.competitors[0].score={value:2};assert.equal(espnSchedule({events:[{id:'1',competitions:[e]}]},'mls')[0].score.home,2);});
test('a match repeated in both team schedules cannot halve the player-learning sample',()=>{const unique=Array.from({length:60},(_,n)=>({id:String(n),homeId:'h',awayId:'a',finished:true,kickoff:new Date(Date.UTC(2026,0,n+1)).toISOString()})),prior=collectPriorMatches([...unique,...unique,...unique],'h',40,Date.parse(captured));assert.equal(prior.length,40);assert.equal(new Set(prior.map(m=>m.id)).size,40);assert.equal(prior[0].id,'59');});
test('licensed shot parser uses regulation periods, checks coverage and preserves player provenance',()=>{const meta={match_status:'available',match_id:1,match_date:'2023-01-01',home_team:{home_team_id:1,home_team_name:'Home'},away_team:{away_team_id:2,away_team_name:'Away'},home_score:1,away_score:0};const events=[1,2].map(team=>({type:{name:'Starting XI'},team:{id:team},tactics:{lineup:Array.from({length:11},(_,n)=>({player:{id:team*100+n,name:'P'+n},position:{name:'Defender'}}))}}));events.push(...[1,2,5].map(period=>({id:String(period),type:{name:'Shot'},period,team:{id:1},minute:period*10,player:{id:100,name:'P0'},shot:{statsbomb_xg:.2,outcome:{name:'Goal'}}})));const m=statsBombMatch(meta,events,'mls',captured);assert.equal(m.shots.length,2);assert.equal(m.xg.home,.4);assert.equal(m.shots[0].playerId,'statsbomb:100');assert(m.kickoffApproximate);delete events[2].shot.statsbomb_xg;assert.throws(()=>statsBombMatch(meta,events,'mls',captured),/coverage/);});
