import {withPawaMarkets,PAWA_MARKET_TYPES} from '../lib/market-outcomes.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {scoreProbabilities,probabilityFor} from '../lib/arata-model.mjs';
import {settleMarket,marketLabel} from '../lib/markets.mjs';
import {parsePawaEvent} from '../lib/web-parsers.mjs';
import {generateTicketPlan} from '../lib/league-tickets.mjs';
const cells=scoreProbabilities(1.5,1.1),f={status:'finished',score:{home:2,away:0}},m=(market,selection,line=null)=>({market,selection,line,period:'FT'});
test('team totals, clean sheets and win-to-nil probabilities use the exact team score',()=>{for(const type of ['HOME_TOTALS','AWAY_TOTALS'])assert.ok(Math.abs(probabilityFor(cells,m(type,'over',.5))+probabilityFor(cells,m(type,'under',.5))-1)<1e-12);assert.ok(Math.abs(probabilityFor(cells,m('HOME_CLEAN_SHEET','yes'))-Math.exp(-1.1))<1e-10);for(const type of ['HOME_CLEAN_SHEET','AWAY_CLEAN_SHEET','HOME_WIN_TO_NIL','AWAY_WIN_TO_NIL'])assert.ok(Math.abs(probabilityFor(cells,m(type,'yes'))+probabilityFor(cells,m(type,'no'))-1)<1e-12);assert.equal(settleMarket(m('HOME_TOTALS','over',1.5),f),'won');assert.equal(settleMarket(m('AWAY_CLEAN_SHEET','yes'),f),'lost');assert.equal(settleMarket(m('HOME_WIN_TO_NIL','yes'),f),'won');assert.equal(settleMarket(m('AWAY_WIN_TO_NIL','no'),f),'won');});
test('combined result markets use joint probabilities and odd/even includes zero',()=>{for(const type of ['ODD_EVEN','HOME_ODD_EVEN','AWAY_ODD_EVEN'])assert.ok(Math.abs(probabilityFor(cells,m(type,'odd'))+probabilityFor(cells,m(type,'even'))-1)<1e-12);assert.equal(settleMarket(m('AWAY_ODD_EVEN','even'),f),'won');assert.equal(settleMarket(m('RESULT_TOTALS','home_under',2.5),f),'won');assert.equal(settleMarket(m('RESULT_BTTS','home_no'),f),'won');const joint=probabilityFor(cells,m('RESULT_BTTS','home_yes')),product=probabilityFor(cells,m('1X2','home'))*probabilityFor(cells,m('BTTS','yes'));assert.notEqual(joint,product);assert.equal(probabilityFor(cells,m('HOME_TOTALS','over',1)),null);assert.equal(probabilityFor(cells,{...m('TOTALS','over',.5),period:'1H'}),null);assert.equal(settleMarket(m('RESULT_BTTS','invalid'),f),'pending');});
test('public bookmaker parser preserves expanded prices and exact full-time market identity',()=>{const names=['Total Score Over/Under - FT - Home Team','Total Score Over/Under - FT - Away Team','Clean Sheet Home Team - FT','Win to Nil Home Team - FT','Odd / Even - FT','1X2 and Totals - FT','1X2 and Both Teams To Score - FT'];const e={id:'real-contract',category:{id:'2'},competition:{name:'League'},region:{name:'Country'},startTime:'2099-01-01T12:00:00Z',participants:[{name:'Home',position:1},{name:'Away',position:2}],markets:names.map((name,i)=>({marketType:{name},row:[{specifier:{total:'1.5'},prices:[{id:String(i),name:i<2?'Over':i===4?'Even':i===5?'1 - Under':i===6?'1 - No':'Yes',odds:1.8,handicap:i<2||i===5?'1.5':undefined}]}]}))};const q=parsePawaEvent(e,new Date().toISOString(),'public').quotes;assert.equal(q.length,7);assert.equal(q[0].market,'HOME_TOTALS');assert.equal(q[5].selection,'home_under');assert.equal(q[6].selection,'home_no');assert.equal(q[5].line,1.5);assert.ok(q.every(q=>q.period==='FT'&&q.odds===1.8));assert.match(marketLabel({...q[0],home:'Home',away:'Away'}),/Home.*Over 1.5/);});
test('expanded markets enter automatic tickets only with positive value, current quotes and existing risk floors',()=>{const now=Date.now(),stamp=new Date(now).toISOString(),picks=[0,1,2].map(i=>({id:'p'+i,fixtureId:'f'+i,home:'Team '+i,away:'Opponent '+i,kickoff:new Date(now+3600000).toISOString(),...m('HOME_TOTALS','over',.5),probability:.9,odds:1.2,edge:.9-1/1.2,confidence:'medium',created:stamp,modelCaptured:stamp,oddsCaptured:stamp,bookmaker:'B',outcome:'pending'})),quotes=picks.map(p=>({...p,captured:stamp}));const plan=generateTicketPlan(picks,quotes,{legCount:2,risk:'balanced',now});assert.ok(plan.tickets.length>0);assert.ok(plan.tickets.every(t=>t.legs.length===2));assert.equal(generateTicketPlan(picks.map(p=>({...p,probability:.5})),quotes,{legCount:2,risk:'balanced',now}).tickets.length,0);});

test('published market discovery respects the bookmaker seven-market view limit',()=>{const query={query:{eventType:'LIVE'},view:{},take:100,skip:0},r=withPawaMarkets({queries:[query]});assert.equal(r.queries.length,3);assert.ok(r.queries.every(q=>q.view.marketTypes.length<=7&&q.take===100&&q.query.eventType==='LIVE'));assert.deepEqual(r.queries.flatMap(q=>q.view.marketTypes),PAWA_MARKET_TYPES);assert.deepEqual(query.view,{});});
