import test from 'node:test';
import assert from 'node:assert/strict';
import {generateTicketPlan,ticketAdvice} from '../lib/league-tickets.mjs';
import {ticketTotals} from '../lib/live.mjs';
import {ticketPreview} from '../lib/domain.mjs';
const now=Date.now(),stamp=new Date(now).toISOString();
const pick=(n,probability=.92)=>({id:'p'+n,fixtureId:'f'+n,home:'Home '+n,away:'Away '+n,league:'League '+n%3,market:'1X2',period:'FT',selection:'home',line:null,confidence:'high',probability,odds:1.15,edge:probability-1/1.15,bookmaker:'Test quote',oddsCaptured:stamp,outcome:'pending',kickoff:new Date(now+3600000).toISOString()});
const quote=p=>({...p,period:'FT',captured:stamp});
test('generation returns varied exact-length tickets for every selection from 1 to 10',()=>{
 const picks=Array.from({length:15},(_,n)=>pick(n)),quotes=picks.map(quote);
 for(let legCount=1;legCount<=10;legCount++){const plan=generateTicketPlan(picks,quotes,{legCount,now});assert.ok(plan.tickets.length>=2,'variety at '+legCount);for(const t of plan.tickets){assert.equal(t.legs.length,legCount);assert.equal(new Set(t.legs.map(l=>l.fixtureId)).size,legCount);assert.ok(t.advice.messages.length);assert.ok(Math.abs(t.probability-.92**legCount)<1e-10);}assert.equal(new Set(plan.tickets.map(t=>t.legs.map(l=>l.fixtureId).sort().join('|'))).size,plan.tickets.length);}
});
test('10-pick limit is shared by model and price-only previews; eleven is rejected',()=>{const legs=Array.from({length:11},(_,n)=>pick(n));assert.ok(Math.abs(ticketTotals(legs.slice(0,10),10).potentialReturn-10*1.15**10)<1e-9);assert.equal(ticketPreview(legs.slice(0,10),10).odds,ticketTotals(legs.slice(0,10),10).odds);assert.throws(()=>ticketTotals(legs,10));assert.throws(()=>ticketPreview(legs,10));assert.throws(()=>generateTicketPlan(legs,legs.map(quote),{legCount:11,now}));assert.throws(()=>generateTicketPlan(legs,legs.map(quote),{legCount:2.5,now}));});
test('risk rules refuse a longer ticket rather than padding or silently returning fewer legs',()=>{const picks=Array.from({length:12},(_,n)=>pick(n,.8)),quotes=picks.map(quote).map(q=>({...q,odds:1.4})),priced=picks.map(p=>({...p,odds:1.4,edge:.8-1/1.4}));assert.equal(generateTicketPlan(priced,quotes,{legCount:10,risk:'cautious',now}).tickets.length,0);assert.ok(generateTicketPlan(priced,quotes,{legCount:10,risk:'extended',now}).tickets.every(t=>t.advice.risk==='High risk'));const scarce=generateTicketPlan(priced.slice(0,3),quotes,{legCount:10,now});assert.equal(scarce.tickets.length,0);assert.match(scarce.reason,/Only 3 matches/);});
test('unknown/low confidence, future timestamps, stale models and unpriced picks cannot pad tickets',()=>{const a=pick(0),b=pick(1);for(const bad of [{...b,confidence:'low'},{...b,confidence:undefined},{...b,modelStale:true},{...b,oddsCaptured:new Date(now+1000).toISOString()},{...b,edge:-.02}])assert.equal(generateTicketPlan([a,bad],[quote(a),quote(bad)],{legCount:2,now}).tickets.length,0);});
test('mix supports ten picks across available leagues while limiting concentration and shared teams',()=>{const picks=Array.from({length:16},(_,n)=>pick(n)),plan=generateTicketPlan(picks,picks.map(quote),{legCount:10,mix:true,now});assert.ok(plan.tickets.length);for(const t of plan.tickets){const counts=new Map();for(const l of t.legs)counts.set(l.league,(counts.get(l.league)||0)+1);assert.ok(counts.size>=2);assert.ok([...counts.values()].every(n=>n<=5));}const same=picks.map(p=>({...p,home:'Shared team'}));assert.equal(generateTicketPlan(same,same.map(quote),{legCount:2,now}).tickets.length,0);});
test('advice quantifies loss chance and explains removing the weakest leg; live quotes stay unassessed',()=>{const legs=[pick(0,.8),pick(1,.9)],a=ticketAdvice(legs);assert.ok(Math.abs(a.lossProbability-.28)<1e-10);assert.equal(a.weakest.fixtureId,'f0');assert.match(a.messages.join(' '),/90.0%/);assert.equal(ticketAdvice([{...legs[0],inPlay:true}]).risk,'Unassessed');});
