import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync} from 'node:fs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec("CREATE TABLE api_cache(key TEXT PRIMARY KEY,expires REAL,payload TEXT);CREATE TABLE fixtures(id TEXT,kickoff TEXT,payload TEXT);CREATE TABLE predictions(id TEXT PRIMARY KEY,fixture_id TEXT,created TEXT,outcome TEXT,payload TEXT);CREATE TABLE odds_snapshots(id TEXT,fixture_id TEXT,captured TEXT,payload TEXT);");
sqlite.exec(readFileSync(new URL('../drizzle/0002_strong_fixer.sql',import.meta.url),'utf8'));
globalThis.__ARATA_DB={prepare(sql){return {params:[],bind(...p){this.params=p;return this;},async all(){return {results:sqlite.prepare(sql).all(...this.params)};},async first(){return sqlite.prepare(sql).get(...this.params);},async run(){sqlite.prepare(sql).run(...this.params);return {success:true};}};},async batch(commands){for(const c of commands)await c.run();return [];}};
const bundle=await build({entryPoints:['lib/store.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-db',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env={DB:globalThis.__ARATA_DB}',loader:'js'}));}}]});
const {historyPage,latestPredictions,predictionMetrics,recentOdds,savePredictions,resultFixtureHeads,liveFixtureHeads,researchFixtureHeads,cachedReadMany,cachedWriteMany}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
for(const f of [{id:'future',kickoff:'2099-01-01T15:00:00Z',status:'scheduled'},{id:'past',kickoff:'2026-01-01T15:00:00Z',status:'finished'}])sqlite.prepare('INSERT INTO fixtures VALUES(?,?,?)').run(f.id,f.kickoff,JSON.stringify(f));
for(const p of [{id:'1',fixtureId:'future',created:'2026-09-26T22:00:00Z',outcome:'pending',home:'Arsenal',away:'Chelsea',predictor:'arata',market:'1X2',selection:'home'},{id:'2',fixtureId:'future',created:'2026-09-27T08:00:00Z',outcome:'pending',home:'Arsenal',away:'Chelsea',predictor:'arata',market:'1X2',selection:'home'},{id:'3',fixtureId:'past',created:'2026-01-01T12:00:00Z',outcome:'won',home:'Inter Miami',away:'Columbus',predictor:'arata',market:'1X2',selection:'home'}])sqlite.prepare('INSERT INTO predictions VALUES(?,?,?,?,?)').run(p.id,p.fixtureId,p.created,p.outcome,JSON.stringify(p));
test('history pagination searches the complete log and preserves older snapshots',async()=>{const a=await historyPage('Chelsea Arsenal','pending',0,1),b=await historyPage('Chelsea Arsenal','pending',1,1);assert.equal(a.total,2);assert.equal(a.records[0].id,'2');assert.equal(b.records[0].id,'1');assert.equal((await historyPage('%','all')).total,0);assert.equal((await historyPage('Columbus','won')).total,1);});
test('ticket board reads one latest forecast per exact market and predictor',async()=>{assert.deepEqual((await latestPredictions()).map(p=>p.id),['2']);assert.deepEqual((await latestPredictions(true)).map(p=>p.id),['3']);});
test('aggregate metrics cover all rows and use Kampala day boundaries',async()=>{const m=await predictionMetrics([{status:'won',stake:100,potentialReturn:180}]);assert.equal(m.total,3);assert.equal(m.pending,2);assert.equal(m.accuracy,1);assert.equal(m.roi,.8);assert.equal(m.trend[0].date,'2026-01-01');});
test('latest price snapshots query does not discard the audit records',async()=>{for(const [id,captured]of [['a','2026-01-01'],['b','2026-01-02']])sqlite.prepare('INSERT INTO odds_snapshots VALUES(?,?,?,?)').run(id,'future',captured,JSON.stringify({id,bookmaker:'B'}));assert.equal((await recentOdds())[0].id,'b');assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM odds_snapshots').get().n,2);});

test('current heads update without scanning or deleting the prediction audit log',async()=>{await savePredictions([{id:'4',fixtureId:'future',kickoff:'2099-01-01T15:00:00Z',created:'2026-09-27T09:00:00Z',outcome:'pending',home:'Arsenal',away:'Chelsea',predictor:'arata',market:'1X2',selection:'home'}]);assert.equal((await latestPredictions())[0].id,'4');assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM predictions').get().n,4);await savePredictions([{id:'older',fixtureId:'future',kickoff:'2099-01-01T15:00:00Z',created:'2026-09-26T09:00:00Z',outcome:'pending',home:'Arsenal',away:'Chelsea',predictor:'arata',market:'1X2',selection:'home'}]);assert.equal((await latestPredictions())[0].id,'4');});

test('lean research and result reads preserve owner quotes and verified result timestamps',async()=>{const fixture={id:'context',home:'Home',away:'Away',kickoff:'2026-01-01T12:00:00Z',status:'finished',score:{home:1,away:0},resultSource:'LiveScore',finalConfirmedAt:'2026-01-01T14:00:00Z',livePeriod:'FULL_TIME',arataModel:{available:true,markets:[{market:'BTTS'}]},quotes:[{source:'Public bookmaker feed',odds:1.6},{source:'Owner-entered',odds:1.8}]};sqlite.prepare('INSERT INTO fixtures VALUES(?,?,?)').run(fixture.id,fixture.kickoff,JSON.stringify(fixture));const research=(await researchFixtureHeads()).find(f=>f.id===fixture.id);assert.equal(research.quotes.length,1);assert.equal(research.quotes[0].odds,1.8);assert.equal(research.arataModel.available,true);const result=(await resultFixtureHeads()).find(f=>f.id===fixture.id);assert.equal(result.finalConfirmedAt,fixture.finalConfirmedAt);assert.equal(result.livePeriod,'FULL_TIME');assert.deepEqual(result.score,fixture.score);assert.equal(result.quotes,undefined);});
test('large tracking lists and cache batches stay within D1 parameter limits',async()=>{const ids=Array.from({length:250},(_,i)=>'tracked-'+i);for(const id of ids)sqlite.prepare('INSERT INTO fixtures VALUES(?,?,?)').run(id,'2020-01-01T00:00:00Z',JSON.stringify({id,status:'finished',score:{home:0,away:0}}));const original=globalThis.__ARATA_DB.prepare;globalThis.__ARATA_DB.prepare=sql=>{const statement=original(sql),bind=statement.bind;statement.bind=function(...params){assert.ok(params.length<=100);return bind.apply(this,params);};return statement;};try{const found=await liveFixtureHeads(ids);assert.ok(ids.every(id=>found.some(f=>f.id===id)));const writes=ids.map((key,i)=>({key,expires:200,value:{data:i}}));await cachedWriteMany(writes);assert.equal((await cachedReadMany(ids)).size,250);}finally{globalThis.__ARATA_DB.prepare=original;}});
