import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {openSqlite} from '../backend/sqlite-client.mjs';import {databaseAdapter} from '../backend/database-adapter.mjs';
test('automatic learning activates, atomically persists its audit and survives restart without rewriting forecasts or tickets',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'arata-learning-test-')),dbPath=path.join(directory,'learning.sqlite'),bundle=path.join(directory,'learning.mjs');let connection;
 try{
  await build({entryPoints:['lib/learning.ts'],outfile:bundle,bundle:true,platform:'node',format:'esm',target:'node22',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env={DB:globalThis.__ARATA_DB};',loader:'js'}));}}]});
  connection=await openSqlite(dbPath,await readFile('backend/postgres.sql','utf8'));globalThis.__ARATA_DB=databaseAdapter(connection);const db=globalThis.__ARATA_DB,commands=[],originals=[];
  const now=Date.now(),start=now-45*86400000;
  for(let i=0;i<800;i++){const id='f'+i,kickoff=new Date(start+i*3600000).toISOString(),created=new Date(Date.parse(kickoff)-3600000).toISOString(),yes=i%5<3,f={id,leagueId:'epl',home:'Home '+i,away:'Away '+i,kickoff,status:'finished',score:yes?{home:1,away:1}:{home:0,away:0},resultSource:'LiveScore',finalConfirmedAt:new Date(Date.parse(kickoff)+7200000).toISOString()},p={id:'p'+i,fixtureId:id,predictor:'arata',modelVersion:'arata-adaptive-goals-v3',kickoff,created,modelCaptured:created,market:'BTTS',selection:'yes',line:null,period:'FT',probability:.9,outcome:yes?'won':'lost'};const payload=JSON.stringify(p);originals.push(payload);commands.push(db.prepare('INSERT INTO fixtures VALUES(?,?,?,?)').bind(id,kickoff,JSON.stringify(f),created),db.prepare('INSERT INTO predictions VALUES(?,?,?,?,?)').bind(p.id,id,created,p.outcome,payload));}
  commands.push(db.prepare('INSERT INTO tickets VALUES(?,?,?,?)').bind('real-record',new Date(now).toISOString(),'won',JSON.stringify({lockedOdds:2,stake:10})));await db.batch(commands);
  const learner=await import(pathToFileURL(bundle).href);await learner.learningStatus();let report;const deadline=Date.now()+10000;do{await new Promise(r=>setTimeout(r,30));report=await learner.learningRegistry();}while((report.running||!report.checkedAt)&&Date.now()<deadline);
  assert.equal(report.eligibleMatches,800);assert.ok(report.active,report.error||report.message);assert.equal(report.runs.at(-1).status,'activated');const revision=report.active.revision;
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM api_cache WHERE key LIKE 'learning:audit:%'").first()).n,1);
  assert.deepEqual((await db.prepare('SELECT payload FROM predictions ORDER BY created').all()).results.map(r=>r.payload),originals);
  assert.equal((await db.prepare('SELECT payload FROM tickets WHERE id=?').bind('real-record').first()).payload,JSON.stringify({lockedOdds:2,stake:10}));
  await connection.close();connection=await openSqlite(dbPath,'');globalThis.__ARATA_DB=databaseAdapter(connection);const restarted=await import(pathToFileURL(bundle).href+'?restart=1');const restored=await restarted.learningRegistry();assert.equal(restored.active.revision,revision);assert.equal(restored.runs.length,1);assert.ok(restored.active.calibrators['*|BTTS']);
 }finally{if(connection)await connection.close();delete globalThis.__ARATA_DB;await rm(directory,{recursive:true});}
});
