import {readPublicResponse} from '../lib/network.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {applyLiveUpdates,ticketProgress,mergeLiveState,mergeFreshState,newerLive,filterFixtureWindow,trackedFixtureDays,isCurrentLive} from '../lib/live.mjs';
import {goalEvents,parseLiveScoreboard,parsePawaTracked} from '../lib/live-details.mjs';
import {dateRange,dayKey} from '../lib/domain.mjs';
const capture='2026-09-27T11:45:00Z',base={id:'saved',home:'China',away:'New Zealand',league:'International Friendlies',leagueId:'web:international-friendlies',kickoff:'2026-09-27T11:35:00Z',status:'live',externalIds:{livescore:'1894381',betpawa:'pawa'},liveCaptured:capture,score:{home:0,away:1},liveClock:"11'",quotes:[]};
const detail={Eid:'1894381',T1:[{Nm:'China'}],T2:[{Nm:'New Zealand'}],Esd:20260927113500,Eps:"11'",Esid:2,Tr1:'0',Tr2:'1','Incs-s':{'1':[{Min:4,Nm:2,Incs:[{Min:4,Nm:2,ID:'0',Pn:'Tyler Bindon',IT:36},{Min:4,Nm:2,Pn:'Callum McCowatt',IT:63}]}]}};
test('real LiveScore scoreboard supplies named scorers, assist and minutes',()=>{const f=parseLiveScoreboard(detail,capture,'public',base);assert.equal(f.id,'saved');assert.equal(f.goalScorers[0].name,'Tyler Bindon');assert.equal(f.goalScorers[0].time,"4'");assert.equal(f.goalScorers[0].assist,'Callum McCowatt');assert.throws(()=>parseLiveScoreboard({...detail,Eid:'wrong'},capture,'public',base));assert.throws(()=>parseLiveScoreboard({...detail,T1:[{Nm:'Other'}]},capture,'public',base));});
test('goal events exclude missed penalties and shootouts and preserve added time',()=>{const d={Incs:{'2':[{Min:90,MinEx:3,Nm:1,IT:37,Pn:'Penalty scorer'},{Min:80,Nm:2,IT:39,Pn:'Own goal'},{Min:80,Nm:2,IT:40,Pn:'Missed'}],'3':[{Min:105,Nm:1,IT:36,Pn:'Extra time'}],'5':[{Min:1,Nm:1,IT:37,Pn:'Shootout'}]}};const goals=goalEvents(d,capture,'public');assert.equal(goals.length,2);assert.equal(goals[1].time,"90 + 3'");assert.equal(goals[0].kind,'own-goal');assert.equal(goalEvents({},capture,'public'),null);assert.deepEqual(goalEvents({Incs:{}},capture,'public'),[]);});
test('stable bookmaker identifiers update a saved leg despite provider league aliases',()=>{const update={...base,id:'different',league:'Friendlies',leagueId:'web:other',externalIds:{betpawa:'pawa'},liveCaptured:'2026-09-27T11:46:00Z',score:{home:1,away:1}};const fs=applyLiveUpdates([base],[update]);assert.equal(fs.length,1);const leg={id:'leg',fixtureId:'saved',home:base.home,away:base.away,odds:2.5};const progress=ticketProgress({legs:[leg]},fs)[0];assert.deepEqual(progress.score,{home:1,away:1});assert.equal(progress.odds,2.5);assert.equal(progress.fixtureId,'saved');});
test('live details preserve models and older responses cannot undo a newer score',()=>{const prior={...base,arataModel:{version:'keep'},models:{home:{probability:.4}},goalScorers:[{name:'Scorer'}],eventsCaptured:capture};const older={...base,liveCaptured:'2026-09-27T11:44:00Z',score:{home:0,away:0}};assert.equal(newerLive(prior,older),prior);const next=newerLive(prior,{...base,models:{},liveCaptured:'2026-09-27T11:46:00Z'});assert.deepEqual(next.models,prior.models);assert.deepEqual(next.goalScorers,prior.goalScorers);assert.deepEqual(next.arataModel,prior.arataModel);});
test('late dashboard responses cannot roll back saved progress or mutate previous state',()=>{const ticket={id:'ticket',status:'pending',legs:[],progress:[{fixtureId:'saved',liveCaptured:capture,score:{home:0,away:1}}]},previous={fixtures:[base],tickets:[ticket],eligibleSelections:[],picks:[],allPicks:[],liveUpdated:capture,range:{from:'2026-09-27',to:'2026-09-27'}};const next={...previous,fixtures:[{...base,liveCaptured:'2026-09-27T11:44:00Z',score:{home:0,away:0}}],tickets:[{...ticket,progress:[{fixtureId:'saved',liveCaptured:'2026-09-27T11:44:00Z',score:{home:0,away:0}}]}]};const merged=mergeFreshState(previous,next);assert.equal(merged.fixtures[0].score.away,1);assert.equal(merged.tickets[0].progress[0].score.away,1);mergeLiveState(previous,{liveFixtures:[{...base,liveCaptured:'2026-09-27T11:46:00Z',score:{home:1,away:1}}],liveSelections:[]});assert.equal(previous.fixtures[0].score.home,0);});
test('Live window excludes stale archived live flags and includes current matches across midnight',()=>{const now=Date.parse(capture),window=dateRange('live','Africa/Kampala',new Date(capture)),fixtures=[base,{...base,id:'stale',liveCaptured:'2026-09-26T20:00:00Z'},{...base,id:'old',kickoff:'2026-09-26T20:00:00Z'},{...base,id:'done',status:'finished'}];assert.deepEqual(filterFixtureWindow(fixtures,'live',window,dayKey,now).map(f=>f.id),['saved']);assert.equal(isCurrentLive(base,now),true);assert.equal(isCurrentLive(fixtures[1],now),false);});
test('unfinished saved tickets add their own UTC result dates independent of the board date',()=>{const f={...base,kickoff:'2026-09-26T22:30:00Z'},tickets=[{status:'pending',legs:[{fixtureId:'saved'}]}];assert.deepEqual(trackedFixtureDays([f],tickets,Date.parse('2026-09-27T11:45:00Z')),['2026-09-26']);assert.deepEqual(trackedFixtureDays([f],[{status:'won',legs:[{fixtureId:'saved'}]}],Date.parse('2026-09-27T11:45:00Z')),[]);});

test('tracked bookmaker scores remain visible when the global live feed stops listing a saved match',()=>{const event={id:'1',category:{id:'2'},participants:[{name:'Home',position:1},{name:'Away',position:2}],startTime:'2026-09-26T17:30:00Z',additionalInfo:{},results:{participantPeriodResults:[{participant:{type:'HOME'},periodResults:[{period:{slug:'FULL_TIME_EXCLUDING_OVERTIME'},type:'SCORE',result:'1'}]},{participant:{type:'AWAY'},periodResults:[{period:{slug:'FULL_TIME_EXCLUDING_OVERTIME'},type:'SCORE',result:'2'}]}]}};const f=parsePawaTracked(event,capture,'public');assert.deepEqual(f.score,{home:1,away:2});assert.equal(f.status,'awaiting-result');assert.equal(f.liveClock,'Awaiting FT');assert.deepEqual(f.quotes,[]);assert.equal(parsePawaTracked({...event,status:'FINISHED'},capture,'public').status,'finished');assert.equal(parsePawaTracked({...event,results:{}},capture,'public'),null);});

test('a transport or response body that ignores abort cannot stall live checks',async()=>{await assert.rejects(readPublicResponse('public',{timeoutMs:20},()=>new Promise(()=>{})),/deadline/);await assert.rejects(readPublicResponse('public',{timeoutMs:20},async()=>({ok:true,json:()=>new Promise(()=>{})})),/deadline/);});
test('source statuses retain one entry per source during repeated stream updates',()=>{const previous={fixtures:[],tickets:[],sources:[{name:'details',status:'cached'}],eligibleSelections:[],picks:[],allPicks:[]};const next=mergeLiveState(previous,{sources:[{name:'details',status:'connected'},{name:'details',status:'connected'}],liveFixtures:[]});assert.equal(next.sources.length,1);assert.equal(next.sources[0].status,'connected');});

test('confirmed FT overrides a newer fetch timestamp on stale live progress',()=>{const live={...base,liveCaptured:'2026-09-27T12:30:00Z'},finished={...base,status:'finished',liveClock:'FT',liveCaptured:'2026-09-27T12:29:00Z'};assert.equal(newerLive(live,finished).status,'finished');const previous={fixtures:[],tickets:[{id:'t',progress:[{fixtureId:'saved',fixtureStatus:'live',liveCaptured:live.liveCaptured}]}],sources:[],eligibleSelections:[],picks:[],allPicks:[]};const next=mergeLiveState(previous,{tickets:[{id:'t',progress:[{fixtureId:'saved',fixtureStatus:'finished',liveCaptured:finished.liveCaptured}]}],liveFixtures:[]});assert.equal(next.tickets[0].progress[0].fixtureStatus,'finished');});

test('verified international friendly league aliases join price and scorer sources',()=>{const pawa={...base,id:'pawa',league:'Int. Friendly Games',leagueId:'web:international:int. friendly games',externalIds:{betpawa:'123'},quotes:[{market:'1X2',selection:'away',odds:1.4}]},ls={...base,externalIds:{livescore:base.externalIds.livescore},goalScorers:[{name:'Scorer'}]};const f=applyLiveUpdates([pawa],[ls]);assert.equal(f.length,1);assert.equal(f[0].quotes.length,1);assert.equal(f[0].goalScorers[0].name,'Scorer');assert.equal(f[0].externalIds.livescore,base.externalIds.livescore);assert.equal(f[0].externalIds.betpawa,'123');assert.equal(applyLiveUpdates([{...pawa,league:'Club Friendlies'}],[ls]).length,2);});

test('a complete Live snapshot removes ended and duplicate cards immediately',()=>{const now=new Date().toISOString(),kickoff=new Date(Date.now()-600000).toISOString(),original={...base,kickoff,liveCaptured:now},alias={...original,id:'alias'},previous={fixtures:[original,alias],tickets:[],sources:[],eligibleSelections:[],picks:[],allPicks:[]};const next=mergeLiveState(previous,{range:{liveOnly:true},liveFixtures:[original],liveSelections:[]});assert.deepEqual(next.fixtures.map(f=>f.id),['saved']);assert.equal(mergeLiveState(next,{range:{liveOnly:true},liveFixtures:[],liveSelections:[]}).fixtures.length,0);});

test('China PR alias joins verified sources and fresh LiveScore clocks take priority over delayed bookmaker clocks',()=>{const now=new Date().toISOString(),ls={...base,liveSource:'LiveScore',liveCaptured:now,liveClock:"56'"},pawa={...base,id:'pawa',home:'China PR',league:'Int. Friendly Games',leagueId:'other',externalIds:{betpawa:'123'},liveSource:'BetPawa Uganda',liveCaptured:new Date(Date.now()+1).toISOString(),liveClock:"50'",quotes:[{market:'1X2',selection:'away',odds:1.06}]};const fs=applyLiveUpdates([ls],[pawa]);assert.equal(fs.length,1);assert.equal(fs[0].liveClock,"56'");assert.equal(fs[0].liveSource,'LiveScore');assert.equal(fs[0].quotes[0].odds,1.06);assert.equal(fs[0].externalIds.betpawa,'123');});
