import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {build} from 'esbuild';
import {analyzeFixture} from '../lib/match-analysis.mjs';
import {historicalKey,validHistoricalResult} from '../lib/historical-archive.mjs';

const now=Date.now(),kickoff=new Date(now+3*3600000).toISOString(),captured=new Date(now).toISOString();
const fixture={id:'match-1',home:'Arsenal',away:'Chelsea',league:'Premier League',leagueId:'epl',kickoff,status:'scheduled',quotes:[{market:'DOUBLE_CHANCE',selection:'1X',line:null,period:'FT',odds:1.7,bookmaker:'Example',captured}],arataModel:{available:true,created:captured,expectedGoals:{home:2.2,away:.7},probabilities:{home:.7,draw:.2,away:.1},markets:[],evidence:{stale:false,leagueMatches:350,homeMatches:36,awayMatches:36,homeForm:[],awayForm:[],h2h:[],sources:['Football-Data.co.uk'],learning:{status:'validated-active'}}}};

test('Match Lab distinguishes likely scores, risk bands and a genuinely fresh value quote',()=>{
 const report=analyzeFixture(fixture,now);assert.equal(report.scorelines.length,5);assert.ok(report.scorelines[0].probability>report.scorelines[1].probability);assert.equal(report.tiers.length,3);assert.equal(report.decision,'consider');assert.ok(report.tiers.some(t=>t.actionable&&t.option.odds===1.7));
 const expired=analyzeFixture({...fixture,quotes:fixture.quotes.map(q=>({...q,captured:new Date(now-5*60000).toISOString()}))},now);assert.equal(expired.decision,'avoid');assert.ok(expired.tiers.every(t=>!t.actionable));assert.ok(expired.options.every(o=>o.odds===null));
 const finished=analyzeFixture({...fixture,status:'finished'},now);assert.equal(finished.decision,'avoid');
 const unsupported=analyzeFixture({...fixture,arataModel:{available:false,reason:'Not enough results.'}},now);assert.deepEqual(unsupported.scorelines,[]);assert.match(unsupported.decisionReason,/Not enough results/);
});

test('portable archive merges sports records, remaps ticket owner and rejects unverified history',async()=>{
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('backend/postgres.sql','utf8'));sqlite.exec('PRAGMA foreign_keys=ON');
 sqlite.prepare('INSERT INTO auth_users(id,username,email,first_name,last_name,phone,role,active,must_change_password,salt,password_hash,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('new-admin','admin','admin@example.test','Admin','User','','admin',1,0,'salt','hash',captured,captured);
 globalThis.__ARATA_DB={prepare(sql){return {sql,params:[],bind(...params){this.params=params;return this;},async all(){return {results:sqlite.prepare(sql).all(...this.params)};},async first(){return sqlite.prepare(sql).get(...this.params)||null;},async run(){sqlite.prepare(sql).run(...this.params);return {success:true};}};},async batch(commands){sqlite.exec('BEGIN');try{for(const command of commands)await command.run();sqlite.exec('COMMIT');return [];}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
 try{const bundle=await build({entryPoints:['lib/backup.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env={DB:globalThis.__ARATA_DB};',loader:'js'}));}}]});const {importBackupBatch,exportBackupPage,seedHistoricalArchive}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
  await importBackupBatch('fixtures',[{id:fixture.id,kickoff,payload:JSON.stringify({...fixture,quotes:[]}),updated:captured}],'new-admin');
  const p={id:'pred-1',fixtureId:fixture.id,kickoff,created:captured,predictor:'arata',market:'1X2',selection:'home',outcome:'pending'};await importBackupBatch('predictions',[{id:p.id,fixture_id:fixture.id,created:captured,outcome:'pending',payload:JSON.stringify(p)}],'new-admin');
  const ticket={id:'ticket-1',created:captured,status:'pending',userId:'old-owner',legs:[p]};const row={id:ticket.id,created:captured,status:'pending',payload:JSON.stringify(ticket),owner_email:'missing@example.test'};await importBackupBatch('tickets',[row],'new-admin');await importBackupBatch('tickets',[row],'new-admin');
  assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM tickets').get().n,1);assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM tickets').get().payload).userId,'new-admin');assert.equal((await exportBackupPage('tickets')).rows[0].owner_email,'admin@example.test');assert.equal(sqlite.prepare('SELECT prediction_id FROM prediction_heads').get().prediction_id,p.id);
  const day=new Date(now-7*86400000).toISOString().slice(0,10),historical={leagueId:'epl',home:'Arsenal',away:'Chelsea',kickoff:day+'T12:00:00Z',availableAt:day+'T23:59:59Z',status:'finished',score:{home:2,away:1},source:'Football-Data.co.uk',sourceUrl:'https://www.football-data.co.uk/mmz4281/2526/E0.csv'};
  assert.equal(validHistoricalResult(historical),true);await importBackupBatch('historical_results',[{id:historicalKey(historical),league_id:'epl',kickoff:historical.kickoff,source:historical.source,payload:JSON.stringify(historical)}],'new-admin');assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM historical_results').get().n,1);
  await assert.rejects(()=>importBackupBatch('historical_results',[{id:'fake',league_id:'epl',kickoff:historical.kickoff,source:historical.source,payload:JSON.stringify({...historical,score:{home:99,away:0}})}],'new-admin'),/invalid record/);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM historical_results').get().n,1);
  const csvDay=new Date(now-8*86400000),csvDate=[String(csvDay.getUTCDate()).padStart(2,'0'),String(csvDay.getUTCMonth()+1).padStart(2,'0'),csvDay.getUTCFullYear()].join('/');sqlite.prepare('INSERT INTO api_cache(key,expires,payload) VALUES(?,?,?)').run('https://www.football-data.co.uk/mmz4281/2526/E0.csv',now+86400000,JSON.stringify({data:`Date,HomeTeam,AwayTeam,FTHG,FTAG\n${csvDate},Aston Villa,Liverpool,1,0\n`}));assert.ok((await seedHistoricalArchive('epl')).archived>=1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM historical_results').get().n,2);
  await assert.rejects(()=>exportBackupPage('auth_users'),/Unknown backup section/);
 }finally{delete globalThis.__ARATA_DB;sqlite.close();}
});

test('analyzer is available to signed-in users while backup stays administrator-only',async()=>{
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('backend/postgres.sql','utf8'));sqlite.exec('PRAGMA foreign_keys=ON');
 globalThis.__ARATA_DB={prepare(sql){return {sql,params:[],bind(...params){this.params=params;return this;},async all(){return {results:sqlite.prepare(sql).all(...this.params)};},async first(){return sqlite.prepare(sql).get(...this.params)||null;},async run(){sqlite.prepare(sql).run(...this.params);return {success:true};}};},async batch(commands){sqlite.exec('BEGIN');try{for(const command of commands)await command.run();sqlite.exec('COMMIT');return [];}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
 try{const bundle=await build({entryPoints:['lib/service.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:"export const env={DB:globalThis.__ARATA_DB,ARATA_ADMIN_INITIAL_PASSWORD:'TestAdmin@123',ARATA_ADMIN_EMAIL:'admin@example.test'};",loader:'js'}));}}]});const {handle}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
  sqlite.prepare('INSERT INTO fixtures VALUES(?,?,?,?)').run(fixture.id,fixture.kickoff,JSON.stringify(fixture),captured);
  const origin='http://localhost',post=(path,body,cookie)=>handle(new Request(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(body)})),get=(path,cookie)=>handle(new Request(origin+path,{headers:cookie?{Cookie:cookie}:{}}));
  assert.equal((await get('/api/admin/backup?table=fixtures')).status,401);
  let login=await post('/api/auth/login',{identity:'admin@example.test',password:'TestAdmin@123'}),cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await post('/api/auth/password',{currentPassword:'TestAdmin@123',newPassword:'VerifiedAdmin@123456'},cookie)).status,200);login=await post('/api/auth/login',{identity:'admin@example.test',password:'VerifiedAdmin@123456'});cookie=login.headers.get('set-cookie').split(';')[0];
  const report=await get('/api/match/analyze?id='+fixture.id,cookie);assert.equal(report.status,200);assert.equal((await report.json()).scorelines.length,5);const backup=await get('/api/admin/backup?table=fixtures',cookie);assert.equal(backup.status,200);assert.equal((await backup.json()).rows.length,1);
  const created=await post('/api/admin/users',{firstName:'Sample',lastName:'Reader',email:'reader@example.test',phone:'0700000000'},cookie);assert.equal(created.status,201);const temporary=(await created.json()).temporaryPassword;let member=await post('/api/auth/login',{identity:'reader@example.test',password:temporary}),memberCookie=member.headers.get('set-cookie').split(';')[0];assert.equal((await post('/api/auth/password',{currentPassword:temporary,newPassword:'ReaderPassword@123456'},memberCookie)).status,200);member=await post('/api/auth/login',{identity:'reader@example.test',password:'ReaderPassword@123456'});memberCookie=member.headers.get('set-cookie').split(';')[0];assert.equal((await get('/api/admin/backup?table=fixtures',memberCookie)).status,403);assert.equal((await get('/api/match/analyze?id='+fixture.id,memberCookie)).status,200);
 }finally{delete globalThis.__ARATA_DB;sqlite.close();}
});
