import test from 'node:test';
import assert from 'node:assert/strict';
import {parseEventMatch,parseOfficialAvailability,matchingResearch} from '../lib/squad-data.mjs';
import {ridgeFit,ridgePredict,fitImpact,squadAdjustment,enhanceForecast} from '../lib/player-impact.mjs';
const now=Date.parse('2026-09-27T12:00:00Z');
const xi=Array.from({length:11},(_,n)=>({id:n+1,name:'Player '+n}));
function page(kickoff='2026-09-20T12:00:00Z'){return {general:{matchId:'1',matchTimeUTCDate:kickoff,finished:true,started:true,leagueId:130,homeTeam:{id:1,name:'Home'},awayTeam:{id:2,name:'Away'}},header:{status:{reason:{short:'FT'},scoreStr:'2 - 1'}},content:{lineup:{lineupType:'standard',homeTeam:{starters:xi},awayTeam:{starters:xi.map(p=>({...p,id:p.id+20}))}},shotmap:{shots:[{id:1,teamId:1,playerId:1,expectedGoals:.7,period:'FirstHalf'},{id:2,teamId:2,playerId:21,expectedGoals:.3,period:'SecondHalf'},{id:3,teamId:1,expectedGoals:.9,period:'PenaltyShootout'}]}}};}
test('match identity and event timing are enforced',()=>{assert.throws(()=>parseEventMatch(page(),'2','mls',new Date(now).toISOString()),/identity/);assert.throws(()=>parseEventMatch(page('2026-09-27T14:00:00Z'),'1','mls',new Date(now).toISOString()),/timing/);assert.throws(()=>parseEventMatch(page('2026-09-27T11:00:00Z'),'1','mls',new Date(now).toISOString()),/timing/);});
test('regulation xG excludes shootouts and rejects missing measurements',()=>{const p=page(),m=parseEventMatch(p,'1','mls',new Date(now).toISOString());assert.equal(m.lineup.status,'historical-confirmed');assert.deepEqual(m.xg,{home:.7,away:.3,events:2});delete p.content.shotmap.shots[0].expectedGoals;assert.equal(parseEventMatch(p,'1','mls',new Date(now).toISOString()).xg,null);});
test('predicted or early-announced XIs never become confirmed',()=>{const p=page('2026-09-28T12:00:00Z');p.general.finished=false;p.general.started=false;p.content.lineup.lineupType='predicted';assert.equal(parseEventMatch(p,'1','mls',new Date(now).toISOString()).lineup.status,'unknown');p.content.lineup.lineupType='standard';assert.equal(parseEventMatch(p,'1','mls',new Date(now).toISOString()).lineup.status,'unknown');p.general.matchTimeUTCDate='2026-09-27T13:00:00Z';assert.equal(parseEventMatch(p,'1','mls',new Date(now).toISOString()).lineup.status,'provider-confirmed');});
test('duplicate starters invalidate confirmation',()=>{const p=page();p.content.lineup.homeTeam.starters[1]=p.content.lineup.homeTeam.starters[0];assert.equal(parseEventMatch(p,'1','mls',new Date(now).toISOString()).lineup.status,'unknown');});
test('exact event joins cannot confuse adjacent team fixtures',()=>{assert.equal(matchingResearch({home:'Home',away:'Away',kickoff:'2026-09-27T12:00:00Z'},{matches:[{home:'Home',away:'Away',kickoff:'2026-09-26T12:00:00Z'}]}),undefined);});
test('ridge identifies a controlled player association, not constant starters',()=>{const rows=Array.from({length:80},(_,n)=>({features:{p:n%2,constant:1,rest:(n%5-2)/2},target:.3*(n%2-.5)+.15*((n%5-2)/2)}));const f=ridgeFit(rows,2);assert(f.beta.p>.15&&f.beta.p<=.2);assert(f.beta.rest>.1);assert.equal(f.beta.constant,undefined);assert(ridgePredict(f,{p:1,rest:1})<=.2);});
test('chronological holdout disables a relationship that reverses later',()=>{const samples=Array.from({length:48},(_,n)=>({kickoff:new Date(Date.UTC(2026,0,n+1)).toISOString(),features:{p:n%2},target:(n<36?1:-1)*.4*(n%2-.5)}));assert.equal(fitImpact(samples).enabled,false);assert.equal(fitImpact(samples.slice(0,20)).enabled,false);});
test('learned effect activates only after later-match evidence',()=>{const samples=Array.from({length:64},(_,n)=>({kickoff:new Date(Date.UTC(2026,0,n+1)).toISOString(),features:{p:n%2},target:.4*(n%2-.5)}));const fit=fitImpact(samples);assert(fit.enabled);assert(fit.validation.holdout>=8);assert(fit.validation.improvement>=.05);});
function trained(){return {through:'2026-09-20T15:00:00Z',observations:[],players:{p:{name:'Important Player'}},xg:{enabled:false},teams:{home:{latest:new Date().toISOString(),matches:40,attack:{enabled:true,n:40,fit:{beta:{p:.2},means:{p:.8}},validation:{}},defence:{enabled:false}}}};}
test('unverified or questionable absences have no player effect',()=>{const m=trained(),s={players:[{id:'p',name:'Important Player'}]};for(const absence of [{name:'Important Player',status:'questionable',verified:true},{name:'Important Player',status:'out',verified:false}])assert.equal(squadAdjustment('Home',m,null,s,[absence],5).attack,0);const out=squadAdjustment('Home',m,null,s,[{name:'Important Player',status:'out',verified:true}],5);assert(Math.abs(out.attack+.16)<1e-12);assert.equal(out.changes.length,1);});
test('lineup conflicting with confirmed absence withholds correction',()=>{const starters=Array.from({length:11},(_,n)=>({id:n===0?'p':String(n),name:n===0?'Important Player':'P'+n}));assert.equal(squadAdjustment('Home',trained(),starters,null,[{name:'Important Player',status:'out',verified:true}],5).attack,0);});
test('training after forecast cutoff cannot affect probabilities',()=>{const t=trained();t.through='2026-09-27T13:00:00Z';const base={available:true,expectedGoals:{home:1,away:1},evidence:{homeRestDays:5,awayRestDays:5}};const r=enhanceForecast(base,{home:'Home',away:'Away',kickoff:'2026-09-27T14:00:00Z'},{trained:t},now);assert.equal(r.evidence.status,'rejected');assert.deepEqual(r.expectedGoals,base.expectedGoals);});
test('undated official reports cannot authorize injury corrections',()=>assert.throws(()=>parseOfficialAvailability('<article><h3>Home</h3></article>','https://www.mlssoccer.com/news/report',new Date(now).toISOString()),/publication/));
