"use client";
import {useEffect,useMemo,useState} from 'react';
import {Search,UserPlus,Users,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {readApiJson,apiErrorMessage} from '@/lib/api-client.mjs';
import type {AppUser} from './AccountAccess';
import BackupPanel from './BackupPanel';
import SupportSettings from './SupportSettings';

async function api(path:string,method='GET',body?:any){return readApiJson(await fetch('/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}));}

export default function AdminDashboard({current}:{current:AppUser}){
 const [users,setUsers]=useState<AppUser[]>([]),[query,setQuery]=useState(''),[addOpen,setAddOpen]=useState(false),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<any>(null),[confirmDelete,setConfirmDelete]=useState<string|null>(null);
 async function reload(){try{setUsers((await api('admin/users')).users);}catch(e){setError(apiErrorMessage(e));}}
 useEffect(()=>{void reload();},[]);
 const filtered=useMemo(()=>{const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return users.filter(u=>terms.every(term=>[u.firstName,u.lastName,u.username,u.email,u.phone,u.role].join(' ').toLowerCase().includes(term)));},[users,query]);
 async function run(operation:()=>Promise<any>,done:(result:any)=>string){setBusy(true);setError('');setMessage('');try{const result=await operation();setMessage(done(result));await reload();setEditing(null);setConfirmDelete(null);return true;}catch(e){setError(apiErrorMessage(e));return false;}finally{setBusy(false);}}
 async function create(e:React.FormEvent){e.preventDefault();const saved=await run(()=>api('admin/users','POST',{firstName,lastName,email,phone}),r=>`${r.user.firstName} can sign in with ${r.user.email}. Temporary password: ${r.temporaryPassword}. Ask them to change it at first login.`);if(saved){setFirstName('');setLastName('');setEmail('');setPhone('');setAddOpen(false);}}
 return <div className="account-management"><div className="section-heading admin-heading"><div><h2>Admin settings</h2><p className="muted">Manage support contacts, people and portable football research.</p></div><button className="primary" onClick={()=>{setError('');setAddOpen(true);}}><UserPlus size={17}/>Add user</button></div>
  {message&&<p className="notice" role="status">{message}</p>}{error&&!addOpen&&<p className="notice error" role="alert">{error}</p>}
  <SupportSettings/>
  <div className="section-heading"><div><h3>User management</h3><p className="small muted">Search accounts and manage access.</p></div></div>
  <div className="admin-user-search"><Search size={18}/><input aria-label="Search users" placeholder="Search name, email, login or phone" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} of {users.length}</span></div>
  <div className="user-list">{filtered.length?filtered.map(u=><article className="panel-card user-card" key={u.id}><div className="section-heading"><div><h3>{u.firstName} {u.lastName}</h3><p className="small muted">{u.email} · {u.phone||'No phone'} · {u.role}</p></div><span className={'leg-outcome '+(u.active?'won':'lost')}>{u.active?'Active':'Inactive'}</span></div>{editing===u.id?<form className="account-form" onSubmit={e=>{e.preventDefault();void run(()=>api('admin/users/'+u.id,'PATCH',draft),()=>`${u.firstName}'s account was updated.`);}}><div className="account-fields"><label>First name<input value={draft.firstName} onChange={e=>setDraft({...draft,firstName:e.target.value})}/></label><label>Last name<input value={draft.lastName} onChange={e=>setDraft({...draft,lastName:e.target.value})}/></label></div><div className="account-fields"><label>Login name<input value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>Email<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Phone<input type="tel" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label></div><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="user">User</option><option value="admin">Administrator</option></select></label><div className="user-actions"><button className="primary" disabled={busy}>Save changes</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form>:<div className="user-actions"><button className="secondary" onClick={()=>{setEditing(u.id);setDraft({...u});}}>Edit</button><button className="secondary" disabled={busy||u.id===current.id} onClick={()=>void run(()=>api('admin/users/'+u.id,'PATCH',{active:!u.active}),()=>`${u.firstName} is now ${u.active?'inactive':'active'}.`)}>{u.active?'Deactivate':'Activate'}</button><button className="text-button" disabled={busy} onClick={()=>void run(()=>api('admin/users/'+u.id+'/reset-password','POST'),r=>`Password reset for ${u.firstName}. Temporary password: ${r.temporaryPassword}.`)}>Reset password</button>{u.id!==current.id&&<button className="text-button danger" disabled={busy} onClick={()=>{if(confirmDelete!==u.id){setConfirmDelete(u.id);return;}void run(()=>api('admin/users/'+u.id,'DELETE'),()=>`${u.firstName}'s access was removed.`);}}>{confirmDelete===u.id?'Confirm remove':'Remove'}</button>}</div>}</article>):<div className="empty compact"><Users size={24}/><h3>No users match this search</h3><p>Try a name, email, login or phone number.</p></div>}</div>
  <BackupPanel/>
  <Dialog open={addOpen} onOpenChange={value=>{if(!busy)setAddOpen(value);}}><DialogContent className="admin-create-modal"><DialogHeader><span className="eyebrow"><ShieldCheck size={15}/> ADMIN ACCESS</span><DialogTitle>Add a user</DialogTitle><DialogDescription>Create access for someone you know. They will change their temporary password on first sign-in.</DialogDescription></DialogHeader><form className="account-form" onSubmit={e=>void create(e)}><div className="account-fields"><label>First name<input autoFocus value={firstName} onChange={e=>setFirstName(e.target.value)} required/></label><label>Last name<input value={lastName} onChange={e=>setLastName(e.target.value)} required/></label></div><div className="account-fields"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} required/></label></div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="admin-modal-actions"><button className="secondary" type="button" onClick={()=>setAddOpen(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create user'}</button></div></form></DialogContent></Dialog>
 </div>;
}
