"use client";
import {useRef,useState} from 'react';
import {Download,Upload,DatabaseZap,ShieldCheck,FileJson,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {readApiJson,apiErrorMessage} from '@/lib/api-client.mjs';

const TABLES=['fixtures','predictions','odds_snapshots','tickets','ticket_legs','ticket_quote_legs','historical_results','api_cache'] as const;
const labels:Record<string,string>={fixtures:'Fixtures and results',predictions:'Forecasts and outcomes',odds_snapshots:'Price snapshots',tickets:'Saved tickets',ticket_legs:'Ticket picks',ticket_quote_legs:'Quoted ticket picks',historical_results:'Verified historical results',api_cache:'Learning and research context'};
type Archive={format:string;version:number;exportedAt:string;sections:Record<string,any[]>};
const request=async(path:string,init?:RequestInit)=>readApiJson(await fetch('/api/'+path,{cache:'no-store',credentials:'same-origin',...init}));

export default function BackupPanel(){
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[open,setOpen]=useState(false),[archive,setArchive]=useState<Archive|null>(null);
 const fileRef=useRef<HTMLInputElement>(null);
 async function download(){setBusy(true);setError('');setNotice('');try{for(const league of ['epl','la-liga','serie-a','ligue-1','bundesliga','mls']){setProgress('Preserving verified '+league+' results');await request('admin/backup/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({league})});}const sections:Record<string,any[]>={};for(const table of TABLES){let after='',pages=0;sections[table]=[];do{const result=await request('admin/backup?table='+table+'&limit=35'+(after?'&after='+encodeURIComponent(after):''));if(result.version!==1||result.table!==table||!Array.isArray(result.rows))throw new Error('Backup response did not match the expected format.');sections[table].push(...result.rows);after=result.next||'';setProgress(`${labels[table]} · ${sections[table].length} records`);if(++pages>10000)throw new Error('Backup page limit reached.');}while(after);}const result:Archive={format:'arata-odds-backup',version:1,exportedAt:new Date().toISOString(),sections};const blob=new Blob([JSON.stringify(result)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Arata-Odds-data-'+new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Kampala'})+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice('Backup downloaded. Store this file privately. Passwords and sessions were excluded.');}catch(e){setError(apiErrorMessage(e));}finally{setBusy(false);setProgress('');}}
 async function selectFile(file?:File){setArchive(null);setError('');setNotice('');if(!file)return;if(file.size>80_000_000){setError('This backup exceeds the 80 MB import limit.');return;}try{const parsed=JSON.parse(await file.text());if(parsed?.format!=='arata-odds-backup'||parsed.version!==1||!parsed.sections||TABLES.some(table=>!Array.isArray(parsed.sections[table]))||Object.keys(parsed.sections).some(key=>!TABLES.includes(key as any)))throw new Error('This is not a supported Arata Odds data backup.');setArchive(parsed);setOpen(true);}catch(e){setError(apiErrorMessage(e));}}
 async function restore(){if(!archive)return;setBusy(true);setError('');setNotice('');let processed=0;try{const encoder=new TextEncoder();for(const table of TABLES){const items=archive.sections[table];let index=0;while(index<items.length){const batch:any[]=[];while(index<items.length&&batch.length<35){const candidate=[...batch,items[index]],body=JSON.stringify({table,rows:candidate});if(encoder.encode(body).length>4_700_000){if(!batch.length)throw new Error(`A ${labels[table]} record exceeds the 4.7 MB per-record import limit.`);break;}batch.push(items[index++]);}await request('admin/backup/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,rows:batch})});processed+=batch.length;setProgress(`${labels[table]} · ${index}/${items.length} · ${processed} restored`);}}await request('admin/backup/finalize',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setOpen(false);setArchive(null);setNotice(`${processed} sports-data records processed. Existing records were kept; learning is being checked against restored verified outcomes.`);}catch(e){setError(`${apiErrorMessage(e)} ${processed} records were processed. Retry the same file to continue safely.`);}finally{setBusy(false);setProgress('');}}
 const count=archive?TABLES.reduce((n,table)=>n+archive.sections[table].length,0):0;
 return <section className="panel-card backup-panel"><div className="section-heading"><div><h3><DatabaseZap size={19}/> Data portability</h3><p className="small muted">Move match history, forecasts, research context and saved tickets to another Arata Odds setup.</p></div></div><div className="backup-actions"><button className="secondary" onClick={()=>void download()} disabled={busy}><Download size={17}/>{busy&&progress?'Preparing…':'Export data'}</button><button className="secondary" onClick={()=>fileRef.current?.click()} disabled={busy}><Upload size={17}/>Import backup</button><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>{void selectFile(e.target.files?.[0]);e.target.value='';}}/></div><p className="small muted"><ShieldCheck size={14}/> Backups contain research and tickets, but no account passwords or sessions. Import merges records and assigns tickets to matching users by email; otherwise they go to the importing admin.</p>{progress&&<p className="backup-progress" role="status"><RefreshCw size={15} className="spin"/>{progress}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="notice error" role="alert">{error}</p>}
  <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="backup-import-modal"><DialogHeader><span className="eyebrow"><FileJson size={15}/> PORTABLE RESEARCH ARCHIVE</span><DialogTitle>Import football data</DialogTitle><DialogDescription>Review the backup before merging it into this installation.</DialogDescription></DialogHeader><div className="backup-import-summary"><strong>{count.toLocaleString()} records</strong><small>Exported {archive?.exportedAt?new Date(archive.exportedAt).toLocaleString('en-GB',{timeZone:'Africa/Kampala'})+' EAT':'—'}</small></div><div className="backup-counts">{archive&&TABLES.map(table=><div key={table}><span>{labels[table]}</span><b>{archive.sections[table].length.toLocaleString()}</b></div>)}</div><p className="small muted">Existing records stay in place. Imported verified results can satisfy the model's normal historical coverage requirements. Learning is rechecked after import; no training threshold is bypassed.</p>{error&&<p className="notice error" role="alert">{error}</p>}{progress&&<p className="backup-progress" role="status"><RefreshCw size={15} className="spin"/>{progress}</p>}<div className="backup-modal-actions"><button className="secondary" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="primary" onClick={()=>void restore()} disabled={busy}>{busy?'Importing…':'Import and merge'}</button></div></DialogContent></Dialog>
 </section>;
}
