"use client";
import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
const labels:Record<string,string>={venue:'Venue weight',form:'Recent form weight',h2h:'H2H weight',attack:'Attack strength',defence:'Defence strength',homeScale:'Home goal scale',awayScale:'Away goal scale'};
const scopeName=(scope:string)=>scope.replace('*','All covered leagues').replace('|',' · ');
const eat=(date:string)=>new Date(date).toLocaleString('en-GB',{timeZone:'Africa/Kampala',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+' EAT';
export default function LearningPanel(){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let disposed=false,controller:AbortController|null=null;async function load(){if(document.hidden||controller)return;controller=new AbortController();const deadline=setTimeout(()=>controller?.abort(),20000);try{const response=await fetch('/api/models/learning',{signal:controller.signal,cache:'no-store'}),value:any=await response.json();if(!response.ok)throw new Error(value.error||'Learning report unavailable.');if(!disposed){setData(value);setError('');}}catch(e){if(!disposed)setError((e as Error).message);}finally{clearTimeout(deadline);controller=null;}}void load();const interval=setInterval(()=>void load(),15000),resume=()=>void load();document.addEventListener('visibilitychange',resume);return()=>{disposed=true;clearInterval(interval);controller?.abort();document.removeEventListener('visibilitychange',resume);};},[]);
 const active=data?.active,runs=data?.runs||[],last=runs.at(-1),bins=(data?.reliability||[]).filter((b:any)=>b.n),curveData=Object.entries(active?.calibrators||{}).map(([scope,model]:any)=>({scope,model}));
 return <section className="learning-panel" aria-label="Arata self-learning"><div className="section-heading"><div><h2>Learning from its own mistakes</h2><p className="muted">Verified results teach Arata. Later matches decide whether a change is used.</p></div><span className={'badge '+(active?'value':'')}>{active?'VALIDATED UPDATE ACTIVE':data?.running?'CHECKING RESULTS':'COLLECTING EVIDENCE'}</span></div>{error&&<p className="notice error" role="status">{error}</p>}<p className="notice">{data?.message||'Loading the learning report…'} {data?.running?'A background learning check is running.':''}</p><div className="model-score-grid"><div className="model-score"><span>Verified learning matches</span><strong>{data?.eligibleMatches??'—'}</strong><small>Distinct matches, not price snapshots · minimum {data?.rules?.minimumMatches||200}</small></div><div className="model-score"><span>Core training matches</span><strong>{data?.coreMatches??'—'}</strong><small>Settled forecasts with their original goal inputs</small></div><div className="model-score"><span>Active corrections</span><strong>{curveData.length}</strong><small>League and market profiles · {Object.keys(active?.cores||{}).length} learned core profiles</small></div></div><p className="small muted">{data?.checkedAt?'Last learning check '+eat(data.checkedAt):'Checks run automatically as results settle and research refreshes.'}{active?' · Active since '+eat(active.activatedAt)+' · '+active.revision:''}</p>{data?.drift&&<p className="small muted">Prospective monitoring: {data.drift.matches} new matches · {data.drift.status}. An update can be rolled back when later results show worse errors.</p>}
 <div className="chart-panel"><h3>Probability versus observed results</h3><p className="small muted">One representative event per match: home win when logged, otherwise the first available market. Each probability range shows its sample count; sparse ranges are uncertain.</p>{bins.length?<><ResponsiveContainer width="100%" height={230}><LineChart data={bins}><CartesianGrid stroke="#26354a" strokeDasharray="3 3"/><XAxis dataKey="range" tick={{fill:'#94a2b6',fontSize:10}}/><YAxis domain={[0,1]} tickFormatter={v=>Math.round(v*100)+'%'} tick={{fill:'#94a2b6',fontSize:11}}/><Tooltip contentStyle={{background:'#111c2c',borderColor:'#31455b'}} formatter={(v:any,name:any)=>[typeof v==='number'?(v*100).toFixed(1)+'%':v,name]}/><Legend wrapperStyle={{fontSize:11}}/><Line dataKey="raw" name="Before calibration" stroke="#72aaff" dot={false}/><Line dataKey="probability" name="Issued forecast" stroke="#00e5a0" dot={false}/><Line dataKey="observed" name="Observed frequency" stroke="#ffbd69" dot={false}/></LineChart></ResponsiveContainer><p className="small muted">{bins.map((b:any)=>`${b.range}: ${b.n} ${b.n===1?'match':'matches'}`).join(' · ')}</p></>:<div className="empty compact">The chart appears after verified logged forecasts settle.</div>}</div>
 <details className="reason"><summary>Active forecasting weights and calibration rules</summary>{active?<><p className="small muted">Only validated profiles apply. Sparse leagues use a validated general profile or the starting defaults. Saved predictions and ticket prices remain locked.</p>{Object.entries(active.cores||{}).map(([scope,c]:any)=><div className="fixture-card" key={scope}><h4>{scopeName(scope)}</h4><div className="learning-weights">{Object.entries(c.weights).map(([key,v]:any)=><div key={key}><small>{labels[key]||key}</small><b>{v.toFixed(3)}</b></div>)}</div><small>Later-match goal error gain: {c.validation?.gain?.toFixed(3)||'—'}</small></div>)}{curveData.map(({scope,model}:any)=><p className="small muted" key={scope}><b>{scopeName(scope)}</b> · {model.kind==='multiclass'?'Normalized three-outcome calibration':'Probability-range calibration'} · {model.validation?.n} validation matches · Brier error improvement {model.validation?.gain?.toFixed(3)}</p>)}</>:<p>No learned profile has passed activation yet. Starting weights remain in use until enough verified evidence supports a change.</p>}</details>
 <details className="reason"><summary>Learning decisions ({runs.length})</summary>{runs.length?runs.slice().reverse().map((run:any)=><article className="fixture-card" key={run.id}><h4>{run.status==='activated'?'Update activated':run.status==='rolled-back'?'Update rolled back':'Candidate rejected'}</h4><p className="small muted">{eat(run.at)} · {run.id}</p>{run.split&&<><p className="small muted">{run.train} training · {run.calibration} calibration · {run.test} later validation matches</p><p className="small muted">Validation from {eat(run.split.testFrom)} to {eat(run.split.testThrough)} · Brier {run.validation.before.toFixed(3)} → {run.validation.after.toFixed(3)} · Log loss {run.logLoss.before.toFixed(3)} → {run.logLoss.after.toFixed(3)}</p><details className="reason"><summary>Decisions by league and market</summary>{run.checks.map((check:any,i:number)=><p className="small muted" key={i}>{check.kind==='core'?'Core weights':'Calibration'} · {scopeName(check.scope)} · {check.status} · {check.train} fitting / {check.test} validation matches{check.validation?' · error gain '+check.validation.gain.toFixed(3):''}</p>)}</details></>}<p className="small muted">{run.note}</p></article>):<p>No candidate has enough data for a complete validation window yet.</p>}</details>
 <details className="reason"><summary>How automatic learning stays accountable</summary><p className="small muted">Arata uses forecasts logged before kickoff, paired with explicit supported final results. Owner-entered outcomes, stale models and forecasts made after kickoff cannot train it. The goal inputs are frozen at forecast time. Core fitting uses an earlier block, calibration a separate later block, and activation a final block of unseen matches. Markets from the same match stay together and price recaptures add no extra votes.</p><p className="small muted">New weights must improve later-match goal error. Calibration and the whole proposed workflow must improve Brier error and log loss under conservative paired checks. Failed candidates leave the current model intact. Consumed validation windows cannot be reused for another activation attempt. The learned model stays provisional; validation does not guarantee future accuracy or profit.</p></details></section>;
}
