"use client";
import {useEffect,useState} from 'react';
import {normalizeMatchStatus} from '@/lib/live.mjs';
export default function MatchStatus({fixture}:{fixture:any}){
 const [now,setNow]=useState(Date.now());useEffect(()=>{if(fixture.status!=='live')return;const timer=setInterval(()=>setNow(Date.now()),2000);return()=>clearInterval(timer);},[fixture.status]);
 const f=normalizeMatchStatus(fixture,now),age=f.liveCaptured?Math.max(0,Math.floor((now-Date.parse(f.liveCaptured))/1000)):null,delayed=f.liveStale||(f.status==='live'&&(age===null||age>15));
 const phase=f.status==='finished'?'Full time':f.livePeriod==='FIRST_HALF'?'First half':f.livePeriod==='SECOND_HALF'?'Second half':f.liveClock==='HT'?'Half time':null;
 const goals=f.goalScorers||[],eventsDelayed=f.eventsScore&&f.score&&(f.eventsScore.home!==f.score.home||f.eventsScore.away!==f.score.away),stamp=f.status==='finished'?f.endedAt||f.finalConfirmedAt||f.liveCaptured:f.liveCaptured;
 return <div className="live-match-detail"><div className="match-status" aria-live="polite">{f.status==='live'&&<span className="live-bubble"><i/> LIVE</span>}{(['live','finished','awaiting-result'].includes(f.status))&&<><strong className="match-score">{f.score?`${f.score.home} – ${f.score.away}`:'Score unavailable'}</strong><span className="badge">{f.status==='finished'?'FT':f.status==='awaiting-result'?'Awaiting confirmed FT':f.liveClock||'Live'}</span></>}{stamp&&<small className={delayed?'stale-score':'muted'}>{f.status==='finished'?(f.endedAt?'Ended · ':'Final confirmed · '):delayed?'Delayed · ':''}{f.liveSource||f.resultSource} · {new Date(stamp).toLocaleString('en-GB',{timeZone:'Africa/Kampala',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'})} EAT{f.status==='live'&&age!==null?` · ${age}s ago`:''}</small>}</div>
 {f.status==='awaiting-result'&&<p className="small muted">Last published score. Final result confirmation is pending; this match is no longer presented as live.</p>}
 {(phase||f.halfTimeScore)&&<p className="small muted match-time-stats">{phase}{f.halfTimeScore?`${phase?' · ':''}HT ${f.halfTimeScore.home}–${f.halfTimeScore.away}`:''}</p>}
 {['live','finished','awaiting-result'].includes(f.status)&&<details className="reason scorer-details"><summary>Goal scorers & match events ({goals.length||'—'})</summary>{goals.length>0?<ul className="goal-events" aria-label="Goal scorers and minutes">{goals.map((g:any)=><li key={g.id}><strong>{g.time}</strong> {g.name} <span className="muted">· {g.team==='home'?f.home:f.away}{g.kind==='own-goal'?' · own goal':g.kind==='penalty'?' · penalty':''}{g.assist?` · assist ${g.assist}`:''}</span></li>)}</ul>:<p className="small muted">{f.score&&f.score.home+f.score.away===0&&f.detailsCoverage==='available'?'No goals recorded.':'Named scorer events are unavailable from the published feed for this match.'}</p>}{!eventsDelayed&&f.score&&goals.length>0&&goals.length<f.score.home+f.score.away&&<p className="small muted">Some scorer events are not published.</p>}{eventsDelayed&&<p className="small muted">Scorer details are catching up with the score.</p>}{f.eventsCaptured&&<p className="small muted">Events: {f.eventsSource} · {new Date(f.eventsCaptured).toLocaleString('en-GB',{timeZone:'Africa/Kampala'})} EAT</p>}</details>}</div>;
}
