"use client";
import {useEffect,useMemo,useState} from 'react';
import {Search,ScanSearch,Sparkles,RefreshCw,ArrowRight,ShieldCheck,TriangleAlert,Goal,Clock3,ExternalLink} from 'lucide-react';
import DateWindow from './DateWindow';
import ModelEvidence from './ModelEvidence';
import {marketLabel} from '@/lib/markets.mjs';
import {readApiJson,apiErrorMessage} from '@/lib/api-client.mjs';
import {searchMatches} from '@/lib/live.mjs';

const pct=(value:number)=>(value*100).toFixed(1)+'%';
const eat=(date:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Kampala',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(date))+' EAT';

export default function MatchAnalyzer({fixtures,range,onRangeChange}:{fixtures:any[];range:string;onRangeChange:(range:string)=>void}){
 const [query,setQuery]=useState(''),[online,setOnline]=useState<any[]>([]),[selected,setSelected]=useState(''),[report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[searchBusy,setSearchBusy]=useState(false),[error,setError]=useState(''),[searchNote,setSearchNote]=useState('');
 const matches=useMemo(()=>{const dedup=new Map([...fixtures,...online].map(f=>[f.id,f]));return searchMatches([...dedup.values()].filter(f=>f.status==='scheduled'&&Date.parse(f.kickoff)>Date.now()),query).sort((a:any,b:any)=>a.kickoff.localeCompare(b.kickoff)).slice(0,70);},[fixtures,online,query]);
 useEffect(()=>{if(report&&!busy)document.getElementById('match-lab-report')?.scrollIntoView({behavior:'smooth',block:'start'});},[report,busy]);
 async function analyze(id:string,force=false){setSelected(id);setBusy(true);setError('');if(id!==selected)setReport(null);try{const response=await fetch('/api/match/analyze?id='+encodeURIComponent(id)+(force?'&refresh=1':''),{cache:'no-store',signal:AbortSignal.timeout(45000)});const result=await readApiJson(response);setReport(result);}catch(e){setError(apiErrorMessage(e));}finally{setBusy(false);}}
 async function searchOnline(){const term=query.trim();if(term.length<2){setSearchNote('Enter at least two characters to search public match sources.');return;}setSearchBusy(true);setSearchNote('');try{const response=await fetch('/api/web/search?q='+encodeURIComponent(term),{cache:'no-store',signal:AbortSignal.timeout(45000)});const result=await readApiJson(response);setOnline(result.fixtures||[]);setSearchNote(`${(result.fixtures||[]).length} matching fixtures found across connected public sources.`);}catch(e){setSearchNote(apiErrorMessage(e));}finally{setSearchBusy(false);}}
 return <div className="analyzer-page">
  <div className="analyzer-intro"><div className="analyzer-orb"><ScanSearch size={28}/></div><div><span className="eyebrow">ONE MATCH · DEEPER CONTEXT</span><h2>Match Lab<span className="mint">.</span></h2><p>Choose a fixture for a tailored Arata forecast, likely scores and price-aware ticket guidance.</p></div></div>
  <div className="analyzer-search-panel"><label htmlFor="match-lab-search">Find a match or league</label><div className="analyzer-search-row"><div className="analyzer-search-input"><Search size={18}/><input id="match-lab-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search team or league" autoComplete="off"/></div><button className="secondary" onClick={searchOnline} disabled={searchBusy||query.trim().length<2}>{searchBusy?<RefreshCw size={16} className="spin"/>:<ScanSearch size={16}/>}<span>{searchBusy?'Searching…':'Search sources'}</span></button></div><p className="small muted">Results filter as you type. Search sources to discover a match beyond the current list.</p>{searchNote&&<p className="small" role="status">{searchNote}</p>}</div>
  <DateWindow range={range} onChange={onRangeChange}/>
  <div className="analyzer-match-list" aria-label="Available matches">{matches.length?matches.map((f:any)=><button key={f.id} type="button" className={'analyzer-match'+(selected===f.id?' selected':'')} onClick={()=>void analyze(f.id)} aria-pressed={selected===f.id}><span className="analyzer-league">{f.league}</span><strong>{f.home} <span>vs</span> {f.away}</strong><small><Clock3 size={13}/>{eat(f.kickoff)}</small><ArrowRight className="analyzer-match-arrow" size={17}/></button>):<div className="empty compact"><Search size={24}/><h3>No matching upcoming fixtures</h3><p>Try another team or date window, or search the connected public sources.</p></div>}</div>
  {busy&&<div className="analyzer-working" role="status"><div className="analyzer-working-icon"><Sparkles size={26}/></div><div><strong>Reviewing match evidence</strong><p>Comparing form, venue, H2H, squad context, model calibration and available prices…</p></div></div>}
  {error&&<p className="notice error" role="alert">{error}</p>}
  {report&&!busy&&<div id="match-lab-report" className="analyzer-report" aria-live="polite"><div className="analyzer-report-head"><div><span className="analyzer-league">{report.fixture.league}</span><h2>{report.fixture.home} <span className="muted">vs</span> {report.fixture.away}</h2><p className="small muted">{eat(report.fixture.kickoff)} · Analysis updated {eat(report.generated)}</p></div><button className="secondary" onClick={()=>void analyze(report.fixture.id,true)}><RefreshCw size={16}/>Refresh analysis</button></div>
   {!report.model?.available?<div className="analyzer-verdict avoid"><TriangleAlert size={24}/><div><b>No reliable independent forecast yet</b><p>{report.decisionReason}</p></div></div>:<>
    <div className="analyzer-hero-stats"><div><small>Home win</small><strong>{pct(report.model.probabilities.home)}</strong></div><div><small>Draw</small><strong>{pct(report.model.probabilities.draw)}</strong></div><div><small>Away win</small><strong>{pct(report.model.probabilities.away)}</strong></div><div><small>Expected goals</small><strong>{report.model.expectedGoals.home.toFixed(2)} – {report.model.expectedGoals.away.toFixed(2)}</strong></div></div>
    <div className={'analyzer-verdict '+(report.decision==='consider'?'consider':'avoid')}>{report.decision==='consider'?<ShieldCheck size={23}/>:<TriangleAlert size={23}/>}<div><b>{report.decision==='consider'?'Conditional ticket candidate':'Leave off the ticket for now'}</b><p>{report.decisionReason}</p></div></div>
    <div className="analyzer-score-panel"><div className="section-heading"><div><h3><Goal size={19}/> Probable full-time scores</h3><p className="small muted">Indicative score-grid estimates. Exact scores remain uncertain and are not calibrated betting prices.</p></div></div><div className="analyzer-scores">{report.scorelines.map((s:any)=><div key={s.home+'-'+s.away}><strong>{s.home} – {s.away}</strong><span>{pct(s.probability)}</span></div>)}</div></div>
    <div className="analyzer-tiers"><div className="section-heading"><div><h3>Choice by risk level</h3><p className="small muted">A listed option is actionable only with a fresh quoted price and enough model value.</p></div></div><div className="analyzer-tier-grid">{report.tiers.map((tier:any)=><article key={tier.name} className={'analyzer-tier '+(tier.actionable?'actionable':'')}><span className="analyzer-tier-label">{tier.name}</span><p>{tier.description}</p>{tier.option?<><strong>{marketLabel({...tier.option,home:report.fixture.home,away:report.fixture.away})}</strong><div className="analyzer-tier-numbers"><span>Model chance <b>{pct(tier.option.probability)}</b></span><span>Fair odds <b>{tier.option.fairOdds.toFixed(2)}</b></span><span>Current price <b>{tier.option.odds?tier.option.odds.toFixed(2):'—'}</b></span><span>Value edge <b>{tier.option.edge!=null?pct(tier.option.edge):'—'}</b></span></div><small>{tier.actionable?`Quoted by ${tier.option.bookmaker} · ${eat(tier.option.oddsCaptured)}`:`Wait for a fresh price above ${tier.option.minimumValueOdds?.toFixed(2)||'fair odds'} before considering this selection.`}</small>{tier.option.sourceUrl&&<a href={tier.option.sourceUrl} target="_blank" rel="noreferrer">View price source <ExternalLink size={12}/></a>}</>:<span className="small muted">No supported option in this probability band.</span>}</article>)}</div></div>
    <div className="analyzer-coverage"><b>Evidence check</b><span>{report.coverage.historyMatches} league results · {report.coverage.homeMatches} {report.fixture.home} results · {report.coverage.awayMatches} {report.fixture.away} results</span><span>Learning: {report.coverage.learning==='validated-active'?'validated update active':'collecting verified outcomes'} · Lineups: {report.coverage.lineupStatus.home} / {report.coverage.lineupStatus.away}</span><p>Unknown injury or lineup status is never treated as confirmed availability. Check team news and final lineups before making a decision.</p></div>
    <details className="analyzer-evidence"><summary>Open full form, H2H, squad and source evidence</summary><ModelEvidence model={report.model} home={report.fixture.home} away={report.fixture.away}/></details>
   </>}
  </div>}
 </div>;
}
