"use client";
import {useEffect,useState,useRef} from 'react';
import {Download,WifiOff} from 'lucide-react';
export default function PwaTools(){
 const [prompt,setPrompt]=useState<any>(null),[installed,setInstalled]=useState(false),[online,setOnline]=useState(true),[help,setHelp]=useState(false);
 const [update,setUpdate]=useState<ServiceWorker|null>(null),updating=useRef(false);
 useEffect(()=>{if(!('serviceWorker' in navigator))return;let disposed=false;const changed=()=>{if(updating.current)window.location.reload();};navigator.serviceWorker.addEventListener('controllerchange',changed);navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(reg=>{const inspect=()=>{if(!disposed&&reg.waiting)setUpdate(reg.waiting);};inspect();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',inspect));}).catch(console.error);return()=>{disposed=true;navigator.serviceWorker.removeEventListener('controllerchange',changed);};},[]);
 useEffect(()=>{const mode=window.matchMedia('(display-mode: standalone)'),check=()=>setInstalled(mode.matches||(navigator as any).standalone===true),connection=()=>setOnline(navigator.onLine),ready=(event:any)=>{event.preventDefault();setPrompt(event);},done=()=>{setPrompt(null);setInstalled(true);};check();connection();mode.addEventListener('change',check);window.addEventListener('online',connection);window.addEventListener('offline',connection);window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);return()=>{mode.removeEventListener('change',check);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);};},[]);
 async function install(){if(!prompt){setHelp(v=>!v);return;}try{await prompt.prompt();await prompt.userChoice;}finally{setPrompt(null);}}
 return <><div className="pwa-tools">{!installed&&<button className="secondary" onClick={install}><Download size={15}/>Install Arata Odds</button>}{installed&&<span className="small muted">Arata Odds · installed app</span>}{update&&<button className="secondary" onClick={()=>{updating.current=true;update.postMessage({type:'SKIP_WAITING'});}}>Update app · reloads this page</button>}{help&&!installed&&<p className="small muted">In Chrome or Edge, open the browser menu and choose Install app. On iPhone, open in Safari, tap Share, then Add to Home Screen. Installation requires HTTPS or localhost.</p>}</div>{!online&&<p className="notice offline-banner" role="status"><WifiOff size={16}/> Offline. Live scores, current prices and saving tickets require a connection. Reconnect before reviewing a pick.</p>}</>;
}
