"use client";
import {useEffect,useState} from 'react';
import {Headset,Mail,MessageCircle,Save} from 'lucide-react';
import {DEFAULT_SUPPORT_CONTACTS,whatsappUrl} from '@/lib/support-settings.mjs';
import {readApiJson,apiErrorMessage} from '@/lib/api-client.mjs';

type Contacts={email:string;whatsapp:string;updated?:string|null};

export default function SupportSettings(){
 const [saved,setSaved]=useState<Contacts>(DEFAULT_SUPPORT_CONTACTS),[email,setEmail]=useState<string>(DEFAULT_SUPPORT_CONTACTS.email),[whatsapp,setWhatsapp]=useState<string>(DEFAULT_SUPPORT_CONTACTS.whatsapp),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let mounted=true;const load=async()=>{try{const value=await readApiJson(await fetch('/api/support',{cache:'no-store'}));if(mounted){setSaved(value);setEmail(value.email);setWhatsapp(value.whatsapp);}}catch(e){if(mounted)setError(apiErrorMessage(e));}finally{if(mounted)setLoading(false);}};void load();const changed=()=>void load();window.addEventListener('arata-support-updated',changed);return()=>{mounted=false;window.removeEventListener('arata-support-updated',changed);};},[]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const value=await readApiJson(await fetch('/api/admin/settings/support',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,whatsapp})}));setSaved(value);setEmail(value.email);setWhatsapp(value.whatsapp);setNotice('Support contacts saved. All app contact links now use these details.');window.dispatchEvent(new CustomEvent('arata-support-updated',{detail:value}));}catch(e){setError(apiErrorMessage(e));}finally{setBusy(false);}}
 const dirty=email.trim().toLowerCase()!==saved.email||whatsapp.trim()!==saved.whatsapp;
 return <section className="panel-card support-settings-panel" aria-labelledby="support-settings-title"><div className="section-heading"><div><span className="eyebrow"><Headset size={14}/> APP CONTACTS</span><h3 id="support-settings-title">Owner & support</h3><p className="small muted">These details appear on the sign-in screen, mobile menu and dashboard footer for every visitor.</p></div></div><form className="account-form" onSubmit={save}><div className="account-fields"><label><span><Mail size={16}/> Support email</span><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={loading||busy} required/></label><label><span><MessageCircle size={16}/> WhatsApp number</span><input type="tel" autoComplete="tel" placeholder="+256791170164" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} disabled={loading||busy} required/><small className="muted">Include the country code, starting with +.</small></label></div><div className="support-settings-actions"><button className="primary" disabled={loading||busy||!dirty}><Save size={16}/>{busy?'Saving…':'Save contacts'}</button>{saved.updated&&<small className="muted">Last updated {new Date(saved.updated).toLocaleString('en-GB',{timeZone:'Africa/Kampala'})} EAT</small>}</div></form><div className="support-settings-preview"><span>Live contact links</span><a href={'mailto:'+saved.email}>{saved.email}</a><a href={whatsappUrl(saved.whatsapp)} target="_blank" rel="noopener noreferrer">WhatsApp {saved.whatsapp}</a></div>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="notice error" role="alert">{error}</p>}</section>;
}
