"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {Trash2,ArrowUpRight,Layers,ShieldCheck,BookmarkCheck,CalendarClock} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Prediction,Ticket} from '@/lib/types';
import {readApiJson,apiErrorMessage} from '@/lib/api-client.mjs';
import {marketLabel} from '@/lib/markets.mjs';
import {ticketTotals} from '@/lib/live.mjs';
import {ticketAdvice} from '@/lib/league-tickets.mjs';
import {matchingTicket,pendingKickoff} from '@/lib/ticket-identity.mjs';
import GeneratedTickets,{RiskAdvice} from './GeneratedTickets';
const pct=(n:number)=>(100*n).toFixed(1)+'%';
export default function TicketReview({legs,setLegs,plan,onSaved,tickets=[],loading=false,phase='fixtures',analysisError='',onTickets}:{legs:Prediction[];setLegs:(p:Prediction[])=>void;plan:any;onSaved:()=>void;tickets?:Ticket[];loading?:boolean;phase?:string;analysisError?:string;onTickets?:()=>void}){
 const [loadedLegCount,setLoadedLegCount]=useState<number|null>(null),[open,setOpen]=useState(false);
 const [stake,setStake]=useState('10'),[name,setName]=useState('My ticket'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const saving=useRef(false),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(loadedLegCount!==null&&loadedLegCount!==plan.legCount){setLegs([]);setLoadedLegCount(null);setOpen(false);setName('My ticket');setSuccess('Pick count changed. Review a newly generated ticket.');}},[plan.legCount,loadedLegCount,setLegs]);
 let preview:any=null,validation='';try{if(legs.length)preview=ticketTotals(legs,Number(stake));}catch(e){validation=(e as Error).message;}
 const duplicate=matchingTicket(tickets,legs);
 function openReview(){opener.current=document.activeElement as HTMLElement;setError('');setOpen(true);}
 const loadGenerated=useCallback((t:any,i:number)=>{opener.current=document.activeElement as HTMLElement;setLoadedLegCount(t.legs.length);setLegs(t.legs);setName(`Generated ticket ${i+1} · ${t.legs.length} picks`);setError('');setSuccess('');setOpen(true);},[setLegs]);
 async function save(){if(saving.current||duplicate)return;saving.current=true;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(legs.every((l:any)=>l.kind==='quote')?{selectionIds:legs.map(l=>l.id)}:legs.every((l:any)=>l.kind!=='quote')?{predictionIds:legs.map(l=>l.id)}:{mixedSelections:legs.map((l:any)=>({id:l.id,kind:l.kind||'prediction'}))}),stake:Number(stake),name,reviewedPrices:legs.map(l=>({id:l.id,odds:l.odds,bookmaker:l.bookmaker}))}),signal:AbortSignal.timeout(60000)});await readApiJson(r);setOpen(false);setLegs([]);setLoadedLegCount(null);setSuccess('Prices and estimates are locked. No bet was placed.');onSaved();}catch(e){setError(apiErrorMessage(e));}finally{saving.current=false;setBusy(false);}}
 return <><GeneratedTickets plan={plan} stake={Number(stake)} onLoad={loadGenerated} loading={loading} phase={phase} analysisError={analysisError}/>
 {success&&<div className="save-confirmation" role="status"><BookmarkCheck size={20}/><div><b>Ticket collection updated</b><p>{success}</p></div>{onTickets&&<button className="text-button" onClick={onTickets}>View tickets →</button>}</div>}
 <div className="draft-review-launch"><div className="draft-review-icon"><Layers size={23}/></div><div><h3>{legs.length?`Your draft · ${legs.length} picks`:'Build your own combination'}</h3><p className="small muted">{legs.length?'Check your selections, prices and risk in Ticket Review.':'Choose matches below, or review a generated alternative.'}</p></div><button className="primary" onClick={openReview} disabled={!legs.length}>Review draft <ArrowUpRight size={16}/></button></div>
 <Dialog open={open} onOpenChange={value=>{if(!saving.current)setOpen(value);}}><DialogContent className="ticket-review-modal" onCloseAutoFocus={e=>{e.preventDefault();opener.current?.focus();}}>
 <DialogHeader className="review-header"><span className="eyebrow"><ShieldCheck size={15}/> YOUR PERSONAL RESEARCH</span><DialogTitle>Ticket Review<span className="mint">.</span></DialogTitle><DialogDescription>Make a considered choice. Review the matches and save this combination to your collection.</DialogDescription><span className="review-count">{legs.length} picks · {preview?.odds.toFixed(2)||'—'} combined odds</span></DialogHeader>
 <div className="review-body"><label className="input-label">Ticket name<Input value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><ol className="review-leg-list">{legs.map((l,i)=><li className="review-leg" key={l.id}><span className="review-leg-number">{String(i+1).padStart(2,'0')}</span><div><strong>{l.home} <span className="muted">vs</span> {l.away}</strong><p>{marketLabel(l)} <span className="mint">@ {l.odds?.toFixed(2)}</span></p>{pendingKickoff(l)&&<span className="pending-kickoff"><CalendarClock size={12}/><time dateTime={l.kickoff}>{pendingKickoff(l)}</time></span>}<small className="muted">{l.bookmaker} · {l.probability!=null?pct(l.probability)+' model probability':'Price-only selection'}</small></div><button className="text-button review-remove" aria-label={'Remove '+marketLabel(l)} onClick={()=>setLegs(legs.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></li>)}</ol>
 {!legs.length&&<p className="notice">This draft is empty. Close the review to choose current matches.</p>}{legs.some((l:any)=>l.unavailable)&&<p className="notice error">A draft selection is suspended, expired or no longer available. Remove it or choose a current quote.</p>}
 <label className="input-label">Reference stake · units<Input type="number" min=".01" step=".01" max="1000000000" value={stake} onChange={e=>setStake(e.target.value)}/><small className="muted">For return calculations only. No money is committed.</small></label>
 <div className="ticket-metrics review-metrics"><div><small>Combined odds</small><strong>{preview?.odds.toFixed(2)||'—'}×</strong></div><div><small>Potential return</small><strong className="mint">{preview?.potentialReturn.toFixed(2)||'—'}</strong></div><div><small>Estimated win chance*</small><strong>{preview?.probability!=null?pct(preview.probability):'Unavailable'}</strong></div><div><small>Expected return*</small><strong>{preview?.expectedReturn!=null?pct(preview.expectedReturn):'Unavailable'}</strong></div></div>
 {preview&&<RiskAdvice advice={ticketAdvice(legs)}/>}<p className="review-disclaimer">*Model estimates assume independent matches. Live and price-only picks have no estimated win chance. Potential return includes the reference stake. Saving records your research and does not place a bet.</p>
 {duplicate&&<div className="notice duplicate-notice" role="status"><BookmarkCheck size={18}/><div><b>Already in your collection</b><p>This combination is saved as “{duplicate.name}”. A different name or stake does not create another ticket.</p>{onTickets&&<button className="text-button" onClick={()=>{setOpen(false);onTickets();}}>View saved tickets →</button>}</div></div>}{(error||validation)&&<p className="notice error" role="alert">{error||validation}</p>}</div>
 <div className="review-footer"><div><BookmarkCheck size={16}/><span>One combination. One saved record.</span></div><button className="primary" disabled={!preview||busy||!!duplicate||legs.some((l:any)=>l.unavailable)} onClick={save}><BookmarkCheck size={16}/>{busy?'Saving…':duplicate?'Already saved':'Save to Tickets'}</button></div>
 </DialogContent></Dialog></>;
}
