"use client";
import {CalendarClock} from 'lucide-react';
import {pendingKickoff} from '@/lib/ticket-identity.mjs';
import {useState} from 'react';
import type {Ticket} from '@/lib/types';
import {marketLabel} from '@/lib/markets.mjs';
import MatchStatus from './MatchStatus';
import {RiskAdvice} from './GeneratedTickets';
import {ticketList} from '@/lib/ticket-list.mjs';
const selectionLabel=marketLabel;
export default function Tickets({tickets,loading=false}:{tickets:Ticket[];loading?:boolean}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all');
 const listing=ticketList(tickets,query,status);const visible:Ticket[]=listing.matches,counts:Record<string,number>=listing.counts;
 return <><label className="input-label">Search saved tickets<input className="league-input" placeholder="Ticket name or team" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ticket-filters" aria-label="Filter saved tickets">{['all','pending','running','won','lost'].map(value=><button key={value} aria-pressed={status===value} className={'ticket-filter '+value+(status===value?' selected':'')} onClick={()=>setStatus(value)}><span>{value[0].toUpperCase()+value.slice(1)}</span><b>{counts[value]}</b></button>)}</div><p className="muted small">Pending tickets first · newest first within each group</p>{loading&&<p className="notice" role="status">Loading saved tickets…</p>}
<p className="notice">Running tickets show current scores and match clocks. They are research records; no bet is placed.</p><h2 className="subheading">Saved tickets <span className="muted">({visible.length})</span></h2>{!visible.length?<div className="empty compact"><p>No saved tickets match this filter.</p></div>:visible.map(t=><div className={'fixture-card saved-ticket '+t.status} key={t.id}><div className="section-heading"><h3>{t.name}</h3><span className={'ticket-outcome '+t.status}>TICKET {t.status==='won'?'WON':t.status==='lost'?'LOST':(t as any).running?'RUNNING':'PENDING'}</span></div><p className="small muted">{((t as any).progress||[]).filter((l:any)=>l.legOutcome==='won').length} won · {((t as any).progress||[]).filter((l:any)=>l.legOutcome==='lost').length} lost · {((t as any).progress||[]).filter((l:any)=>!l.legOutcome||l.legOutcome==='pending').length} pending</p>{((t as any).progress||[]).map((l:any)=><div className="ticket-match" key={l.id}><div className="ticket-leg-heading"><strong>{l.home} vs {l.away}</strong><span className={'leg-outcome '+(l.legOutcome||'pending')}>{l.legOutcome==='won'?'✓ Pick won':l.legOutcome==='lost'?'× Pick lost':'Pick pending'}</span></div><small>{selectionLabel(l)} · locked odds {l.odds.toFixed(2)}</small>{pendingKickoff(l)&&<span className="pending-kickoff"><CalendarClock size={13}/><time dateTime={l.kickoff}>{pendingKickoff(l)}</time></span>}<MatchStatus fixture={{...l,status:l.fixtureStatus,liveSource:l.liveSource||'Live update'}}/></div>)}{(t as any).advice&&<RiskAdvice advice={(t as any).advice}/>}<p className="small muted">{t.legs.length} picks · {t.odds.toFixed(2)} combined odds · {t.stake.toFixed(2)} reference units</p><p>Potential return <strong className="mint">{t.potentialReturn.toFixed(2)} units</strong></p></div>)}</>;
}
