import {outcomePredicate,supportedMarket} from './market-outcomes.mjs';
import {teamKey} from './domain.mjs';
import {marketKey,halfLine} from './markets.mjs';
import {enhanceForecast} from './player-impact.mjs';
import {coreGoals,DEFAULT_WEIGHTS,scoreProbabilities,probabilityFor} from './goal-core.mjs';
import {usableActive,activeWeights,calibratedMarkets} from './learning-engine.mjs';
export {scoreProbabilities,probabilityFor} from './goal-core.mjs';
export const ARATA_VERSION='arata-adaptive-goals-v3';
export const PREDICTORS=['arata','betbetter','blend'];
export const PREDICTOR_NAMES={arata:'Arata Model',betbetter:'Bet Better',blend:'Arata + Bet Better'};
const aliases={houstondynamofc:'houstondynamo',lafc:'losangeles',fcarsenal:'arsenal',brentfordfc:'brentford',manchesterunitedfc:'manutd',tottenhamhotspurfc:'tottenham',stlouiscity:'stlouiscity',redbullnewyork:'newyork',losangelesfootballclub:'losangeles',fcdallas:'dallas',atlanta:'atlantaunited',atlantautd:'atlantaunited',charlottefc:'charlotte',seattlesoundersfc:'seattlesounders',minnesotaunitedfc:'minnesotaunited',lagalaxy:'losangelesgalaxy',saintlouiscitysc:'stlouiscity',sandiegofc:'sandiego',mancity:'manchestercity',manunited:'manutd',nottmforest:'nottinghamforest',leedsunited:'leeds',brighton:'brighton',athleticclub:'athbilbao',athleticbilbao:'athbilbao',atleticomadrid:'athmadrid',atleticodemadrid:'athmadrid',realbetis:'betis',realsociedad:'sociedad',fcbarcelona:'barcelona',rcceltadevigo:'celta',celtavigo:'celta',intermilan:'inter',internazionale:'inter',acmilan:'milan',asroma:'roma',parissaintgermain:'psg',parisstgermain:'psg',olympiquelyonnais:'lyon',olympiquedemarseille:'marseille',asmonaco:'monaco',staderennais:'rennes',lilleosc:'lille',stadebrestois29:'brest',rcstrasbourg:'strasbourg',rclens:'lens',angerssco:'angers',fcnantes:'nantes',losangelesfc:'losangeles',sportingkc:'sportingkansascity',newyorkredbulls:'newyork',newyorkcityfc:'newyorkcity',atlantautdfc:'atlantaunited',atlantaunitedfc:'atlantaunited',intermiamicf:'intermiami',orlandocitysc:'orlandocity',torontofc:'toronto',fcincinnati:'cincinnati',fccincinnati:'cincinnati',cfmontreal:'montreal',vancouverwhitecapsfc:'vancouverwhitecaps',chicagofirefc:'chicagofire',coloradorapids:'colorado',columbuscrewsc:'columbuscrew',nashvillesc:'nashville',austinfc:'austin',fcstlouis:'stlouiscity',stlouiscitysc:'stlouiscity',fcunionberlin:'unionberlin','1fcunionberlin':'unionberlin',eintrachtfrankfurt:'frankfurt',scfreiburg:'freiburg',vflwolfsburg:'wolfsburg',vfbStuttgart:'stuttgart',vfbstuttgart:'stuttgart',bayer04leverkusen:'leverkusen',bayerleverkusen:'leverkusen',borussiadortmund:'dortmund',fcausgburg:'augsburg',fcaugsburg:'augsburg',tsg1899hoffenheim:'hoffenheim',tsghoffenheim:'hoffenheim',werderbremen:'bremen',svwerderbremen:'bremen',hamburgersv:'hamburg'};
export function modelTeam(name){const key=teamKey(name);return aliases[key]||key;}
export function csvRows(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(Boolean))rows.push(row);row=[];value='';}else value+=c;}if(value||row.length){row.push(value);rows.push(row);}const headers=(rows.shift()||[]).map(x=>x.replace(/^\uFEFF/,''));return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
export function parseHistoricalCsv(text,leagueId,sourceUrl,now=Date.now()){
 const records=[];for(const r of csvRows(text)){const date=String(r.Date).match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);if(!date)continue;const year=date[3].length===2?'20'+date[3]:date[3],day=`${year}-${date[2].padStart(2,'0')}-${date[1].padStart(2,'0')}`;
 // A date-only result becomes usable after the complete UTC date; no same-day leakage.
 const availableAt=Date.parse(day+'T23:59:59Z'),home=r.HomeTeam||r.Home,away=r.AwayTeam||r.Away,hg=r.FTHG??r.HG,ag=r.FTAG??r.AG;if(!home||!away||hg===''||ag===''||!Number.isFinite(availableAt)||new Date(availableAt).toISOString().slice(0,10)!==day||availableAt>=now)continue;
 const score={home:Number(hg),away:Number(ag)};if(!Object.values(score).every(x=>Number.isInteger(x)&&x>=0&&x<=30))continue;
 records.push({home,away,leagueId,kickoff:day+'T12:00:00Z',availableAt:new Date(availableAt).toISOString(),status:'finished',score,source:'Football-Data.co.uk',sourceUrl,shotsHome:r.HS===''?null:Number(r.HS),shotsAway:r.AS===''?null:Number(r.AS),shotsOnTargetHome:r.HST===''?null:Number(r.HST),shotsOnTargetAway:r.AST===''?null:Number(r.AST)});}
 return records;
}
const clamp=(v,low,high)=>Math.min(high,Math.max(low,v));
function avg(matches,selector,cutoff,prior=1.4){let total=prior*6,weight=6;for(const m of matches){const w=Math.exp(-Math.log(2)*Math.max(0,(cutoff-Date.parse(m.availableAt||m.kickoff))/86400000)/120);total+=selector(m)*w;weight+=w;}return total/weight;}
export function forecastArata(fixture,history,context={},now=Date.now()){
 const cutoff=Math.min(now,Date.parse(fixture.kickoff)),h=modelTeam(fixture.home),a=modelTeam(fixture.away),unique=new Map();for(const m of history){const time=Date.parse(m.availableAt||m.kickoff);if(m.leagueId!==fixture.leagueId||m.status!=='finished'||!m.score||!Number.isFinite(time)||time>=cutoff||cutoff-time>730*86400000)continue;const key=[m.leagueId,modelTeam(m.home),modelTeam(m.away),String(m.kickoff).slice(0,10)].join('|');if(!unique.has(key))unique.set(key,m);}
 const league=[...unique.values()].sort((a,b)=>Date.parse(b.kickoff)-Date.parse(a.kickoff));const games=team=>league.filter(m=>modelTeam(m.home)===team||modelTeam(m.away)===team).slice(0,40),home=games(h),away=games(a);
 if(league.length<40||home.length<8||away.length<8)return {available:false,reason:'At least 40 league results and 8 recent results per team are required.',coverage:{leagueMatches:league.length,homeMatches:home.length,awayMatches:away.length}};
 const lastHome=Date.parse(home[0].availableAt||home[0].kickoff),lastAway=Date.parse(away[0].availableAt||away[0].kickoff);if(cutoff-lastHome>90*86400000||cutoff-lastAway>90*86400000)return {available:false,reason:'Team history is more than 90 days old.'};
 const gf=(m,t)=>modelTeam(m.home)===t?m.score.home:m.score.away,ga=(m,t)=>modelTeam(m.home)===t?m.score.away:m.score.home;
 const baseH=avg(league,m=>m.score.home,cutoff,1.5),baseA=avg(league,m=>m.score.away,cutoff,1.2),base=(baseH+baseA)/2;
 const rates=(matches,t,venue)=>{const split=matches.filter(m=>modelTeam(m[venue])===t);return {attack:avg(matches,m=>gf(m,t),cutoff,base),venueAttack:avg(split,m=>gf(m,t),cutoff,venue==='home'?baseH:baseA),defence:avg(matches,m=>ga(m,t),cutoff,base),venueDefence:avg(split,m=>ga(m,t),cutoff,venue==='home'?baseA:baseH)};};
 const hr=rates(home,h,'home'),ar=rates(away,a,'away'),form=(matches,t)=>avg(matches.slice(0,5),m=>gf(m,t)-ga(m,t),cutoff,0);
 const h2h=league.filter(m=>[modelTeam(m.home),modelTeam(m.away)].includes(h)&&[modelTeam(m.home),modelTeam(m.away)].includes(a)).slice(0,5);
 const features={schema:1,baseH,baseA,base,homeAttack:hr.attack,homeVenueAttack:hr.venueAttack,homeDefence:hr.defence,homeVenueDefence:hr.venueDefence,awayAttack:ar.attack,awayVenueAttack:ar.venueAttack,awayDefence:ar.defence,awayVenueDefence:ar.venueDefence,formDifference:form(home,h)-form(away,a),h2hCount:h2h.length,h2hPriorWeight:6/(6+h2h.reduce((n,m)=>n+Math.exp(-Math.log(2)*Math.max(0,(cutoff-Date.parse(m.availableAt||m.kickoff))/86400000)/120),0)),h2hHome:h2h.length>=3?avg(h2h,m=>gf(m,h),cutoff,0):0,h2hAway:h2h.length>=3?avg(h2h,m=>gf(m,a),cutoff,0):0,homeAdjustment:1,awayAdjustment:1};
 const initialGoals=coreGoals(features,DEFAULT_WEIGHTS),cells=scoreProbabilities(initialGoals.home,initialGoals.away),probabilities=Object.fromEntries(['home','draw','away'].map(selection=>[selection,probabilityFor(cells,{market:'1X2',selection})]));
 const recent= (matches,t)=>matches.slice(0,5).map(m=>({date:m.kickoff,opponent:modelTeam(m.home)===t?m.away:m.home,goalsFor:gf(m,t),goalsAgainst:ga(m,t),result:gf(m,t)>ga(m,t)?'W':gf(m,t)<ga(m,t)?'L':'D',sourceUrl:m.sourceUrl}));
 const markets=new Map(['home','draw','away'].map(selection=>[marketKey({market:'1X2',selection,line:null}),{market:'1X2',selection,line:null,period:'FT'}]));for(const q of fixture.quotes||[])if(q.period==='FT'&&supportedMarket(q))markets.set(marketKey(q),{market:q.market,selection:q.selection,line:q.line??null,period:'FT'});
 const evidence={kickoff:fixture.kickoff,homeForm:recent(home,h),awayForm:recent(away,a),h2h:h2h.map(m=>({home:m.home,away:m.away,score:m.score,kickoff:m.kickoff,sourceUrl:m.sourceUrl})),homeRestDays:Math.floor((cutoff-lastHome)/86400000),awayRestDays:Math.floor((cutoff-lastAway)/86400000),availability:context.availability||{status:'unknown',reports:[]},sources:[...new Set(league.map(m=>m.source))],homeMatches:home.length,awayMatches:away.length,leagueMatches:league.length,historyThrough:league.reduce((s,m)=>m.availableAt>s?m.availableAt:s,''),captured:context.captured||new Date(now).toISOString(),stale:context.stale===true};
 const baseForecast={available:true,predictor:'arata',version:ARATA_VERSION,created:new Date(now).toISOString(),probabilities,expectedGoals:initialGoals,evidence,markets:[...markets.values()].map(m=>({...m,probability:probabilityFor(cells,m),confidence:'LEAN',version:ARATA_VERSION,verdict:'Independent goal model · provisional; learning requires validated settled forecasts.'}))};
 const enhanced=context.advanced?enhanceForecast(baseForecast,fixture,context.advanced,now):null;
 if(enhanced){features.homeAdjustment=enhanced.expectedGoals.home/initialGoals.home;features.awayAdjustment=enhanced.expectedGoals.away/initialGoals.away;}
 const active=usableActive(context.learning,cutoff),weights=activeWeights(active,fixture.leagueId),baselineGoals=coreGoals(features,DEFAULT_WEIGHTS),expectedGoals=coreGoals(features,weights),baselineCells=scoreProbabilities(baselineGoals.home,baselineGoals.away),learnedCells=scoreProbabilities(expectedGoals.home,expectedGoals.away);
 const corrected=calibratedMarkets(baseForecast.markets.map(m=>({...m,probability:probabilityFor(learnedCells,m),baselineProbability:probabilityFor(baselineCells,m),learningVersion:active?.revision||'baseline'})),fixture.leagueId,active);
 return {...baseForecast,expectedGoals,probabilities:Object.fromEntries(corrected.filter(m=>m.market==='1X2').map(m=>[m.selection,m.probability])),markets:corrected,evidence:{...evidence,...(enhanced?{advanced:enhanced.evidence}:{}),coreFeatures:features,learning:{revision:active?.revision||'baseline',status:active?'validated-active':'collecting',activatedAt:active?.activatedAt,weights,baselineGoals,calibrated:!!active&&Object.keys(active.calibrators||{}).length>0}}};
}
export function blendMarkets(arata,external){if(!arata?.available)return [];const map=new Map(external.map(m=>[marketKey(m),m]));return arata.markets.flatMap(a=>{const b=map.get(marketKey(a));return b&&b.probability>0&&b.probability<1?[{...a,probability:(a.probability+b.probability)/2,confidence:'LEAN',version:ARATA_VERSION+'+50-50:'+b.version,verdict:'Equal-weight blend of Arata and Bet Better; provisional.'}]:[];});}
