import {db,saveHistoricalResults} from './store';
import {historicalKey,validHistoricalResult} from './historical-archive.mjs';
import {usableActive} from './learning-engine.mjs';
import {parseHistoricalCsv} from './arata-model.mjs';
import {normalizeSupportContacts} from './support-settings.mjs';

export const BACKUP_VERSION=1;
export const BACKUP_TABLES=['fixtures','predictions','odds_snapshots','tickets','ticket_legs','ticket_quote_legs','historical_results','api_cache','app_settings'] as const;
type Table=typeof BACKUP_TABLES[number];
const keys:Record<Table,string>={fixtures:'id',predictions:'id',odds_snapshots:'id',tickets:'id',ticket_legs:'id',ticket_quote_legs:'id',historical_results:'id',api_cache:'key',app_settings:'key'};
const cacheFilter="(key='learning:registry:v1' OR key LIKE 'learning:audit:%' OR key LIKE 'model-evidence:%' OR key LIKE 'advanced-context:v4:%')";
const historyCodes:Record<string,string>={epl:'E0',bundesliga:'D1','la-liga':'SP1','serie-a':'I1','ligue-1':'F1',mls:'USA'};
function tableName(value:string):Table{if(!BACKUP_TABLES.includes(value as Table))throw new Error('Unknown backup section.');return value as Table;}
function object(value:any){return value&&typeof value==='object'&&!Array.isArray(value);}
function identifier(value:any){return typeof value==='string'&&value.length>0&&value.length<=300;}
function iso(value:any){return typeof value==='string'&&Number.isFinite(Date.parse(value));}
function payload(row:any){if(typeof row.payload!=='string'||row.payload.length>4_500_000)throw new Error('Invalid backup record size.');try{return JSON.parse(row.payload);}catch{throw new Error('Backup record is not valid JSON.');}}
function requireRecord(ok:any){if(!ok)throw new Error('Backup contains an invalid record. No records from this batch were imported.');}

export async function seedHistoricalArchive(league:string){const code=historyCodes[league];if(!code)throw new Error('Unsupported historical league.');const records=await db().prepare("SELECT key,payload FROM api_cache WHERE key LIKE 'https://www.football-data.co.uk/%'").all(),since=Date.now()-730*86400000,history:any[]=[];for(const row of records.results as any[]){const url=String(row.key).split('|')[0];if(!url.endsWith('/'+code+'.csv'))continue;try{const raw=JSON.parse(row.payload).data;if(typeof raw==='string')history.push(...parseHistoricalCsv(raw,league,url).filter((m:any)=>Date.parse(m.kickoff)>since));}catch{}}return {league,archived:await saveHistoricalResults(history)};}

export async function exportBackupPage(section:string,after='',limit=35){const table=tableName(section),key=keys[table],size=Math.min(50,Math.max(1,Number(limit)||35));if(!identifier(after)&&after!=='')throw new Error('Invalid backup cursor.');const where=table==='api_cache'?`AND ${cacheFilter}`:'';const records=await db().prepare(`SELECT * FROM ${table} WHERE ${key}>? ${where} ORDER BY ${key} LIMIT ?`).bind(after,size).all();let rows=records.results as any[];
 if(table==='tickets'&&rows.length){const users=await db().prepare('SELECT id,email FROM auth_users WHERE deleted_at IS NULL').all();const emails=new Map((users.results as any[]).map(u=>[u.id,u.email]));rows=rows.map(row=>({...row,owner_email:emails.get(JSON.parse(row.payload).userId)||null}));}
 return {version:BACKUP_VERSION,table,rows,next:rows.length===size?String(rows.at(-1)[key]):null};}

export async function importBackupBatch(section:string,input:any[],adminId:string){const table=tableName(section);if(!Array.isArray(input)||input.length<1||input.length>50)throw new Error('Import 1–50 records per batch.');const users=table==='tickets'?await db().prepare('SELECT id,email FROM auth_users WHERE deleted_at IS NULL').all():null;const byEmail=new Map((users?.results||[]).map((u:any)=>[String(u.email).toLowerCase(),u.id]));const byId=new Set((users?.results||[]).map((u:any)=>u.id));const commands:any[]=[];
 for(const row of input){requireRecord(object(row));const value=payload(row);requireRecord(object(value));const id=row.id;
  if(table==='fixtures'){requireRecord(identifier(id)&&value.id===id&&iso(row.kickoff)&&value.kickoff===row.kickoff&&typeof value.home==='string'&&typeof value.away==='string'&&identifier(value.leagueId));commands.push(db().prepare('INSERT INTO fixtures(id,kickoff,payload,updated) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.kickoff,row.payload,iso(row.updated)?row.updated:new Date().toISOString()));}
  else if(table==='predictions'){requireRecord(identifier(id)&&identifier(row.fixture_id)&&value.id===id&&value.fixtureId===row.fixture_id&&iso(row.created)&&['pending','won','lost'].includes(row.outcome));commands.push(db().prepare('INSERT INTO predictions(id,fixture_id,created,outcome,payload) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.fixture_id,row.created,row.outcome,row.payload));if(Date.parse(row.created)<Date.parse(value.kickoff))commands.push(db().prepare('INSERT INTO prediction_heads(fixture_id,predictor,market,selection,line_key,prediction_id,created) VALUES(?,?,?,?,?,?,?) ON CONFLICT(fixture_id,predictor,market,selection,line_key) DO UPDATE SET prediction_id=excluded.prediction_id,created=excluded.created WHERE excluded.created>prediction_heads.created OR (excluded.created=prediction_heads.created AND excluded.prediction_id>prediction_heads.prediction_id)').bind(row.fixture_id,value.predictor||'betbetter',value.market||'1X2',value.selection,String(value.line??''),id,row.created));}
  else if(table==='odds_snapshots'){requireRecord(identifier(id)&&identifier(row.fixture_id)&&value.id===id&&value.fixtureId===row.fixture_id&&iso(row.captured));commands.push(db().prepare('INSERT INTO odds_snapshots(id,fixture_id,captured,payload) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.fixture_id,row.captured,row.payload));}
  else if(table==='tickets'){requireRecord(identifier(id)&&value.id===id&&iso(row.created)&&['pending','won','lost'].includes(row.status)&&Array.isArray(value.legs)&&value.legs.length<=10);const owner=byEmail.get(String(row.owner_email||'').toLowerCase())||(byId.has(value.userId)?value.userId:adminId);value.userId=owner;commands.push(db().prepare('INSERT INTO tickets(id,created,status,payload) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.created,row.status,JSON.stringify(value)));}
  else if(table==='ticket_legs'){requireRecord(identifier(id)&&identifier(row.ticket_id)&&identifier(row.prediction_id)&&object(value));commands.push(db().prepare('INSERT INTO ticket_legs(id,ticket_id,prediction_id,payload) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.ticket_id,row.prediction_id,row.payload));}
  else if(table==='ticket_quote_legs'){requireRecord(identifier(id)&&identifier(row.ticket_id)&&identifier(row.fixture_id)&&object(value));commands.push(db().prepare('INSERT INTO ticket_quote_legs(id,ticket_id,fixture_id,payload) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.ticket_id,row.fixture_id,row.payload));}
  else if(table==='historical_results'){requireRecord(identifier(id)&&value.leagueId===row.league_id&&value.kickoff===row.kickoff&&value.source===row.source&&id===historicalKey(value)&&validHistoricalResult(value));commands.push(db().prepare('INSERT INTO historical_results(id,league_id,kickoff,source,payload) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,row.league_id,row.kickoff,row.source,row.payload));}
  else if(table==='api_cache'){requireRecord(identifier(row.key)&&(row.key==='learning:registry:v1'||/^(learning:audit:|model-evidence:|advanced-context:v4:)/.test(row.key))&&object(value));if(row.key==='learning:registry:v1'&&object(value.data))value.data={...value.data,importedActive:usableActive(value.data.active)||null,active:null,status:'collecting',message:'Imported learning profile awaits validation against restored outcomes.'};const expiry=row.key.startsWith('advanced-context:')?Math.max(Number(row.expires)||0,Date.now()+6*3600000):Number.MAX_SAFE_INTEGER;commands.push(db().prepare('INSERT INTO api_cache(key,expires,payload) VALUES(?,?,?) ON CONFLICT(key) DO NOTHING').bind(row.key,expiry,JSON.stringify(value)));}
  else if(table==='app_settings'){requireRecord(row.key==='support_contacts'&&iso(row.updated));const contacts=normalizeSupportContacts(value);commands.push(db().prepare('INSERT INTO app_settings(key,payload,updated) VALUES(?,?,?) ON CONFLICT(key) DO NOTHING').bind('support_contacts',JSON.stringify(contacts),row.updated));}
  else throw new Error('Unknown backup section.');
 }
 await db().batch(commands);return {table,processed:input.length,mode:'merge',note:'Existing records were kept; accounts, passwords and sessions are excluded.'};}
