import {normalizeModel,marketKey,settleMarket} from './markets.mjs';
export const SIDES = ['home', 'draw', 'away'];
export const LEAGUES = [{id:'epl',name:'Premier League',open:'pl'}, {id:'la-liga',name:'La Liga',open:'laliga'}, {id:'bundesliga',name:'Bundesliga',open:'bl1'}, {id:'serie-a',name:'Serie A'}, {id:'ligue-1',name:'Ligue 1'}, {id:'mls',name:'MLS'}];
export function dayKey(date = new Date(), zone = 'Africa/Kampala') {
  const parts = new Intl.DateTimeFormat('en-CA', {timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(date));
  const p = Object.fromEntries(parts.map(x=>[x.type,x.value])); return `${p.year}-${p.month}-${p.day}`;
}
export function dateRange(range, zone='Africa/Kampala', now=new Date()) { if(String(range).startsWith('date:')){const date=range.slice(5);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw new Error('Choose a valid match date.');return {from:date,to:date};}if(range==='live'){const from=dayKey(new Date(new Date(now).getTime()-86400000),zone);return {from,to:dayKey(now,zone),liveOnly:true};}const start=dayKey(now,zone); const d=new Date(start+'T12:00:00Z'); if(range==='tomorrow')d.setUTCDate(d.getUTCDate()+1); const from=d.toISOString().slice(0,10); d.setUTCDate(d.getUTCDate()+(range==='week'?6:range==='upcoming'?30:0)); return {from,to:d.toISOString().slice(0,10)}; }
const aliases = {'atlantaunitedfc':'atlantaunited','atlantautdfc':'atlantaunited','atlantautd':'atlantaunited','seattlesoundersfc':'seattlesounders','minnesotaunitedfc':'minnesotaunited','lagalaxy':'losangelesgalaxy','saintlouiscitysc':'stlouiscity','stlouiscitysc':'stlouiscity','charlottefc':'charlotte','sandiegofc':'sandiego','columbuscrewsc':'columbuscrew','newyorkcityfc':'newyorkcity','intermiamicf':'intermiami','fccincinnati':'cincinnati','orlandocitysc':'orlandocity','vancouverwhitecapsfc':'vancouverwhitecaps','sportingkc':'sportingkansascity','arsenalfc':'arsenal','chelseafc':'chelsea','fulhamfc':'fulham','evertonfc':'everton','liverpoolfc':'liverpool','manchestercityfc':'manchestercity','tottenhamhotspur':'tottenham','newcastleunited':'newcastle','ipswichtown':'ipswich','nottinghamforestfc':'nottinghamforest','westhamunited':'westham','wolverhamptonwanderers':'wolves','brightonhovealbion':'brighton','brightonandhovealbion':'brighton','afcbournemouth':'bournemouth','hullcity':'hull','bayernmunchen':'bayern','bayernmunich':'bayern','fcbayernmunchen':'bayern','borussiamonchengladbach':'gladbach','borussiamgladbach':'gladbach','1fckoln':'koln','fckoln':'koln','cologne':'koln','mainz05':'mainz','1fsvmainz05':'mainz','manchesterunited':'manutd','manunited':'manutd'};
export function teamKey(name) { const k=String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');return aliases[k]||k; }
export function fixtureKey(home,away,kickoff,league) { return `${league}:${teamKey(home)}:${teamKey(away)}:${new Date(kickoff).toISOString()}`; }
export function parseBetBetter(feed,league) {
  if(feed.error) throw new Error(String(feed.error)); if(!Array.isArray(feed.picks))throw new Error('Invalid model response');
  const grouped=new Map();
  for(const p of feed.picks) {

    const teams=String(p.game).split(' @ '); if(teams.length!==2||!Number.isFinite(Date.parse(p.gameTimeUtc)))continue;
    const [away,home]=teams; const id=fixtureKey(home,away,p.gameTimeUtc,league.id);
    const normalized=normalizeModel(p,home,away,teamKey);if(!normalized)continue;const side=normalized.selection;
    const probability=Number(p.modelProbabilityPct)/100; if(!normalized||!Number.isFinite(probability)||probability<=0||probability>=1)continue;
    const f=grouped.get(id)||{id,home,away,league:league.name,leagueId:league.id,kickoff:new Date(p.gameTimeUtc).toISOString(),status:'scheduled',source:'Bet Better',probabilities:{},models:{},marketModels:[],odds:{}};
    const model={...normalized,probability,providerFairOdds:p.fairOdds,confidence:p.confidence,verdict:p.verdict,version:feed.updatedUtc,providerMarket:p.market};
    const index=f.marketModels.findIndex(x=>marketKey(x)===marketKey(model));
    if(index<0)f.marketModels.push(model);else if(p.market==='Head to Head 3-Way')f.marketModels[index]=model;
    if(normalized.market==='1X2'&&(!f.models[side]||p.market==='Head to Head 3-Way')){f.probabilities[side]=probability;f.models[side]=model;}
    grouped.set(id,f);
  }
  return [...grouped.values()];
}
export function parseOpenLiga(rows,league) { if(!Array.isArray(rows))throw new Error('Invalid fixture response');return rows.filter(x=>x.team1&&x.team2&&Number.isFinite(Date.parse(x.matchDateTimeUTC))).map(x=>{const home=x.team1.teamName,away=x.team2.teamName,kickoff=new Date(x.matchDateTimeUTC).toISOString();const score=x.matchIsFinished?x.matchResults?.find(r=>r.resultTypeKind==='After90Minutes'||r.resultTypeID===2):null;return {id:fixtureKey(home,away,kickoff,league.id),externalId:x.matchID,home,away,homeId:x.team1.teamId,awayId:x.team2.teamId,league:league.name,leagueId:league.id,kickoff,status:x.matchIsFinished?'finished':Date.parse(kickoff)<Date.now()?'awaiting-result':'scheduled',score:score?{home:score.pointsTeam1,away:score.pointsTeam2}:null,source:'OpenLigaDB',probabilities:{},models:{},odds:{}};}); }
export function mergeFixtures(fixtures,models) {const out=new Map(fixtures.map(x=>[x.id,x]));for(const m of models){const f=[...out.values()].find(x=>x.leagueId===m.leagueId&&teamKey(x.home)===teamKey(m.home)&&teamKey(x.away)===teamKey(m.away)&&Math.abs(Date.parse(x.kickoff)-Date.parse(m.kickoff))<=15*60000);if(f){out.set(f.id,{...f,probabilities:m.probabilities,models:m.models,marketModels:m.marketModels,modelSource:'Bet Better',modelStale:m.modelStale,modelCaptured:m.modelCaptured});}else out.set(m.id,m);}return [...out.values()];}
export function edge(probability,odds) { if(!Number.isFinite(probability)||!Number.isFinite(odds)||odds<=1)return null;return probability-1/odds; }
export function ticketPreview(legs,stake) {if(!Array.isArray(legs)||!legs.length||legs.length>10)throw new Error('Select between 1 and 10 picks.');if(new Set(legs.map(x=>x.fixtureId)).size!==legs.length)throw new Error('Only one pick per fixture is allowed.');if(!Number.isFinite(stake)||stake<=0||stake>1e9)throw new Error('Enter a positive stake.');for(const l of legs)if(!Number.isFinite(l.odds)||l.odds<=1||!Number.isFinite(l.probability)||l.probability<=0||l.probability>=1)throw new Error('Every leg needs a model probability and valid market odds.'); const odds=legs.reduce((n,l)=>n*l.odds,1),probability=legs.reduce((n,l)=>n*l.probability,1);if(!Number.isFinite(odds)||!Number.isFinite(stake*odds))throw new Error('Ticket total is too large.');return {odds,probability,expectedReturn:probability*odds-1,potentialReturn:stake*odds,stake};}
export function suggestCombinations(picks,maxLegs=3) {const candidates=[...picks].filter(p=>p.edge>.05&&p.odds>1).sort((a,b)=>b.edge-a.edge).slice(0,14);const results=[];function visit(start,legs){if(legs.length>=2){const t=ticketPreview(legs,1);results.push({...t,legs,score:t.expectedReturn*t.probability/Math.sqrt(legs.length)});}if(legs.length>=Math.min(5,Math.max(2,maxLegs)))return;for(let i=start;i<candidates.length;i++){if(legs.some(l=>l.fixtureId===candidates[i].fixtureId))continue;visit(i+1,[...legs,candidates[i]]);}}visit(0,[]);return results.sort((a,b)=>b.score-a.score).slice(0,5);}
export function settlePrediction(p,fixture) {return settleMarket(p,fixture);}
export function performance(predictions,tickets) {const settled=predictions.filter(p=>['won','lost'].includes(p.outcome));const won=settled.filter(p=>p.outcome==='won').length;const closed=tickets.filter(t=>['won','lost'].includes(t.status));const staked=closed.reduce((s,t)=>s+t.stake,0);const profit=closed.reduce((s,t)=>s+(t.status==='won'?t.potentialReturn-t.stake:-t.stake),0);const buckets=new Map();for(const p of [...settled].sort((a,b)=>a.created.localeCompare(b.created))){const date=dayKey(p.created);const b=buckets.get(date)||{date,wins:0,total:0};b.total++;if(p.outcome==='won')b.wins++;buckets.set(date,b);}let wins=0,total=0;return {total:predictions.length,settled:settled.length,pending:predictions.filter(p=>p.outcome==='pending').length,accuracy:settled.length?won/settled.length:null,roi:staked?profit/staked:null,profit,staked,trend:[...buckets.values()].map(b=>{wins+=b.wins;total+=b.total;return {date:b.date,accuracy:100*wins/total,picks:total};})};}
export function historicalContext(fixture,history) {const past=history.filter(f=>f.status==='finished'&&f.score&&Date.parse(f.kickoff)<Date.parse(fixture.kickoff)).sort((a,b)=>b.kickoff.localeCompare(a.kickoff));const hk=teamKey(fixture.home),ak=teamKey(fixture.away);const includes=(f,k)=>teamKey(f.home)===k||teamKey(f.away)===k;const form=k=>past.filter(f=>includes(f,k)).slice(0,5).map(f=>{const own=teamKey(f.home)===k?f.score.home:f.score.away,other=teamKey(f.home)===k?f.score.away:f.score.home;return own>other?'W':own<other?'L':'D';});return {h2h:past.filter(f=>includes(f,hk)&&includes(f,ak)).slice(0,5),homeForm:form(hk),awayForm:form(ak)};}

