import {retainBackground,takeResearchRequest,assertResearchBudget,requestState,requestMemo,researchTimeRemaining,isHostedRequest} from './background.mjs';
import {cachedRead,cachedWrite} from './store';
import {parseOfficialAvailability} from './squad-data.mjs';
import {collectPriorMatches,espnTeams,espnRoster,espnSchedule,espnMatch,matchEvent,statsBombMatch} from './espn-squad.mjs';
import {forecastArata,modelTeam} from './arata-model.mjs';
import {trainEnhancements} from './player-impact.mjs';
const leagues:Record<string,[number,string]>={mls:[130,'mls'],epl:[47,'premier-league'],bundesliga:[54,'bundesliga'],'la-liga':[87,'laliga'],'serie-a':[55,'serie-a'],'ligue-1':[53,'ligue-1']};
const espn:Record<string,string>={mls:'usa.1',epl:'eng.1',bundesliga:'ger.1','la-liga':'esp.1','serie-a':'ita.1','ligue-1':'fra.1'};
function eventState():{memory:Map<string,any>;flight:Map<string,Promise<any>>;pending:Map<string,{fixtures:any[];history:any[]}>;running:Set<string>;workers:number}{return requestState('event-research',()=>({memory:new Map(),flight:new Map(),pending:new Map(),running:new Set(),workers:0}));}
// Store selected structured fields, never megabytes of page HTML or executable scripts.
export async function publicResearch(url:string,ttl:number,parse:(value:string,captured:string)=>any){if(new URL(url).hostname.endsWith('fotmob.com'))throw new Error('Automated FotMob collection is disabled by source terms.');const key='event-research:v3:'+url;const active=eventState().flight.get(key);if(active)return active;const task=(async()=>{const old=eventState().memory.get(key)||await cachedRead(key);if(old&&old.expires>Date.now()){eventState().memory.set(key,old);return old;}assertResearchBudget();takeResearchRequest();const r=await fetch(url,{headers:{'User-Agent':'ArataOdds/1.0 (personal research)','Accept':'text/html,application/json'},signal:AbortSignal.timeout(isHostedRequest()?3000:20000)});if(!r.ok)throw new Error(`Public research source returned ${r.status}`);if(Number(r.headers.get('content-length'))>6000000)throw new Error('Research page exceeds size limit.');const reader=r.body!.getReader(),parts:Uint8Array[]=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>6000000){await reader.cancel();throw new Error('Research page exceeds size limit.');}parts.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const p of parts){bytes.set(p,offset);offset+=p.length;}const captured=new Date().toISOString(),data=parse(new TextDecoder().decode(bytes),captured),value={data,captured,expires:Date.now()+ttl,stale:false};await cachedWrite(key,value.expires,value);eventState().memory.set(key,value);if(eventState().memory.size>80)eventState().memory.delete(eventState().memory.keys().next().value!);return value;})();eventState().flight.set(key,task);try{return await task;}finally{eventState().flight.delete(key);}}
export async function officialAvailability(league:string){try{if(league==='mls'){const index=await publicResearch('https://www.mlssoccer.com/media-resources/',1800000,html=>[...html.matchAll(/href="([^"]*\/news\/mls-player-status-report[^"\s]*)"/g)].map(m=>new URL(m[1],'https://www.mlssoccer.com').href));const url=index.data[0];if(!url||new URL(url).hostname!=='www.mlssoccer.com')throw new Error('Latest official report not linked.');return (await publicResearch(url,1800000,(html,captured)=>parseOfficialAvailability(html,url,captured))).data;}if(league==='epl'){return (await publicResearch('https://fantasy.premierleague.com/api/bootstrap-static/',1800000,(raw,captured)=>{const data=JSON.parse(raw);if(!data.teams?.length||!data.elements?.length)throw new Error('Official player feed incomplete.');return {source:'Official Premier League FPL player status',url:'https://www.premierleague.com/en/latest-player-injuries',captured,modified:captured,validFrom:captured,validUntil:new Date(Date.parse(captured)+7*86400000).toISOString(),status:'official-player-status',teams:data.teams.map((t:any)=>({team:t.name,players:data.elements.filter((p:any)=>p.team===t.id&&['i','s','d','u'].includes(p.status)&&p.news&&Date.parse(p.news_added)<=Date.parse(captured)).map((p:any)=>({name:p.first_name+' '+p.second_name,status:p.chance_of_playing_next_round===0&&['i','s'].includes(p.status)?'out':'questionable',reason:String(p.news).split(/\s+/).slice(0,24).join(' '),published:p.news_added,modified:p.news_added,verified:true,source:'Premier League FPL',sourceUrl:'https://www.premierleague.com/en/latest-player-injuries'}))})),note:'Official fantasy player availability reports, not a complete medical registry. Zero next-round chance with injured/suspended status is treated as OUT; doubtful remains context.'};})).data;}return {status:'not-covered',teams:[],note:'No comprehensive official availability report is connected for this league.'};}catch(e){return {status:'unavailable',teams:[],note:(e as Error).message};}}

const root='https://raw.githubusercontent.com/hudl/open-data/master/data/';
const competitionNames:Record<string,string>={mls:'Major League Soccer',epl:'Premier League',bundesliga:'1. Bundesliga','la-liga':'La Liga','serie-a':'Serie A','ligue-1':'Ligue 1'};
async function espnSummary(id:string,league:string,upcoming=false){return (await publicResearch(`https://site.api.espn.com/apis/site/v2/sports/soccer/${espn[league]}/summary?event=${id}`,upcoming?60000:30*86400000,(raw,captured)=>espnMatch(JSON.parse(raw),id,league,captured))).data;}
async function openArchive(league:string,teams:Set<string>,progress:(s:any)=>void){const index=(await publicResearch(root+'competitions.json',7*86400000,raw=>JSON.parse(raw))).data;const seasons=index.filter((c:any)=>c.competition_name===competitionNames[league]&&c.competition_gender==='male').sort((a:any,b:any)=>String(b.season_name).localeCompare(String(a.season_name)));if(!seasons.length)return {matches:[],season:null,note:'No licensed event archive for this league.'};const season=seasons[0],url=root+`matches/${season.competition_id}/${season.season_id}.json`,all=(await publicResearch(url,30*86400000,raw=>JSON.parse(raw))).data;const selected=all.filter((m:any)=>[modelTeam(m.home_team.home_team_name),modelTeam(m.away_team.away_team_name)].some(k=>teams.has(k))).sort((a:any,b:any)=>b.match_date.localeCompare(a.match_date)).slice(0,60),matches:any[]=[];let cursor=0;await Promise.all([0,1].map(async()=>{while(cursor<selected.length){const meta=selected[cursor++];try{const r=await publicResearch(root+`events/${meta.match_id}.json`,90*86400000,(raw,captured)=>statsBombMatch(meta,JSON.parse(raw),league,captured));matches.push(r.data);}catch{}progress({archiveCompleted:cursor,archiveTotal:selected.length});}}));return {matches,season:season.season_name,note:'StatsBomb Open Data — archival research, not a current injury/lineup feed. Full shot-xG provenance is retained.'};}

export function queueResearch(league:string,fixtures:any[],history:any[]){if(!espn[league]||eventState().pending.has(league))return;eventState().pending.set(league,{fixtures,history});if(eventState().workers<2)retainBackground(drain());}
async function drain(){eventState().workers++;try{while(true){const league=[...eventState().pending.keys()].filter(id=>!eventState().running.has(id)).sort((a,b)=>a==='mls'?-1:b==='mls'?1:0)[0];if(!league)break;const input=eventState().pending.get(league)!;eventState().running.add(league);try{const last=await cachedRead('advanced-context:v4:'+league),ids=[...new Set(input.fixtures.flatMap(f=>[modelTeam(f.home),modelTeam(f.away)]))].sort().join('|');if(last?.expires>Date.now()&&last.data?.scope===ids)continue;await warmLeague(league,input.fixtures,input.history,ids);}catch(e){await cachedWrite('research-job:v4:'+league,Date.now()+3600000,{data:{status:(e as Error).message.startsWith('Research paused')?'paused':'failed',error:(e as Error).message,updated:new Date().toISOString()}});}finally{eventState().pending.delete(league);eventState().running.delete(league);}}}finally{eventState().workers--;}}
async function warmLeague(league:string,fixtures:any[],history:any[],scope:string){const job:any={league,status:'loading',completed:0,total:0,rejected:0,started:new Date().toISOString()};const progress=async(extra:any={})=>{Object.assign(job,extra);job.updated=new Date().toISOString();await cachedWrite('research-job:v4:'+league,Date.now()+3600000,{data:{...job}});};await progress();const base=`https://site.api.espn.com/apis/site/v2/sports/soccer/${espn[league]}/`;
 const directory=(await publicResearch(base+'teams?limit=1000',86400000,raw=>espnTeams(JSON.parse(raw)))).data,needed=new Set(fixtures.flatMap(f=>[modelTeam(f.home),modelTeam(f.away)])),teams=directory.filter((t:any)=>needed.has(modelTeam(t.name))),squads:any={},events=new Map<string,any>(),matches:any={},scheduled:any[]=[],errors:string[]=[],official=await officialAvailability(league),year=new Date().getUTCFullYear();
 let cursor=0;job.total=teams.length;job.teams=teams.length;job.status='collecting-squads';await progress();await Promise.all([0,1].map(async()=>{while(cursor<teams.length){const team=teams[cursor++];try{squads[team.id]=(await publicResearch(base+`teams/${team.id}/roster`,3600000,(raw,captured)=>espnRoster(JSON.parse(raw),team.id,captured))).data;for(const season of [year,year-1]){const r=await publicResearch(base+`teams/${team.id}/schedule?season=${season}`,season===year?3600000:7*86400000,raw=>espnSchedule(JSON.parse(raw),league));scheduled.push(...r.data);}}catch(e){if(errors.length<8)errors.push(team.name+': '+(e as Error).message);}assertResearchBudget();job.completed++;await progress();}}));
 const dates=[...new Set(fixtures.map(f=>f.kickoff.slice(0,10)))];for(const date of dates){try{const r=await publicResearch(base+`scoreboard?dates=${date.replaceAll('-','')}&limit=1000`,date===new Date().toISOString().slice(0,10)?60000:1800000,raw=>espnSchedule(JSON.parse(raw),league));scheduled.push(...r.data);}catch{}}
 assertResearchBudget();const uniqueScheduled=[...new Map(scheduled.map(m=>[m.id,m])).values()],selected=new Map<string,any>();for(const team of teams){for(const m of collectPriorMatches(uniqueScheduled,team.id))selected.set(m.id,m);}
 const upcoming=fixtures.map(f=>matchEvent(f,uniqueScheduled)).filter(Boolean);const tasks=[...upcoming.map(m=>({id:m.id,upcoming:true})),...[...selected.keys()].map(id=>({id,upcoming:false}))];job.total+=tasks.length;job.status='collecting-lineups';await progress();cursor=0;await Promise.all([0,1].map(async()=>{while(cursor<tasks.length){const task=tasks[cursor++];try{const m=await espnSummary(task.id,league,task.upcoming),expected=uniqueScheduled.find(e=>e.id===task.id);if(expected&&(modelTeam(expected.home)!==modelTeam(m.home)||modelTeam(expected.away)!==modelTeam(m.away)||Math.abs(Date.parse(expected.kickoff)-Date.parse(m.kickoff))>15*60000))throw new Error('Schedule and summary identities do not agree.');if(task.upcoming)matches[task.id]=m;else if(m.status==='finished'&&m.score&&m.lineup.status==='historical-confirmed')events.set(m.id,m);else job.rejected++;}catch(e){job.rejected++;if(errors.length<8)errors.push(task.id+': '+(e as Error).message);}assertResearchBudget();job.completed++;if(job.completed%5===0)await progress();}}));
 job.status='collecting-open-events';await progress();const archive=await openArchive(league,needed,extra=>{void progress(extra);}).catch(e=>({matches:[],season:null,note:(e as Error).message}));assertResearchBudget();const archived=archive.matches;for(const m of archived)events.set(m.id,m);job.status='training';await progress();const trained=await trainEnhancements([...events.values()],history,forecastArata),data={league,scope,captured:new Date().toISOString(),fixtures:uniqueScheduled,squads,matches,official,trained,errors,archive:{season:archive.season,note:archive.note,matches:archived.map((m:any)=>({id:m.id,home:m.home,away:m.away,date:m.kickoff,xg:m.xg,sourceUrl:m.sourceUrl,shots:m.shots}))}};await cachedWrite('advanced-context:v4:'+league,Date.now()+6*3600000,{data});await progress({status:'ready',completed:job.total,lineups:[...events.values()].filter(m=>m.source==='ESPN match lineup/results').length,events:archived.length,squads:Object.keys(squads).length,enabledTeams:Object.values(trained.teams).filter((t:any)=>t.attack.enabled||t.defence.enabled).length,xgEnabled:trained.xg.enabled,archiveSeason:archive.season,errors});}
export async function advancedContext(league:string,fixture:any):Promise<any>{const cached=await requestMemo('advanced-context:'+league,()=>cachedRead('advanced-context:v4:'+league));if(!cached)return null;const d=cached.data;let m=matchEvent(fixture,d.fixtures),match=m?d.matches[m.id]:null;try{if(m&&Date.parse(fixture.kickoff)-Date.now()<2*3600000&&Date.parse(fixture.kickoff)>Date.now())match=await espnSummary(m.id,league,true);}catch{match=null;}let official=d.official;if(!official.captured||Date.now()-Date.parse(official.captured)>1800000)official=await officialAvailability(league);
 const side=(s:string)=>{const name=fixture[s],report=official.teams?.find((t:any)=>modelTeam(t.team)===modelTeam(name)),squad=Object.values(d.squads).find((t:any)=>modelTeam(t.team)===modelTeam(name));return {squad,match:match?{status:match.status,captured:match.captured,sourceUrl:match.sourceUrl,lineup:match.lineup,unavailable:match.unavailable[s],news:match.news}:null,official:report?{...official,teams:undefined,players:report.players}:null,coverage:report?'Official report linked; unlisted players remain unknown.':'No comprehensive official absence report for this team/date.',captured:d.captured,stale:Date.now()-Date.parse(d.captured)>24*3600000};};return {trained:d.trained,home:side('home'),away:side('away'),archive:d.archive};}
export async function researchJobs(){return Promise.all(Object.keys(espn).map(async league=>({league,...(await cachedRead('research-job:v4:'+league))?.data||{status:'not-started'}})));}
export async function researchArchive(league:string){if(!espn[league])throw new Error('Unsupported research league.');return (await cachedRead('advanced-context:v4:'+league))?.data?.archive||{matches:[],note:'Licensed event archive is warming.'};}
