import {modelTeam} from './arata-model.mjs';
import {fixtureKey,settlePrediction} from './domain.mjs';
import {leagueIdentity,matchFixture,eat} from './web-parsers.mjs';
export const LIVE_INTERVAL_MS=2000;
export const FIXTURE_INTERVAL_MS=60000;
export function searchMatches(rows,query){const words=String(query||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().split(/\s+/).filter(Boolean);return rows.filter(f=>{const text=[f.home,f.away,f.league].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return words.every(w=>text.includes(w));});}
export function matchClock(raw,period=''){const s=String(raw??'').trim().replace(/[’′]/g,"'");if(/^(HT|HALF.?TIME)$/i.test(s)||/HALFTIME|HALF_TIME/.test(period))return 'HT';if(/^(FT|FULL.?TIME|FINISHED)$/i.test(s))return 'FT';if(/^(NS|NOT STARTED)$/i.test(s))return 'Scheduled';const added=s.match(/^(\d+)\s*\+\s*(\d+)/);if(added)return `${Number(added[1])} + ${Number(added[2])}'`;const n=Number.parseInt(s,10);if(!Number.isFinite(n))return s||'Live';if(period==='FIRST_HALF'&&n>45)return `45 + ${n-45}'`;if(n>90&&n<120)return `90 + ${n-90}'`;return `${n}'`;}
export function parseLiveScore(data,captured,sourceUrl){if(!Array.isArray(data.Sctns))throw new Error('LiveScore response has no sections.');const found=new Map();for(const s of data.Sctns){const stage=s.Ts||s.Comp||s;for(const e of stage.Evs||s.Evs||[]){const home=e.T1?.[0]?.Nm,away=e.T2?.[0]?.Nm,stamp=Number(e.Est);if(!home||!away||!Number.isFinite(stamp)||stamp<=0||e.Spid&&e.Spid!==1)continue;const l=leagueIdentity(stage.CompN||stage.Snm||stage.Csnm||'Football',stage.Cnm||stage.Csnm||''),kickoff=new Date(stamp*1000).toISOString(),eps=String(e.Eps||'NS');let status=/^FT$/i.test(eps)?'finished':/^NS$/i.test(eps)?'scheduled':/^HT$/i.test(eps)||/\d/.test(eps)?'live':'interrupted';const h=e.Tr1==null?null:Number(e.Tr1),a=e.Tr2==null?null:Number(e.Tr2);const score=Number.isInteger(h)&&Number.isInteger(a)&&h>=0&&a>=0&&h<=50&&a<=50?{home:h,away:a}:null;
 const f={id:fixtureKey(home,away,kickoff,l.leagueId),...l,home,away,kickoff,kickoffEAT:eat(kickoff),status,score,liveClock:matchClock(eps,e.Esid===2?'FIRST_HALF':e.Esid===3?'SECOND_HALF':''),halfTimeScore:(status==='finished'||eps==='HT'||e.Esid===3)&&e.Trh1!=null&&e.Trh2!=null?{home:Number(e.Trh1),away:Number(e.Trh2)}:undefined,livePeriod:eps==='HT'?'HALFTIME':eps==='FT'?'FULL_TIME':e.Esid===2?'FIRST_HALF':e.Esid===3?'SECOND_HALF':'',liveCaptured:captured,liveSource:'LiveScore',source:'LiveScore',sourceUrl,sourceUpdated:data.Ts?new Date(data.Ts*1000).toISOString():captured,externalIds:{livescore:String(e.Eid)},resultSource:status==='finished'?'LiveScore':undefined,probabilities:{},models:{},marketModels:[],quotes:[],odds:{}};found.set(f.id,f);}}return [...found.values()];}
export function liveTeamKey(name){const key=modelTeam(name);return key==='chinapr'?'china':key;}
function liveLeagueKey(f){const name=String(f.league||'').toLowerCase().replace(/[^a-z0-9]/g,'');return ['internationalfriendlies','intfriendlygames'].includes(name)?'international-friendlies':name;}
export function sameLiveFixture(a,b){if(!a||!b)return false;const common=Object.entries(a.externalIds||{}).some(([provider,id])=>id&&String(id)===String(b.externalIds?.[provider]));if(common)return true;if(liveTeamKey(a.home)!==liveTeamKey(b.home)||liveTeamKey(a.away)!==liveTeamKey(b.away)||Math.abs(Date.parse(a.kickoff)-Date.parse(b.kickoff))>15*60000)return false;return a.leagueId===b.leagueId||liveLeagueKey(a)===liveLeagueKey(b);}
export function livePatch(f){return Object.fromEntries(['league','leagueId','status','score','halfTimeScore','liveClock','livePeriod','liveCaptured','liveSource','liveStale','sourceUpdated','resultSource','externalIds','goalScorers','eventsCaptured','eventsSource','eventsScore','detailsCoverage','finalConfirmedAt','endedAt','lastPlayClock','detailsCheckedAt','resultCheckedAt'].filter(k=>f[k]!==undefined&&f[k]!==null).map(k=>[k,f[k]]));}
export function normalizeMatchStatus(f,now=Date.now()){
 if(f.status==='finished')return {...f,liveClock:'FT',livePeriod:'FULL_TIME',finalConfirmedAt:f.finalConfirmedAt||f.liveCaptured,liveStale:false};
 if(f.status==='live'&&now-Date.parse(f.kickoff)>3*3600000&&(!f.liveCaptured||now-Date.parse(f.liveCaptured)>90000))return {...f,status:'awaiting-result',liveClock:'Awaiting FT',liveStale:true};
 if(f.status==='scheduled'&&now-Date.parse(f.kickoff)>3*3600000)return {...f,status:'awaiting-result',liveClock:'Status unconfirmed',liveStale:true};
 return f;
}
export function newerLive(prior,next){
 if(!prior)return normalizeMatchStatus(next);
 const patch=livePatch(next),sameScore=prior.score&&next.score&&prior.score.home===next.score.home&&prior.score.away===next.score.away;
 // A final score is immutable in the live stream. Post-match events can hydrate
 // once, only when the provider corroborates the recorded result.
 if(prior.status==='finished'||prior.resultSource==='Owner-entered'){
  const eventPatch=sameScore?Object.fromEntries(['goalScorers','eventsCaptured','eventsSource','eventsScore','detailsCoverage','detailsCheckedAt'].filter(k=>patch[k]!==undefined&&(k==='detailsCheckedAt'||!prior.eventsCaptured||Date.parse(next.eventsCaptured)>=Date.parse(prior.eventsCaptured))).map(k=>[k,patch[k]])):{};
  return {...normalizeMatchStatus(prior),...eventPatch,externalIds:{...prior.externalIds,...next.externalIds}};
 }
 if(prior.status==='live'&&next.status==='scheduled')return prior;
 const oldTime=Date.parse(prior.liveCaptured)||0,newTime=Date.parse(next.liveCaptured)||0;
 if(oldTime>newTime&&!(next.status==='finished'&&prior.status!=='finished'))return prior;
 const preferScore=next.liveSource==='BetPawa Uganda'&&prior.liveSource==='LiveScore'&&!prior.liveStale&&Date.now()-oldTime<10000&&prior.status==='live';
 if(preferScore)for(const key of ['status','score','halfTimeScore','liveClock','livePeriod','liveCaptured','liveSource','liveStale','sourceUpdated','resultSource'])if(prior[key]!==undefined)patch[key]=prior[key];
 const merged={...prior,...patch,score:preferScore?prior.score:next.score??prior.score,...(next.goalScorers===undefined?{goalScorers:prior.goalScorers,eventsCaptured:prior.eventsCaptured,eventsSource:prior.eventsSource,eventsScore:prior.eventsScore}:{}),externalIds:{...prior.externalIds,...next.externalIds}};
 if(merged.status==='finished'){merged.finalConfirmedAt=next.finalConfirmedAt||next.liveCaptured;merged.lastPlayClock=prior.liveClock;merged.liveClock='FT';merged.livePeriod='FULL_TIME';merged.liveStale=false;}
 return merged;
}
export function applyLiveUpdates(existing,updates){
 const out=existing.map(f=>({...f})),ids=new Map(),teams=new Map(),external=new Map();
 const teamPair=f=>liveTeamKey(f.home)+'|'+liveTeamKey(f.away);
 const addIndex=(f,i)=>{ids.set(f.id,i);const key=teamPair(f);if(!teams.has(key))teams.set(key,new Set());teams.get(key).add(i);for(const [source,id]of Object.entries(f.externalIds||{})){if(!id)continue;const key=source+':'+id;if(!external.has(key))external.set(key,new Set());external.get(key).add(i);}};
 out.forEach(addIndex);
 for(const update of updates){const indices=new Set(teams.get(teamPair(update))||[]);if(ids.has(update.id))indices.add(ids.get(update.id));for(const [source,id]of Object.entries(update.externalIds||{}))for(const i of external.get(source+':'+id)||[])indices.add(i);
 const matches=[...indices].filter(i=>out[i].id===update.id||sameLiveFixture(out[i],update));if(!matches.length){out.push(update);addIndex(update,out.length-1);continue;}
 const primary=matches.find(i=>out[i].id===update.id&&!out[i].duplicateOf)??[...matches].sort((a,b)=>Number(!!out[a].duplicateOf)-Number(!!out[b].duplicateOf)||(Date.parse(out[b].liveCaptured)||0)-(Date.parse(out[a].liveCaptured)||0))[0];
 for(const i of matches){const record=out[i],next=newerLive(record,{...update,id:record.id});if(next===record)continue;out[i]={...next,quotes:update.quoteRefresh?update.quotes:update.quotes?.length?update.quotes:record.quotes,duplicateOf:i===primary?undefined:out[primary].id,sourceUrls:[...new Set([...(record.sourceUrls||[]),update.sourceUrl].filter(Boolean))]};addIndex(out[i],i);}}
 for(const indices of external.values()){if(indices.size<2)continue;const group=[...indices].map(i=>out[i]).sort((a,b)=>Number(!!a.duplicateOf)-Number(!!b.duplicateOf)||(Date.parse(b.liveCaptured)||0)-(Date.parse(a.liveCaptured)||0));for(const f of group)if(f.id!==group[0].id)f.duplicateOf=group[0].id;}return out;
}
export function isCurrentLive(f,now=Date.now()){return f.status==='live'&&Date.parse(f.kickoff)<=now+15*60000&&now-Date.parse(f.kickoff)<4*3600000&&Number.isFinite(Date.parse(f.liveCaptured))&&now-Date.parse(f.liveCaptured)<45000;}
export function filterFixtureWindow(fixtures,range,window,day,now=Date.now()){return fixtures.filter(f=>!f.duplicateOf&&(range==='live'?isCurrentLive(f,now):day(f.kickoff)>=window.from&&day(f.kickoff)<=window.to&&(range!=='upcoming'||Date.parse(f.kickoff)>now||isCurrentLive(f,now))));}
export function activeTicketIds(fixtures,tickets,now=Date.now()){const map=new Map(fixtures.map(f=>[f.id,f]));return new Set(tickets.filter(t=>t.status==='pending'||t.status==='lost').flatMap(t=>t.legs.filter(l=>{const f=map.get(l.fixtureId);return !f||f.status!=='finished'&&now-Date.parse(f.kickoff)<30*86400000;}).map(l=>l.fixtureId)));}
export function trackedFixtureDays(fixtures,tickets,now=Date.now()){const ids=activeTicketIds(fixtures,tickets,now);return [...new Set(fixtures.filter(f=>ids.has(f.id)&&Date.parse(f.kickoff)<=now&&now-Date.parse(f.kickoff)<30*86400000).sort((a,b)=>a.kickoff.localeCompare(b.kickoff)).map(f=>f.kickoff.slice(0,10)))].slice(-8);}
export function ticketTotals(legs,stake){if(!Array.isArray(legs)||legs.length<1||legs.length>10||new Set(legs.map(l=>l.fixtureId)).size!==legs.length)throw new Error('Choose 1–10 picks, one per fixture.');if(!Number.isFinite(stake)||stake<=0||stake>1e9||legs.some(l=>!Number.isFinite(l.odds)||l.odds<=1||l.odds>1000))throw new Error('Valid decimal prices and a positive stake are required.');const odds=legs.reduce((n,l)=>n*l.odds,1),hasModels=legs.every(l=>Number.isFinite(l.probability)&&l.probability>0&&l.probability<1&&!l.inPlay);const probability=hasModels?legs.reduce((n,l)=>n*l.probability,1):null;if(!Number.isFinite(odds*stake))throw new Error('Ticket return is too large.');return {odds,stake,potentialReturn:odds*stake,probability,expectedReturn:probability==null?null:probability*odds-1};}
export function ticketProgress(ticket,fixtures){const index=new Map(fixtures.map(f=>[f.id,f]));return ticket.legs.map(l=>{let f=index.get(l.fixtureId);if(f?.duplicateOf)f=newerLive(f,index.get(f.duplicateOf)||f);const alternatives=fixtures.filter(other=>sameLiveFixture(f||l,other)&&other.liveCaptured);for(const other of alternatives)f=newerLive(f,other);f=f?normalizeMatchStatus(f):f;return {...l,kickoff:f?.kickoff||l.kickoff,legOutcome:f?settlePrediction({...l,outcome:'pending'},f):'pending',fixtureStatus:f?.status||'unavailable',liveClock:f?.liveClock,livePeriod:f?.livePeriod,score:f?.score,halfTimeScore:f?.halfTimeScore,liveCaptured:f?.liveCaptured,liveSource:f?.liveSource,liveStale:f?.liveStale,goalScorers:f?.goalScorers,eventsCaptured:f?.eventsCaptured,eventsSource:f?.eventsSource,eventsScore:f?.eventsScore,detailsCoverage:f?.detailsCoverage,finalConfirmedAt:f?.finalConfirmedAt,endedAt:f?.endedAt,lastPlayClock:f?.lastPlayClock};});}
export function eligibleQuotes(fixtures){return fixtures.flatMap(f=>(f.quotes||[]).filter(q=>!q.stale&&q.period==='FT'&&((f.status==='live'&&q.inPlay&&Date.now()-Date.parse(q.captured)<30000)||(f.status==='scheduled'&&Date.parse(f.kickoff)>Date.now()&&!q.inPlay&&Date.now()-Date.parse(q.captured)<(q.source==='Owner-entered'?86400000:120000)))).map(q=>({id:JSON.stringify([f.id,q.bookmakerId||q.bookmaker,q.market,q.selection,q.line??null,q.captured]),fixtureId:f.id,home:f.home,away:f.away,league:f.league,leagueId:f.leagueId,kickoff:f.kickoff,...q,kind:'quote',probability:null,fixtureStatus:f.status,liveClock:f.liveClock,score:f.score,oddsCaptured:q.captured,outcome:'pending'})));}

export function mergeLiveState(previous,update){if(!previous)return null;const byId=new Map(previous.fixtures.map(f=>[f.id,{...f}]));for(const f of update.liveFixtures||[])byId.set(f.id,newerLive(byId.get(f.id),{probabilities:{},models:{},marketModels:[],quotes:[],odds:{},...byId.get(f.id),...f}));for(const f of byId.values()){if(f.status==='live'){f.quotes=(update.liveSelections||[]).filter(q=>q.fixtureId===f.id);f.odds=Object.fromEntries(f.quotes.filter(q=>q.market==='1X2').map(q=>[q.selection,q.odds]));}}let fixtures=applyLiveUpdates([...byId.values()],[]).filter(f=>!f.duplicateOf).sort((a,b)=>a.kickoff.localeCompare(b.kickoff));if(update.range?.liveOnly){const currentIds=new Set((update.liveFixtures||[]).map(f=>f.id));fixtures=fixtures.filter(f=>currentIds.has(f.id)&&isCurrentLive(f));}const tickets=(update.tickets||previous.tickets||[]).map(t=>{const prior=previous.tickets?.find(p=>p.id===t.id);if(!prior)return t;const progress=(t.progress||[]).map(l=>{const old=prior.progress?.find(p=>p.fixtureId===l.fixtureId);return newerTicketProgress(old,l);});return {...t,progress};});return {...previous,fixtures,eligibleSelections:[...(previous.eligibleSelections||[]).filter(q=>!q.inPlay&&(byId.get(q.fixtureId)?.status==='scheduled')&&Date.parse(q.kickoff)>Date.now()&&Date.now()-Date.parse(q.captured||q.oddsCaptured)<(q.source==='Owner-entered'?86400000:120000)),...(update.liveSelections||[])],tickets,sources:[...new Map([...(previous.sources||[]),...(update.sources||[])].map(s=>[s.name,s])).values()],liveUpdated:update.liveUpdated,liveConnection:update.connection||previous.liveConnection,allPicks:(previous.allPicks||[]).filter(p=>byId.get(p.fixtureId)?.status==='scheduled'),picks:(previous.picks||[]).filter(p=>byId.get(p.fixtureId)?.status==='scheduled')};}
export function mergeFreshState(previous,next){if(!previous)return {...next,sources:[...new Map((next.sources||[]).map(s=>[s.name,s])).values()]};const window=next.range;const liveFixtures=previous.fixtures.filter(f=>f.liveCaptured&&(window?.liveOnly?f.status==='live':!window||Date.parse(f.kickoff)>=Date.parse(window.from+'T00:00:00+03:00')&&Date.parse(f.kickoff)<=Date.parse(window.to+'T23:59:59+03:00')));return mergeLiveState(next,{liveFixtures,liveSelections:(previous.eligibleSelections||[]).filter(q=>q.inPlay),tickets:(next.tickets||[]).map(t=>{const old=previous.tickets?.find(p=>p.id===t.id);return {...t,progress:(t.progress||[]).map(l=>{const prior=old?.progress?.find(p=>p.fixtureId===l.fixtureId);return newerTicketProgress(prior,l);})};}),liveUpdated:Date.parse(previous.liveUpdated)>Date.parse(next.liveUpdated||0)?previous.liveUpdated:next.liveUpdated,sources:(next.sources||[]).filter(s=>['LiveScore','BetPawa live'].includes(s.name)),range:window});}

export function newerTicketProgress(prior,next){if(!prior)return next;if(prior.fixtureStatus==='finished'&&next.fixtureStatus!=='finished')return prior;if(next.fixtureStatus==='finished'&&prior.fixtureStatus!=='finished')return next;return Date.parse(prior.liveCaptured)>Date.parse(next.liveCaptured||0)?prior:next;}
