import {modelTeam} from './arata-model.mjs';
import {playerKey} from './squad-data.mjs';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mean=a=>a.reduce((n,v)=>n+v,0)/Math.max(1,a.length);
export function ridgeFit(samples,penalty=15){
 const keys=[...new Set(samples.flatMap(s=>Object.keys(s.features)))].filter(k=>{const values=samples.map(s=>s.features[k]||0);return k==='rest'?Math.max(...values)-Math.min(...values)>.25:values.filter(v=>v===1).length>=6&&values.filter(v=>v===0).length>=6;});
 const means=Object.fromEntries(keys.map(k=>[k,mean(samples.map(s=>s.features[k]||0))])),beta=Object.fromEntries(keys.map(k=>[k,0]));
 const residual=samples.map(s=>s.target),x=samples.map(s=>keys.map(k=>(s.features[k]||0)-means[k]));
 for(let step=0;step<150;step++){let delta=0;for(let j=0;j<keys.length;j++){const key=keys[j],old=beta[key];let numerator=0,denominator=penalty;for(let i=0;i<x.length;i++){numerator+=x[i][j]*(residual[i]+x[i][j]*old);denominator+=x[i][j]**2;}const next=clamp(numerator/denominator,-.2,.2),change=next-old;beta[key]=next;for(let i=0;i<x.length;i++)residual[i]-=x[i][j]*change;delta=Math.max(delta,Math.abs(change));}if(delta<1e-7)break;}
 return {beta,means,penalty,n:samples.length};
}
export function ridgePredict(fit,features){return clamp(Object.entries(fit.beta).reduce((v,[k,b])=>v+b*((features[k]||0)-fit.means[k]),0),-.2,.2);}
export function fitImpact(samples){
 const ordered=[...samples].sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)),n=ordered.length;
 if(n<32)return {enabled:false,n,reason:'At least 32 historical starting XIs with confirmed results are needed.'};
 const split=n-Math.max(8,Math.ceil(n*.25)),train=ordered.slice(0,split),test=ordered.slice(split),fit=ridgeFit(train);
 const baseline=mean(test.map(s=>s.target**2)),adjusted=mean(test.map(s=>(s.target-ridgePredict(fit,s.features))**2)),improvement=baseline>0?(baseline-adjusted)/baseline:0;
 const validation={train:train.length,holdout:test.length,baselineMSE:baseline,adjustedMSE:adjusted,improvement,through:ordered.at(-1).kickoff};
 return {enabled:improvement>=.05&&Object.keys(fit.beta).length>0,n,reason:improvement>=.05?'Passed later-match validation.':'No 5% improvement on later matches; player/rest correction remains inactive.',validation,fit:ridgeFit(ordered)};
}
const restFeature=days=>clamp((Math.min(days,10)-5)/5,-1,1);
const getRest=(matches,team,kickoff)=>{const prior=matches.filter(m=>Date.parse(m.availableAt)<Date.parse(kickoff)&&[modelTeam(m.home),modelTeam(m.away)].includes(team)).at(-1);return prior?clamp((Date.parse(kickoff)-Date.parse(prior.kickoff))/86400000,0,30):null;};
export async function trainEnhancements(events,history,forecast,now=Date.now()){
 const usable=events.filter(m=>m.status==='finished'&&m.score&&m.lineup.status==='historical-confirmed'&&Date.parse(m.availableAt)<now).sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)),observations=[],players={};
 const baselines=new Map();let processed=0;for(const m of usable){if(processed++%8===0)await new Promise(resolve=>setTimeout(resolve,0));const baseline=forecast(m,history,{},Date.parse(m.kickoff));baselines.set(m.id,baseline);if(!baseline.available)continue;for(const side of ['home','away']){const other=side==='home'?'away':'home',team=modelTeam(m[side]),days=getRest(usable,team,m.kickoff);if(days==null)continue;const features={rest:restFeature(days)};for(const p of m.lineup[side]){features[p.id]=1;players[p.id]={id:p.id,name:p.name,team};}observations.push({team,kickoff:m.kickoff,availableAt:m.availableAt,features,base:baseline.expectedGoals[side],opponentBase:baseline.expectedGoals[other],goals:m.score[side],hasXg:!!m.xg,xg:m.xg?.[side]??null,againstXg:m.xg?.[other]??null,attack:Math.log((m.score[side]+.3)/(baseline.expectedGoals[side]+.3)),defence:Math.log((m.score[other]+.3)/(baseline.expectedGoals[other]+.3)),xgAttack:m.xg?Math.log((m.xg[side]+.3)/(baseline.expectedGoals[side]+.3)):0,xgDefence:m.xg?Math.log((m.xg[other]+.3)/(baseline.expectedGoals[other]+.3)):0,sourceUrl:m.sourceUrl});}}
 const teams={};for(const team of new Set(observations.map(o=>o.team))){const rows=observations.filter(o=>o.team===team&&now-Date.parse(o.availableAt)<730*86400000).slice(-40);teams[team]={attack:fitImpact(rows.map(o=>({...o,target:o.attack}))),defence:fitImpact(rows.map(o=>({...o,target:o.defence}))),matches:rows.length,latest:rows.at(-1)?.kickoff};}
 // Tune xG weight on earlier games; inspect its goal likelihood on a separate,
 // later block. Opponent-adjusted residual rates use only preceding events.
 const scored=[];for(const m of usable){const baseline=baselines.get(m.id);if(!baseline.available)continue;const factors=xgFactors(observations,m);if(!factors.available)continue;scored.push({kickoff:m.kickoff,home:m.score.home,away:m.score.away,base:baseline.expectedGoals,factors});}
 const nll=(rows,w)=>mean(rows.map(r=>['home','away'].reduce((n,side)=>{const l=clamp(r.base[side]*Math.exp(w*r.factors[side]),.25,4.5);return n+l-r[side]*Math.log(l);},0)));
 let xg={enabled:false,weight:0,n:scored.length,reason:'At least 60 matches with preceding xG history are required.'};if(scored.length>=60){const split=Math.floor(scored.length*.7),train=scored.slice(0,split),test=scored.slice(split);const weights=[0,.15,.3,.5],weight=weights.reduce((best,w)=>nll(train,w)<nll(train,best)?w:best,0),base=nll(test,0),adjusted=nll(test,weight),gain=base-adjusted;const enabled=weight>0&&gain>.02;xg={enabled,weight:enabled?weight:0,n:scored.length,validation:{train:train.length,holdout:test.length,baselineNLL:base,adjustedNLL:adjusted,gain},reason:enabled?'Passed later-match goal-likelihood validation.':'No material later-match improvement; xG remains visible research context.'};}
 return {version:'arata-impact-ridge-v1',created:new Date(now).toISOString(),through:usable.at(-1)?.availableAt,events:usable.filter(m=>m.xg).length,lineupMatches:usable.filter(m=>!m.xg).length,teams,players,xg,observations,note:'Regularized associations, not causal injury estimates. Later-match retrospective checks are separate from prospective predictor accuracy.'};
}
export function xgFactors(observations,fixture,cutoff=Date.parse(fixture.kickoff)){
 const past=observations.filter(o=>o.hasXg&&Date.parse(o.availableAt)<cutoff&&cutoff-Date.parse(o.availableAt)<180*86400000),home=past.filter(o=>o.team===modelTeam(fixture.home)).slice(-20),away=past.filter(o=>o.team===modelTeam(fixture.away)).slice(-20);if(home.length<8||away.length<8)return {available:false,home:0,away:0,homeMatches:home.length,awayMatches:away.length};const rate=(rows,key)=>rows.reduce((v,o)=>v+o[key],0)/(rows.length+8);return {available:true,home:clamp((rate(home,'xgAttack')+rate(away,'xgDefence'))/2,-.4,.4),away:clamp((rate(away,'xgAttack')+rate(home,'xgDefence'))/2,-.4,.4),homeMatches:home.length,awayMatches:away.length};
}
export function squadAdjustment(team,model,lineup,squad,absences,restDays){
 const candidate=model?.teams?.[modelTeam(team)],detail=candidate&&Date.now()-Date.parse(candidate.latest)<180*86400000?candidate:null,changes=[],fits={attack:detail?.attack,defence:detail?.defence},out=new Set((absences||[]).filter(p=>p.verified&&p.status==='out').map(p=>playerKey(p.name))),roster=new Map((squad?.players||[]).map(p=>[p.id,p]));let attack=0,defence=0;
 for(const [kind,f]of Object.entries(fits)){if(!f?.enabled||!f.fit)continue;let effect=0;const restBeta=f.fit.beta.rest||0;if(restBeta&&Number.isFinite(restDays)&&Number.isFinite(f.fit.means.rest))effect+=restBeta*(restFeature(restDays)-f.fit.means.rest);
 if(lineup?.length===11){const starters=new Set(lineup.map(p=>p.id));if(lineup.some(p=>out.has(playerKey(p.name))))return {attack:0,defence:0,changes:[],reason:'Confirmed XI conflicts with the current official absence report; correction withheld.'};for(const [id,b]of Object.entries(f.fit.beta)){if(id==='rest')continue;effect+=b*((starters.has(id)?1:0)-f.fit.means[id]);}}
 else for(const [id,b]of Object.entries(f.fit.beta)){if(id==='rest')continue;const p=roster.get(id)||model.players[id];if(p&&out.has(playerKey(p.name))){const change=-b*f.fit.means[id];effect+=change;changes.push({name:p.name,kind,logEffect:change,appearances:Math.round(f.fit.means[id]*f.n)});}}
 if(kind==='attack')attack=clamp(effect,-.2,.2);else defence=clamp(effect,-.2,.2);}
 return {attack,defence,changes,reason:!detail?'No historical player model for this team.':!fits.attack?.enabled&&!fits.defence?.enabled?'Player/rest adjustments did not pass validation or lack sufficient history.':'Validated adjustments; goal-rate change capped at approximately 22%.',learnedPlayers:detail?[...new Set([...Object.keys(fits.attack?.fit?.beta||{}),...Object.keys(fits.defence?.fit?.beta||{})])].filter(id=>id!=='rest').map(id=>({id,name:roster.get(id)?.name||model.players[id]?.name||id,attack:fits.attack?.fit?.beta[id]||0,defence:fits.defence?.fit?.beta[id]||0,starts:Math.round((fits.attack?.fit?.means[id]||fits.defence?.fit?.means[id]||0)*detail.matches)})):[],validation:detail?{attack:fits.attack?.validation,defence:fits.defence?.validation}:null,n:detail?.matches||0};
}
export function enhanceForecast(base,fixture,context,now=Date.now()){
 const trained=context.trained,cutoff=Math.min(now,Date.parse(fixture.kickoff));if(!base.available||!trained)return {expectedGoals:base.expectedGoals,evidence:{status:'warming',note:'Event and squad research is warming; goals, form, venue and H2H remain the fallback.'}};
 if(Date.parse(trained.through)>=cutoff)return {expectedGoals:base.expectedGoals,evidence:{status:'rejected',note:'Training includes results unavailable at forecast time.'}};
 const factors=xgFactors(trained.observations,fixture,cutoff),adjustments={};for(const side of ['home','away']){const team=fixture[side],c=context[side]||{};const currentLineup=c.match?.status==='scheduled'&&c.match.lineup.status==='provider-confirmed'&&Date.parse(c.match.captured)<=cutoff&&cutoff-Date.parse(c.match.captured)<120000?c.match.lineup[side]:null;const absences=c.official&&Date.parse(c.official.modified)<=cutoff&&cutoff-Date.parse(c.official.captured)<3600000&&Date.parse(fixture.kickoff)>=Date.parse(c.official.validFrom)&&Date.parse(fixture.kickoff)<Date.parse(c.official.validUntil)?c.official.players:[];adjustments[side]=squadAdjustment(team,trained,currentLineup,c.squad,absences,Date.parse(fixture.kickoff)-now<=2*86400000?(Date.parse(fixture.kickoff)-Date.parse(trained.teams?.[modelTeam(team)]?.latest))/86400000:NaN);}
 const goals={};for(const side of ['home','away']){const other=side==='home'?'away':'home',xg=trained.xg.enabled&&factors.available?trained.xg.weight*factors[side]:0;goals[side]=clamp(base.expectedGoals[side]*Math.exp(clamp(xg+adjustments[side].attack+adjustments[other].defence,-.3,.3)),.25,4.5);}
 const recent=trained.observations.filter(o=>o.hasXg&&Date.parse(o.availableAt)<cutoff&&cutoff-Date.parse(o.availableAt)<180*86400000&&[modelTeam(fixture.home),modelTeam(fixture.away)].includes(o.team)).slice(-12).map(o=>({team:o.team,date:o.kickoff,xg:o.xg,xga:o.againstXg,sourceUrl:o.sourceUrl}));
 return {expectedGoals:goals,evidence:{status:'researched',baselineGoals:base.expectedGoals,trainedThrough:trained.through,eventMatches:trained.events,lineupMatches:trained.lineupMatches,archive:context.archive?{season:context.archive.season,note:context.archive.note,matches:context.archive.matches?.length}:null,xg:{...trained.xg,...factors,recent},adjustments,home:context.home,away:context.away,note:trained.note}};
}
