import {requestState,isHostedRequest} from './background.mjs';
import {BoundedCache} from './bounded-cache.mjs';
import {readPublicResponse} from './network.mjs';
import { LEAGUES,parseBetBetter,parseOpenLiga,mergeFixtures,historicalContext } from './domain.mjs';
import {cachedRead,cachedWrite} from './store';
const memory=new BoundedCache();
function flights():Map<string,Promise<any>>{return requestState('provider-flights',()=>new Map());}
export function requestCache(){return new Map<string,Promise<any>>();}
export async function fetchCached(url:string,ttl:number,memo:Map<string,Promise<any>>,options:{volatile?:boolean;headers?:Record<string,string>;text?:boolean;maxStaleMs?:number;timeoutMs?:number;retries?:number}={}){const key=url+'|'+JSON.stringify(options);if(memo.has(key))return memo.get(key);const promise=(async()=>{const mem=memory.get(key);if(mem&&mem.expires>Date.now())return mem;if(flights().has(key))return flights().get(key);const task=(async()=>{const old=mem||(options.volatile?null:await cachedRead(key));if(old&&old.expires>Date.now()){memory.set(key,old);return old;}try{let response:Response|undefined,data:any;for(let n=0;n<(options.retries??(isHostedRequest()?1:2));n++){try{const result=await readPublicResponse(url,{headers:{Accept:'application/json','User-Agent':'ArataOdds/1.0 (+personal football research)',...options.headers},text:options.text,timeoutMs:options.timeoutMs??(isHostedRequest()?5000:12000)});response=result.response;data=result.data;if(!response)throw new Error('Public source returned no response.');if(response.ok)break;if(response.status<500&&response.status!==429)break;}catch(e){if(n===(options.retries??(isHostedRequest()?1:2))-1)throw e;}}if(!response?.ok)throw new Error(`Feed returned ${response?.status||'no response'}`);if(data.error)throw new Error(String(data.error));const value={data,captured:new Date().toISOString(),stale:false,expires:Date.now()+ttl};memory.set(key,value);if(memory.size>60)memory.delete(memory.keys().next().value!);if(!options.volatile)await cachedWrite(key,value.expires,value);return value;}catch(e){if(old&&Date.now()-Date.parse(old.captured)<(options.maxStaleMs??86400000))return {...old,stale:true,error:e instanceof Error?e.message:'Feed unavailable'};throw e;}})();flights().set(key,task);try{return await task;}finally{flights().delete(key);}})();memo.set(key,promise);return promise;}
export async function ingest(){const memo=requestCache();const statuses:any[]=[];const models:any[]=[];const history:any[]=[];const year=new Date().getUTCFullYear()-(new Date().getUTCMonth()<6?1:0);
 await Promise.all([Promise.all(LEAGUES.map(async(l:any)=>{try{const r=await fetchCached(`https://betbetter.world/soccer/${l.id}/picks?format=json`,900000,memo,{timeoutMs:6000,retries:1});const fs=parseBetBetter(r.data,l);models.push(...fs.map((f:any)=>({...f,modelStale:r.stale,modelCaptured:r.captured})));statuses.push({name:`Bet Better · ${l.name}`,status:r.stale?'cached':'connected',count:fs.length,captured:r.captured,stale:r.stale});}catch(e){statuses.push({name:`Bet Better · ${l.name}`,status:'unavailable',message:(e as Error).message});}})),
Promise.all(LEAGUES.filter((l:any)=>l.open).map(async(l:any)=>{try{const r=await fetchCached(`https://api.openligadb.de/getmatchdata/${l.open}/${year}`,900000,memo);const fs=parseOpenLiga(r.data,l);history.push(...fs);statuses.push({name:`OpenLigaDB · ${l.name}`,status:r.stale?'cached':'connected',count:fs.length,captured:r.captured,stale:r.stale});}catch(e){statuses.push({name:`OpenLigaDB · ${l.name}`,status:'unavailable',message:(e as Error).message});}}))]);
 const fixtures=mergeFixtures(history,models);return {fixtures,statuses,history};}
export async function details(f:any){const league=LEAGUES.find((l:any)=>l.id===f.leagueId);if(!league?.open)return {h2h:[],homeForm:[],awayForm:[],message:'Historical coverage is unavailable for this league in the free feed.'};const season=new Date(f.kickoff).getUTCFullYear()-(new Date(f.kickoff).getUTCMonth()<6?1:0);const memo=requestCache();const results=await Promise.allSettled([season,season-1,season-2].map(async(y)=>{const r=await fetchCached(`https://api.openligadb.de/getmatchdata/${league.open}/${y}`,y===season?900000:86400000,memo);return parseOpenLiga(r.data,league);}));const history=results.flatMap(r=>r.status==='fulfilled'?r.value:[]);return {...historicalContext(f,history),message:results.some(r=>r.status==='rejected')?'Some historical seasons are unavailable.':null,source:'OpenLigaDB'};}
// Requested João Brito actor deliberately disabled: the owner requires no API keys or paid requests.
export const flashscoreContract={actor:'joaobrito/flashscore-sports-data-api',fixtures:{mode:'matchesByDate',sports:['football']},details:{mode:'matchDetails',include:{h2h:true}},enabled:false,reason:'Requires an Apify token and paid actor runs.'};
export async function publicRecord(){return fetchCached('https://betbetter.world/results?format=json',900000,requestCache());}

