import {isHostedRequest} from './background.mjs';
import {fetchCached,requestCache} from './providers';
import {parseHistoricalCsv,modelTeam} from './arata-model.mjs';
import {historicalResultRows,saveHistoricalResults} from './store';
import {historicalKey} from './historical-archive.mjs';
const codes:Record<string,string>={epl:'E0',bundesliga:'D1','la-liga':'SP1','serie-a':'I1','ligue-1':'F1'};
const newsCodes:Record<string,string>={epl:'eng.1',bundesliga:'ger.1','la-liga':'esp.1','serie-a':'ita.1','ligue-1':'fra.1',mls:'usa.1'};
export async function researchHistory(leagueId:string){const memo=requestCache(),year=new Date().getUTCFullYear()-(new Date().getUTCMonth()<6?1:0),code=codes[leagueId];if(!code&&leagueId!=='mls')return {history:[],stale:true,status:'unavailable',message:'No verified historical feed for this league.'};const urls=leagueId==='mls'?['https://www.football-data.co.uk/new/USA.csv']:[year,year-1,year-2].map(y=>`https://www.football-data.co.uk/mmz4281/${String(y).slice(-2)}${String(y+1).slice(-2)}/${code}.csv`);
 const archived=await historicalResultRows(leagueId),history:any[]=[],errors:string[]=[],captured:string[]= [];let stale=false;
 // Respect the free publisher: bounded, sequential downloads with persistent cache.
 await Promise.all(urls.map(async(url,i)=>{try{const r:any=await fetchCached(url,i===0?21600000:604800000,memo,{text:true,headers:{Accept:'text/csv'},maxStaleMs:7*86400000,retries:1,timeoutMs:isHostedRequest()?4000:12000});const parsed=parseHistoricalCsv(r.data,leagueId,url);if(!parsed.length)throw new Error('No valid settled historical rows.');history.push(...parsed);stale ||= r.stale;captured.push(r.captured);}catch(e){errors.push((e as Error).message);}}));
 const existing=new Set(archived.map(historicalKey));await saveHistoricalResults(history.filter(m=>!existing.has(historicalKey(m))&&Date.parse(m.kickoff)>Date.now()-730*86400000));const merged=[...new Map([...archived,...history].map(m=>[historicalKey(m),m])).values()];
 return {history:merged,stale:stale||!history.length,captured:captured.sort()[0]||null,status:merged.length?(history.length?(stale?'cached':errors.length?'partial':'connected'):'cached'):'unavailable',message:errors.join('; ')||(!history.length&&archived.length?'Using imported verified results while public feed is unavailable.':null)};
}
export async function availabilityNews(leagueId:string){if(!newsCodes[leagueId])return {articles:[],status:'unknown',captured:null};try{const r:any=await fetchCached(`https://site.api.espn.com/apis/site/v2/sports/soccer/${newsCodes[leagueId]}/news?limit=50`,1800000,requestCache(),{maxStaleMs:3600000,retries:1});return {articles:r.data.articles||[],status:r.stale?'stale':'headlines-only',captured:r.captured};}catch{return {articles:[],status:'unknown',captured:null};}}
export function teamAvailability(f:any,feed:any){const teams=[f.home,f.away];const reports=(feed.articles||[]).filter((a:any)=>{const headline=String(a.headline||'');return /injur|ruled out|fitness|suspens|hamstring|ankle|knee|return|doubt/i.test(headline)&&teams.some(t=>{const key=modelTeam(t),words=t.toLowerCase().split(/\W+/).filter((w:string)=>w.length>3&&!['united','city','football','club'].includes(w));return modelTeam(headline).includes(key)||words.length>0&&words.every((w:string)=>headline.toLowerCase().includes(w));})&&Number.isFinite(Date.parse(a.published))&&Date.parse(a.published)<=Date.now()&&Date.now()-Date.parse(a.published)<7*86400000;}).map((a:any)=>({headline:String(a.headline).split(/\s+/).slice(0,24).join(' '),published:a.published,url:a.links?.web?.href||'https://www.espn.com/soccer/',source:'ESPN',verified:false}));return {status:reports.length?'news-mentions':'unknown',reports,captured:feed.captured,note:'Headlines are availability context, not a verified squad list. No player absence or injury adjustment is inferred. Check linked team news before betting.'};}
