import {modelTeam} from './arata-model.mjs';
export const playerKey=name=>String(name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
export function nextPage(html){const raw=String(html).match(/<script[^>]*id="__NEXT_DATA__"[^>]*>([\s\S]*?)<\/script>/)?.[1];if(!raw)throw new Error('Public page has no structured research data.');return JSON.parse(raw).props.pageProps;}
const player=p=>({id:String(p.id),name:p.name,position:p.usualPlayingPositionId??p.positionId});
export function parseEventMatch(page,expectedId,leagueId,captured=new Date().toISOString()){
 const g=page.general,s=page.header?.status;if(!g||String(g.matchId)!==String(expectedId))throw new Error('Historical match identity mismatch.');
 const kickoff=g.matchTimeUTCDate,now=Date.parse(captured),time=Date.parse(kickoff),status=s?.cancelled?'cancelled':g.finished?'finished':g.started?'live':'scheduled';
 if(!Number.isFinite(time)||!Number.isFinite(now)||g.finished&&time+3*3600000>now||g.started&&time>now)throw new Error('Source timing is inconsistent; post-match information rejected.');
 const scoreParts=String(s?.scoreStr||'').match(/^(\d+)\s*-\s*(\d+)$/),lineup=page.content?.lineup,shots=page.content?.shotmap?.shots;
 const result={id:String(expectedId),leagueId,providerLeagueId:g.parentLeagueId||g.leagueId,home:g.homeTeam.name,away:g.awayTeam.name,homeId:String(g.homeTeam.id),awayId:String(g.awayTeam.id),kickoff,availableAt:new Date(time+3*3600000).toISOString(),status,score:scoreParts?{home:Number(scoreParts[1]),away:Number(scoreParts[2])}:null,source:'FotMob public match page',sourceUrl:`https://www.fotmob.com/match/${expectedId}`,captured,lineup:{status:'unknown',home:[],away:[]},unavailable:{home:[],away:[]},shots:[],xg:null};
 // A predicted XI is never described as confirmed. Even a standard XI is usable
 // pre-match only in the announcement window; later forecasts may not use it.
 const confirmed=lineup?.lineupType==='standard'&&['homeTeam','awayTeam'].every(k=>lineup[k]?.starters?.length===11&&new Set(lineup[k].starters.map(p=>String(p.id))).size===11);
 if(confirmed&&(status!=='scheduled'||time-now<=120*60000&&time>now)){result.lineup={status:status==='finished'?'historical-confirmed':'provider-confirmed',home:lineup.homeTeam.starters.map(player),away:lineup.awayTeam.starters.map(player),source:lineup.source||'FotMob'};}
 for(const side of ['home','away'])result.unavailable[side]=(lineup?.[side+'Team']?.unavailable||[]).map(p=>({...player(p),status:'reported-unavailable',reason:p.unavailability?.type,expectedReturn:p.unavailability?.expectedReturn||null,verified:false}));
 if(status==='finished'&&s?.reason?.short==='FT'&&!s?.awarded&&Array.isArray(shots)&&shots.length){const valid=shots.filter(p=>['FirstHalf','SecondHalf'].includes(p.period)&&!p.isOwnGoal);if(valid.length&&valid.every(p=>Number.isFinite(p.expectedGoals)&&p.expectedGoals>=0&&p.expectedGoals<=1&&[result.homeId,result.awayId].includes(String(p.teamId)))){result.shots=valid.map(p=>({id:String(p.id),teamId:String(p.teamId),playerId:String(p.playerId),playerName:p.playerName,minute:p.min,added:p.minAdded||0,xg:p.expectedGoals,goal:p.eventType==='Goal',period:p.period}));result.xg={home:result.shots.filter(p=>p.teamId===result.homeId).reduce((v,p)=>v+p.xg,0),away:result.shots.filter(p=>p.teamId===result.awayId).reduce((v,p)=>v+p.xg,0),events:result.shots.length};}}
 return result;
}
export function parseLeague(page,leagueId,providerId){if(Number(page.details?.id)!==providerId)throw new Error('League identity mismatch.');return {leagueId,providerId,season:page.details.selectedSeason,matches:(page.fixtures?.allMatches||[]).map(m=>({id:String(m.id),home:m.home.name,away:m.away.name,homeId:String(m.home.id),awayId:String(m.away.id),kickoff:m.status.utcTime,finished:m.status.finished===true,cancelled:m.status.cancelled===true}))};}
export function parseSquad(page,teamId,captured){const d=page.fallback?.['team-'+teamId];if(String(d?.details?.id)!==String(teamId))throw new Error('Squad identity mismatch.');return {teamId:String(teamId),team:d.details.name,captured,sourceUrl:`https://www.fotmob.com/teams/${teamId}/overview`,status:'published-roster',players:(d.squad?.squad||[]).filter(g=>g.title!=='coach').flatMap(g=>g.members||[]).map(p=>({...player(p),position:p.role?.fallback||p.positionId,injury:p.injury?{...p.injury}:null})),note:'Published squad, not proof of registration or fitness. Missing injury entries do not establish availability.'};}
function decode(s){return s.replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&(?:amp|nbsp|quot|apos|lt|gt);/g,x=>({'&amp;':'&','&nbsp;':' ','&quot;':'"','&apos;':"'",'&lt;':'<','&gt;':'>'}[x]));}
export function parseOfficialAvailability(html,url,captured=new Date().toISOString()){
 const published=html.match(/datePublished\\?"\s*:\s*\\?"([^"\\]+)/)?.[1],modified=html.match(/dateModified\\?"\s*:\s*\\?"([^"\\]+)/)?.[1]||published,now=Date.parse(captured);
 if(!published||!Number.isFinite(Date.parse(modified))||Date.parse(modified)>now||now-Date.parse(modified)>7*86400000)throw new Error('Official report has no current, valid publication time.');
 const article=html.match(/<article\b[^>]*>[\s\S]*?<\/article>/i)?.[0];if(!article)throw new Error('Official report article unavailable.');
 const text=decode(article.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<[^>]+>/g,'\n')),lines=text.split(/\n/).map(s=>s.trim()).filter(Boolean),teams=[];let team=null;
 for(const line of lines){const entry=line.match(/^(.+?)\s*[-–]\s*(.*?)\s*\((Out|Questionable)\)$/i);if(entry&&team){team.players.push({name:entry[1].trim(),status:entry[3].toLowerCase(),reason:entry[2].trim(),verified:true,source:'MLS official player status report',sourceUrl:url,published,modified});continue;}if(/^(?:Sunday|Saturday|Friday|Wednesday|Tuesday|Thursday|Monday),/.test(line)||/Report|Communications|Share|Copy URL|HERE|available|Related/.test(line))continue;if(/^(?:Columbus Crew|Inter Miami CF|Atlanta United|Austin FC|Charlotte FC|Chicago Fire FC|FC Cincinnati|Colorado Rapids|FC Dallas|D\.?C\.? United|Houston Dynamo FC|Sporting Kansas City|LA Galaxy|Los Angeles Football Club|Minnesota United FC|CF Montréal|Nashville SC|New England Revolution|Red Bull New York|New York City FC|Orlando City SC|Philadelphia Union|Portland Timbers|Real Salt Lake|San Diego FC|San Jose Earthquakes|Seattle Sounders FC|St\. Louis CITY SC|Toronto FC|Vancouver Whitecaps FC)$/.test(line)){team={team:line,players:[]};teams.push(team);}}
 if(teams.length<20)throw new Error('Official report coverage incomplete.');
 const heading=decode(html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1]||lines.find(s=>s.startsWith('MLS Player Status Report:'))||''),dates=[...heading.matchAll(/(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})/g)].map(m=>Date.parse(`${m[1]} ${m[2]}, ${new Date(published).getUTCFullYear()} 00:00:00 GMT`));
 return {source:'MLS official player status report',url,published,modified,captured,validFrom:dates.length?new Date(Math.min(...dates)).toISOString():published,validUntil:dates.length?new Date(Math.max(...dates)+2*86400000).toISOString():new Date(Date.parse(published)+3*86400000).toISOString(),teams,status:'official-listed-absences',note:'Covers the listed matchday; OUT is confirmed by the league report. Questionable is not an absence. Unlisted players are not certified fit.'};
}
export function matchingResearch(f,league){return league.matches.find(m=>modelTeam(m.home)===modelTeam(f.home)&&modelTeam(m.away)===modelTeam(f.away)&&Math.abs(Date.parse(m.kickoff)-Date.parse(f.kickoff))<=15*60000);}
