import {requestState} from './background.mjs';
import {clientPayloadJson} from './transport.mjs';
import { env } from 'cloudflare:workers';
export function db(){if(!env.DB)throw new Error('Persistent storage is unavailable.');return env.DB;}
export async function rows(table:string){if(!['fixtures','predictions','tickets','odds_snapshots'].includes(table))throw new Error('Invalid table');const result=await db().prepare(`SELECT * FROM ${table}`).all();return result.results.map((r:any)=>({...JSON.parse(r.payload),...(r.outcome?{outcome:r.outcome}:{}),...(r.status?{status:r.status}:{})}));}
export async function saveFixtures(fixtures:any[]){const now=new Date().toISOString();for(let i=0;i<fixtures.length;i+=80)await db().batch(fixtures.slice(i,i+80).map(f=>db().prepare('INSERT INTO fixtures(id,kickoff,payload,updated) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET kickoff=excluded.kickoff,payload=excluded.payload,updated=excluded.updated').bind(f.id,f.kickoff,clientPayloadJson(f),now)));}
function headState():{ready?:Promise<void>}{return requestState('prediction-head-init',()=>({}));}
async function ensurePredictionHeads(){if(headState().ready)return headState().ready;headState().ready=(async()=>{const ready=await cachedRead('prediction-heads:v1:ready');if(ready?.data)return;await db().prepare(`INSERT INTO prediction_heads(fixture_id,predictor,market,selection,line_key,prediction_id,created) SELECT fixture_id,predictor,market,selection,line_key,id,created FROM (SELECT p.fixture_id,coalesce(json_extract(p.payload,'$.predictor'),'betbetter') AS predictor,coalesce(json_extract(p.payload,'$.market'),'1X2') AS market,json_extract(p.payload,'$.selection') AS selection,coalesce(json_extract(p.payload,'$.line'),'') AS line_key,p.id,p.created,ROW_NUMBER() OVER(PARTITION BY p.fixture_id,coalesce(json_extract(p.payload,'$.predictor'),'betbetter'),coalesce(json_extract(p.payload,'$.market'),'1X2'),json_extract(p.payload,'$.selection'),coalesce(json_extract(p.payload,'$.line'),'') ORDER BY p.created DESC,p.id DESC) AS position FROM predictions p JOIN fixtures f ON f.id=p.fixture_id WHERE p.created<f.kickoff) ranked WHERE position=1 ON CONFLICT(fixture_id,predictor,market,selection,line_key) DO NOTHING`).run();await cachedWrite('prediction-heads:v1:ready',Number.MAX_SAFE_INTEGER,{data:true});})();try{await headState().ready;}catch(e){headState().ready=undefined;throw e;}}
export async function savePredictions(predictions:any[]){await ensurePredictionHeads();for(let i=0;i<predictions.length;i+=40){const commands:any[]=[];for(const p of predictions.slice(i,i+40)){commands.push(db().prepare('INSERT INTO predictions(id,fixture_id,created,outcome,payload) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(p.id,p.fixtureId,p.created,p.outcome,clientPayloadJson(p)));if(Date.parse(p.created)<Date.parse(p.kickoff))commands.push(db().prepare('INSERT INTO prediction_heads(fixture_id,predictor,market,selection,line_key,prediction_id,created) VALUES(?,?,?,?,?,?,?) ON CONFLICT(fixture_id,predictor,market,selection,line_key) DO UPDATE SET prediction_id=excluded.prediction_id,created=excluded.created WHERE excluded.created>prediction_heads.created OR (excluded.created=prediction_heads.created AND excluded.prediction_id>prediction_heads.prediction_id)').bind(p.fixtureId,p.predictor||'betbetter',p.market||'1X2',p.selection,String(p.line??''),p.id,p.created));}await db().batch(commands);}}
export async function cachedRead(key:string){const r:any=await db().prepare('SELECT expires,payload FROM api_cache WHERE key=?').bind(key).first();return r?{expires:r.expires,...JSON.parse(r.payload)}:null;}
export async function cachedWrite(key:string,expires:number,value:any){await db().prepare('INSERT INTO api_cache(key,expires,payload) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET expires=excluded.expires,payload=excluded.payload').bind(key,expires,JSON.stringify(value)).run();}
export async function cachedReadMany(keys:string[]){const found=new Map<string,any>();for(let i=0;i<keys.length;i+=80){const batch=keys.slice(i,i+80);const r=await db().prepare('SELECT key,expires,payload FROM api_cache WHERE key IN ('+batch.map(()=>'?').join(',')+')').bind(...batch).all();for(const row of r.results as any[])found.set(row.key,{expires:row.expires,...JSON.parse(row.payload)});}return found;}
export async function cachedWriteMany(entries:{key:string;expires:number;value:any}[]){for(let i=0;i<entries.length;i+=80)await db().batch(entries.slice(i,i+80).map(e=>db().prepare('INSERT INTO api_cache(key,expires,payload) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET expires=excluded.expires,payload=excluded.payload').bind(e.key,e.expires,JSON.stringify(e.value))));}
function decodeRows(records:any[]){return records.map(r=>({...JSON.parse(r.payload),...(r.outcome?{outcome:r.outcome}:{}),...(r.status?{status:r.status}:{})}));}
export async function predictionRows(where:string,params:any[]=[]){const r=await db().prepare('SELECT p.* FROM predictions p WHERE '+where).bind(...params).all();return decodeRows(r.results);}
export async function latestPredictions(settled=false){await ensurePredictionHeads();const r=await db().prepare(`SELECT p.id,p.fixture_id,p.created,p.outcome,json_remove(p.payload,'$.quoteComparisons') AS payload FROM prediction_heads h JOIN predictions p ON p.id=h.prediction_id JOIN fixtures f ON f.id=h.fixture_id WHERE ${settled?"json_extract(f.payload,'$.status')='finished' AND p.created<f.kickoff AND p.outcome IN ('won','lost')":"json_extract(f.payload,'$.status')='scheduled' AND f.kickoff>? AND p.outcome='pending'"}`).bind(...(settled?[]:[new Date().toISOString()])).all();return decodeRows(r.results);}
export async function recentOdds(){const r=await db().prepare("SELECT o.* FROM odds_snapshots o JOIN (SELECT o.id,ROW_NUMBER() OVER (PARTITION BY fixture_id,json_extract(payload,'$.bookmaker') ORDER BY captured DESC,id DESC) AS position FROM odds_snapshots o) ranked ON ranked.id=o.id WHERE ranked.position=1").all();return decodeRows(r.results);}
export async function historyPage(query='',outcome='all',page=0,pageSize=20){if(query.length>80||!['all','won','lost','pending'].includes(outcome)||!Number.isInteger(page)||page<0||page>100000||!Number.isInteger(pageSize)||pageSize<1||pageSize>100)throw new Error('Invalid history filter.');const filters:string[]=[],params:any[]=[];if(outcome!=='all'){filters.push('p.outcome=?');params.push(outcome);}for(const term of query.toLowerCase().split(/\s+/).filter(Boolean).slice(0,10)){filters.push("LOWER(json_extract(p.payload,'$.home') || ' ' || json_extract(p.payload,'$.away')) LIKE ? ESCAPE '\\'");params.push('%'+term.replace(/[\\%_]/g,'\\$&')+'%');}const where=filters.length?filters.join(' AND '):'1=1';const total:any=await db().prepare('SELECT COUNT(*) AS total FROM predictions p WHERE '+where).bind(...params).first();const r=await db().prepare('SELECT p.* FROM predictions p WHERE '+where+' ORDER BY p.created DESC,p.id DESC LIMIT ? OFFSET ?').bind(...params,pageSize,page*pageSize).all();return {records:decodeRows(r.results),total:Number(total.total),page,pageSize,pages:Math.ceil(Number(total.total)/pageSize)};}
export async function predictionMetrics(tickets:any[]){const result=await db().prepare("SELECT outcome,COUNT(*) AS n FROM predictions GROUP BY outcome").all();let total=0,won=0,settled=0,pending=0;for(const r of result.results as any[]){total+=Number(r.n);if(r.outcome==='pending')pending=Number(r.n);if(r.outcome==='won')won=Number(r.n);if(['won','lost'].includes(r.outcome))settled+=Number(r.n);}const dates=await db().prepare("SELECT date(created,'+3 hours') AS day,outcome,COUNT(*) AS n FROM predictions WHERE outcome IN ('won','lost') GROUP BY date(created,'+3 hours'),outcome ORDER BY day").all();const buckets=new Map<string,any>();for(const r of dates.results as any[]){const b=buckets.get(r.day)||{date:r.day,total:0,wins:0};b.total+=Number(r.n);if(r.outcome==='won')b.wins+=Number(r.n);buckets.set(r.day,b);}let cumulative=0,wins=0;const closed=tickets.filter(t=>['won','lost'].includes(t.status)),staked=closed.reduce((v,t)=>v+t.stake,0),profit=closed.reduce((v,t)=>v+(t.status==='won'?t.potentialReturn-t.stake:-t.stake),0);return {total,settled,pending,accuracy:settled?won/settled:null,staked,profit,roi:staked?profit/staked:null,trend:[...buckets.values()].map(b=>{cumulative+=b.total;wins+=b.wins;return {date:b.date,accuracy:100*wins/cumulative,picks:cumulative};})};}

export async function fixtureRowsByIds(ids:string[]){const found:any[]=[];for(let i=0;i<ids.length;i+=100){const batch=ids.slice(i,i+100);const r=await db().prepare('SELECT * FROM fixtures WHERE id IN ('+batch.map(()=>'?').join(',')+')').bind(...batch).all();found.push(...decodeRows(r.results));}return found;}
export async function researchFixtureHeads(){const r=await db().prepare(`SELECT id,kickoff,json_extract(payload,'$.arataModel') AS arataModel,json_extract(payload,'$.blendModels') AS blendModels,(SELECT json_group_array(json(q.value)) FROM json_each(f.payload,'$.quotes') q WHERE json_extract(q.value,'$.source')='Owner-entered') AS quotes FROM fixtures f`).all();return r.results.map((row:any)=>({...row,arataModel:row.arataModel?JSON.parse(row.arataModel):null,blendModels:row.blendModels?JSON.parse(row.blendModels):[],quotes:JSON.parse(row.quotes||'[]')}));}
export async function fixtureWindowRows(from:string,to:string){const r=await db().prepare(`SELECT * FROM fixtures WHERE (kickoff>=? AND kickoff<?) OR json_extract(payload,'$.status')='live'`).bind(from+'T00:00:00+03:00',new Date(Date.parse(to+'T00:00:00+03:00')+86400000).toISOString()).all();return decodeRows(r.results);}
export async function liveFixtureHeads(ticketIds:string[]=[]){const keys=['home','away','league','leagueId','status','source','sourceUrl','externalIds','score','halfTimeScore','liveClock','livePeriod','liveCaptured','liveSource','liveStale','sourceUpdated','resultSource','duplicateOf','goalScorers','eventsCaptured','eventsSource','eventsScore','detailsCoverage','finalConfirmedAt','endedAt','lastPlayClock','detailsCheckedAt','resultCheckedAt'];const projection=keys.map(k=>`json_extract(payload,'$.${k}') AS ${k}`).join(',');const ids=[...new Set(ticketIds)],found=new Map<string,any>();for(let i=0;i<Math.max(ids.length,1);i+=80){const batch=ids.slice(i,i+80),base=i===0?"(kickoff>=? AND kickoff<=?) OR json_extract(payload,'$.status')='live'":"",byId=batch.length?'id IN ('+batch.map(()=>'?').join(',')+')':'',where=[base,byId].filter(Boolean).join(' OR '),params=i===0?[new Date(Date.now()-3*86400000).toISOString(),new Date(Date.now()+86400000).toISOString(),...batch]:batch;const r=await db().prepare(`SELECT id,kickoff,${projection},CASE WHEN json_extract(payload,'$.status')='live' THEN json_extract(payload,'$.quotes') END AS quotes FROM fixtures WHERE ${where}`).bind(...params).all();for(const row of r.results as any[]){const f={...row};for(const key of ['externalIds','score','halfTimeScore','goalScorers','eventsScore','quotes'])if(typeof f[key]==='string')f[key]=JSON.parse(f[key]);f.liveStale=f.liveStale===true||f.liveStale===1||f.liveStale==='true';found.set(f.id,f);}}return [...found.values()];}

export async function resultFixtureHeads(){const keys=['home','away','league','leagueId','status','source','score','resultSource','liveSource','halfTimeScore','kickoffEAT','sourceUrl','finalConfirmedAt','endedAt','liveCaptured','sourceUpdated','duplicateOf','livePeriod'];const projection=keys.map(k=>`json_extract(payload,'$.${k}') AS ${k}`).join(',');const r=await db().prepare(`SELECT id,kickoff,${projection} FROM fixtures WHERE json_extract(payload,'$.status')='finished'`).all();return r.results.map((row:any)=>({...row,score:typeof row.score==='string'?JSON.parse(row.score):row.score,halfTimeScore:typeof row.halfTimeScore==='string'?JSON.parse(row.halfTimeScore):row.halfTimeScore}));}
