import {fixtureKey,teamKey,LEAGUES} from './domain.mjs';
import {halfLine,marketKey} from './markets.mjs';
export const BOOKMAKERS=[{id:'betpawa',name:'BetPawa Uganda',url:'https://www.betpawa.ug/'},{id:'gsb',name:'GSB Uganda',url:'https://gsb.ug/'},{id:'1xbet',name:'1XBet Uganda',url:'https://1xbet.ug/en'},{id:'betway',name:'Betway Uganda',url:'https://www.betway.ug/'},{id:'sba',name:'SBA Uganda',url:'https://www.sba.co.ug/'},{id:'betwinner',name:'Betwinner',url:'https://betwinner.com/'}];
export function eat(iso){return new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Kampala',dateStyle:'medium',timeStyle:'short'}).format(new Date(iso))+' EAT';}
export function leagueIdentity(name,region=''){const k=String(name).toLowerCase().replace(/^laliga$/,'la liga').replace(/^major league soccer$/,'mls'),r=region.toLowerCase();const l=LEAGUES.find(l=>l.name.toLowerCase()===k&&(l.id!=='epl'||r==='england'));return {league:name,leagueId:l?.id||`web:${r}:${k}`};}
export function parsePawaEvent(e,captured,sourceUrl){if(String(e.category?.id)!=='2')return null;const p=[...(e.participants||[])].sort((a,b)=>a.position-b.position);if(p.length!==2||!p.every(x=>x.name)||!Number.isFinite(Date.parse(e.startTime)))return null;
 const [home,away]=p.map(x=>x.name);if(/virtual|esport|special bets|simulated/i.test(e.competition?.name||''))return null;const league=leagueIdentity(e.competition?.name||'Unspecified league',e.region?.name||'');const kickoff=new Date(e.startTime).toISOString(),id=fixtureKey(home,away,kickoff,league.leagueId);const quotes=[];
 for(const m of e.markets||[]){const name=m.marketType?.name;for(const row of m.row||[])for(const price of row.prices||[]){let market,selection,line=null;
 if(name==='1X2 - FT'){market='1X2';selection=({'1':'home','X':'draw','2':'away'})[price.name];}
 else if(name==='Both Teams To Score - FT'){market='BTTS';selection=String(price.name).toLowerCase();if(!['yes','no'].includes(selection))continue;}
 else if(name==='Total Score Over/Under - FT'){market='TOTALS';selection=String(price.name).toLowerCase();line=Number(price.handicap??row.specifier?.total);if(!['over','under'].includes(selection)||!halfLine(line))continue;}
 else if(name==='Asian Handicap - FT'){market='HANDICAP';selection=({'1':'home','2':'away'})[price.name];line=Number(price.handicap??price.specifier?.hcp);if(!halfLine(line))continue;}
 else if(name==='Double Chance - FT'){market='DOUBLE_CHANCE';selection=price.name;if(!['1X','X2','12'].includes(selection))continue;}
 else if(['Total Score Over/Under - FT - Home Team','Total Score Over/Under - FT - Away Team'].includes(name)){market=name.includes('Home Team')?'HOME_TOTALS':'AWAY_TOTALS';selection=String(price.name).toLowerCase();line=Number(price.handicap??row.specifier?.total);if(!['over','under'].includes(selection)||!halfLine(line))continue;}
 else if(['Clean Sheet Home Team - FT','Clean Sheet Away Team - FT','Win to Nil Home Team - FT','Win to Nil Away Team - FT'].includes(name)){market=(name.includes('Home Team')?'HOME_':'AWAY_')+(name.startsWith('Clean Sheet')?'CLEAN_SHEET':'WIN_TO_NIL');selection=String(price.name).toLowerCase();if(!['yes','no'].includes(selection))continue;}
 else if(['Odd / Even - FT','Odd / Even - FT- Home Team','Odd / Even - FT - Home Team','Odd / Even - FT - Away Team'].includes(name)){market=(name.includes('Home Team')?'HOME_':name.includes('Away Team')?'AWAY_':'')+'ODD_EVEN';selection=String(price.name).toLowerCase();if(!['odd','even'].includes(selection))continue;}
 else if(['1X2 and Totals - FT','1X2 and Both Teams To Score - FT'].includes(name)){const match=String(price.name).match(/^(1|X|2)\s*-\s*(Over|Under|Yes|No)$/i);if(!match)continue;market=name.includes('Totals')?'RESULT_TOTALS':'RESULT_BTTS';selection=({'1':'home','X':'draw','2':'away'})[match[1].toUpperCase()]+'_'+match[2].toLowerCase();if(market==='RESULT_TOTALS'){line=Number(price.handicap??row.specifier?.total);if(!halfLine(line))continue;}}
 else continue;const odds=Number(price.odds);if(!selection||!Number.isFinite(odds)||odds<=1||odds>1000||price.suspended||price.additionalInfo?.suspended)continue;
 quotes.push({market,selection,line,odds,bookmaker:'BetPawa Uganda',bookmakerId:'betpawa',captured,inPlay:!!e.additionalInfo?.live,sourceUrl,externalEventId:String(e.id),externalPriceId:String(price.id),period:'FT',source:'Public bookmaker feed'});
 }}const odds=Object.fromEntries(quotes.filter(q=>q.market==='1X2').map(q=>[q.selection,q.odds]));return {id,...league,home,away,kickoff,kickoffEAT:eat(kickoff),status:e.additionalInfo?.live?'live':Date.parse(kickoff)>Date.now()?'scheduled':'awaiting-result',source:'BetPawa Uganda',sourceUrl,externalIds:{betpawa:String(e.id)},probabilities:{},models:{},marketModels:[],odds,quotes,oddsCaptured:captured,bookmaker:'BetPawa Uganda',oddsSource:'Public bookmaker feed'};
}
// Read JSON embedded in the public HTML. Never execute remote JavaScript.
export function extract1xState(html){for(const raw of html.match(/"(?:[^"\\]|\\.)*"/g)||[]){if(!raw.includes('startTimestamp'))continue;let decoded;try{decoded=JSON.parse(raw);}catch{continue;}const marker='["__BETTING_APP__"]=';const pos=decoded.indexOf(marker);if(pos<0)continue;const start=pos+marker.length;let depth=0,inString=false,escape=false;for(let i=start;i<decoded.length;i++){const c=decoded[i];if(inString){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')inString=false;}else if(c==='"')inString=true;else if(c==='{')depth++;else if(c==='}'&&--depth===0){try{return JSON.parse(decoded.slice(start,i+1));}catch{break;}}}}return null;}
export function parse1xHtml(html,url='https://1xbet.ug/en'){const state=extract1xState(html),found=new Map();function walk(o){if(Array.isArray(o))o.forEach(walk);else if(o&&typeof o==='object'){if(o.sportId===1&&o.isNotStarted&&!o.isSubGame&&o.startTimestamp&&o.firstOpponentName&&o.secondOpponentName&&!/virtual|esport|special bets|simulated|cyber/i.test(`${o.champName} ${o.firstOpponentName}`)){const kickoff=new Date(o.startTimestamp).toISOString(),home=o.firstOpponentName,away=o.secondOpponentName,l=leagueIdentity(o.champName,o.countryName),id=fixtureKey(home,away,kickoff,l.leagueId);found.set(id,{id,...l,home,away,kickoff,kickoffEAT:eat(kickoff),status:Date.parse(kickoff)>Date.now()?'scheduled':'awaiting-result',source:'1XBet Uganda',sourceUrl:url,externalIds:{'1xbet':String(o.id)},probabilities:{},models:{},marketModels:[],odds:{},quotes:[]});}Object.values(o).forEach(walk);}}walk(state);return [...found.values()];}
export function matchFixture(f,existing){return existing.find(x=>teamKey(x.home)===teamKey(f.home)&&teamKey(x.away)===teamKey(f.away)&&Math.abs(Date.parse(x.kickoff)-Date.parse(f.kickoff))<=15*60000&&(x.leagueId===f.leagueId||x.league.toLowerCase()===f.league.toLowerCase()));}
export function combineWeb(existing,incoming){const out=[...existing];for(const f of incoming){const prior=matchFixture(f,out);if(prior){const i=out.indexOf(prior),quotes=[...(prior.quotes||[]),...(f.quotes||[])];const dedup=new Map();for(const q of quotes)dedup.set(`${q.bookmakerId||q.bookmaker}|${marketKey(q)}`,q);out[i]={...prior,quotes:[...dedup.values()],externalIds:{...prior.externalIds,...f.externalIds},sourceUrls:[...new Set([...(prior.sourceUrls||[]),f.sourceUrl].filter(Boolean))]};}else out.push(f);}return out;}
