import {isHostedRequest} from './background.mjs';
import {discoveryDays} from './ingest-plan.mjs';
import {cachedRead,cachedWrite} from './store';
import {PAWA_MARKET_TYPES,withPawaMarkets} from './market-outcomes.mjs';
import {fetchCached,requestCache} from './providers';
import {BOOKMAKERS,parsePawaEvent,parse1xHtml,combineWeb,eat} from './web-parsers.mjs';
import {dayKey,dateRange} from './domain.mjs';
const base='https://www.betpawa.ug';
async function pawaConfig(memo:any){const r=await fetchCached(base+'/strapi/api/jurisdictions?filters%5Bhostname%5D%5B%24eq%5D=www.betpawa.ug&locale=en&pagination%5BpageSize%5D=1',86400000,memo);const brand=r.data.data?.[0]?.brandIdentifier;if(typeof brand!=='string')throw new Error('Public Uganda brand configuration is unavailable.');return {Accept:'application/json','X-Pawa-Brand':brand,'X-Pawa-Language':'en'};}
export async function webIngest(existing:any[],search?:string,range='week',pricesOnly=false){const memo=requestCache(),statuses:any[]=[],fixtures:any[]=[];let searchUrl='';
 await Promise.all(BOOKMAKERS.filter(b=>!pricesOnly||b.id==='betpawa').map(async b=>{try{
  if(b.id==='betpawa'){const headers=await pawaConfig(memo);let urls:string[]=[];
   if(search){searchUrl=base+'/api/sportsbook/v3/search?name='+encodeURIComponent(search);urls=[searchUrl];}
   else {const cursor=isHostedRequest()?Number((await cachedRead('discovery-cursor:'+range))?.data||0):0;const dates=discoveryDays(range,cursor,isHostedRequest());if(isHostedRequest())await cachedWrite('discovery-cursor:'+range,Number.MAX_SAFE_INTEGER,{data:cursor+1});urls=dates.map(date=>{const midnight=new Date(date+'T00:00:00+03:00'),from=midnight.toISOString(),to=new Date(midnight.getTime()+86400000).toISOString();const q={queries:[{query:{categories:['2'],startTime:{gte:from,lt:to},hasOdds:true},view:{marketTypes:PAWA_MARKET_TYPES},sort:{competitionPriority:'DESC',startTime:'ASC'},take:100,skip:0}]};return base+'/api/sportsbook/v4/events/lists/by-queries?q='+encodeURIComponent(JSON.stringify(withPawaMarkets(q)));});}
   if(!search){const catalog=await fetchCached(base+'/api/sportsbook/v4/categories/list/2',21600000,memo,{headers});const wanted:Record<string,string[]>={England:['Premier League'],Spain:['LaLiga'],Germany:['Bundesliga'],Italy:['Serie A'],France:['Ligue 1'],USA:['Major League Soccer']};const ids=catalog.data.withRegions?.flatMap((x:any)=>x.regions||[]).flatMap((r:any)=>(r.competitions||[]).filter((c:any)=>wanted[r.region?.name]?.includes(c.competition?.name)).map((c:any)=>String(c.competition.id)))||[];if(ids.length){const selected=dateRange(range),start=new Date(selected.from+'T00:00:00+03:00'),end=new Date(new Date(selected.to+'T00:00:00+03:00').getTime()+86400000),q={queries:[{query:{categories:['2'],zones:{competitions:ids},startTime:{gte:start.toISOString(),lt:end.toISOString()},hasOdds:true},view:{marketTypes:PAWA_MARKET_TYPES},sort:{startTime:'ASC'},take:100,skip:0}]};urls.push(base+'/api/sportsbook/v4/events/lists/by-queries?q='+encodeURIComponent(JSON.stringify(withPawaMarkets(q))));}}
   const results:any[]=[];for(const url of urls){try{const pageMemo=requestCache(),r=await fetchCached(url,60000,pageMemo,{headers});const events=search?r.data.events:r.data.responses?.flatMap((x:any)=>x.responses)||[];if(!Array.isArray(events))throw new Error('Unexpected football feed structure.');const parsed=events.map((e:any)=>parsePawaEvent(e,r.captured,url)).filter(Boolean);results.push({status:'fulfilled',value:{r:{stale:r.stale,captured:r.captured,capped:r.data.responses?.some((x:any)=>x.responses?.length===100)},parsed,url}});}catch(reason){results.push({status:'rejected',reason});}}
   const fixtureIds=new Set<string>();let count=0,quotes=0,capped=0,stale=false,failed=0;for(const x of results){if(x.status==='rejected'){failed++;continue;}const {r,parsed,url}=x.value;stale||=r.stale;if(r.capped)capped++;for(const f of parsed){if(f){f.quotes=f.quotes.map((q:any)=>({...q,stale:r.stale}));fixtures.push(f);fixtureIds.add(f.id);count++;quotes+=f.quotes.length;}}}
   if(!count&&failed)throw new Error('Public football requests failed.');statuses.push({name:b.name,status:stale?'cached':failed?'partial':'connected',count:fixtureIds.size,quoteCount:quotes,captured:new Date().toISOString(),stale,message:`${search?'Public team search':'Incremental date discovery, up to 100 events per fetched day'}. ${capped} day(s) reached the limit. ${failed} request(s) failed. Published full-time markets, including team totals, clean sheets and result combinations; binary settlement only.`});return;
  }
  const r=await fetchCached(b.url,900000,memo,{text:true,headers:{Accept:'text/html'},timeoutMs:4000,retries:1});
  if(b.id==='1xbet'){const fs=parse1xHtml(r.data,b.url).filter((f:any)=>!search||`${f.home} ${f.away} ${f.league}`.toLowerCase().includes(search.toLowerCase()));fixtures.push(...fs);statuses.push({name:b.name,status:fs.length?'partial':'unavailable',count:fs.length,quoteCount:0,captured:r.captured,stale:r.stale,message:'Public Uganda page fixtures. Prices are omitted from its embedded data; no prices inferred.'});return;}
  // These public pages do not expose a verified machine-readable Uganda odds contract.
  statuses.push({name:b.name,status:'unavailable',count:0,quoteCount:0,captured:r.captured,message:b.id==='betway'?'The Uganda URL currently redirects to South Africa. South African prices are excluded.':'Public page loaded, but a verified Uganda fixture/odds feed is unavailable. Use owner-entered prices.'});
 }catch(e){statuses.push({name:b.name,status:'unavailable',count:0,quoteCount:0,message:(e as Error).message+' No login, challenge bypass or invented prices.'});}}));
 const combined=combineWeb(existing,fixtures).map((f:any)=>({...f,kickoffEAT:eat(f.kickoff)}));return {fixtures:combined,statuses,discovery:{strategy:'Curated official football and Uganda bookmaker sources; public JSON and embedded page data',timezone:'Africa/Kampala',coverage:'BetPawa: selected EAT dates, at most 100 events per fetched date, plus up to 100 fixtures across six model-covered leagues in the selected period. Hosted week/upcoming dates rotate across refreshes. 1XBet: public page highlights. Not exhaustive.',search:search||null,searchUrl:searchUrl||null}};
}
